FROM golang:1.26-alpine AS builder

WORKDIR /app

RUN go env -w GOPROXY=https://goproxy.cn,direct
COPY go.mod go.sum ./
RUN go mod download


COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o aibuddy .

FROM alpine:3.23.3

WORKDIR /app

RUN sed -i 's#https\?://dl-cdn.alpinelinux.org/alpine#https://mirrors.tuna.tsinghua.edu.cn/alpine#g' /etc/apk/repositories

RUN apk --no-cache add ca-certificates tzdata ffmpeg
ENV TZ=Asia/Shanghai


COPY --from=builder /app/aibuddy .
COPY config ./config

EXPOSE 9081

CMD ["./aibuddy"]
