// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"aibuddy/internal/model"
)

func newDeviceMessage(db *gorm.DB, opts ...gen.DOOption) deviceMessage {
	_deviceMessage := deviceMessage{}

	_deviceMessage.deviceMessageDo.UseDB(db, opts...)
	_deviceMessage.deviceMessageDo.UseModel(&model.DeviceMessage{})

	tableName := _deviceMessage.deviceMessageDo.TableName()
	_deviceMessage.ALL = field.NewAsterisk(tableName)
	_deviceMessage.ID = field.NewInt(tableName, "id")
	_deviceMessage.MsgID = field.NewString(tableName, "msg_id")
	_deviceMessage.FromDeviceID = field.NewString(tableName, "from_device_id")
	_deviceMessage.FromUsername = field.NewString(tableName, "from_username")
	_deviceMessage.ToDeviceID = field.NewString(tableName, "to_device_id")
	_deviceMessage.Content = field.NewString(tableName, "content")
	_deviceMessage.Fmt = field.NewString(tableName, "fmt")
	_deviceMessage.Dur = field.NewInt(tableName, "dur")
	_deviceMessage.Read = field.NewBool(tableName, "read")
	_deviceMessage.CreatedAt = field.NewTime(tableName, "created_at")
	_deviceMessage.UpdatedAt = field.NewTime(tableName, "updated_at")
	_deviceMessage.Device = deviceMessageBelongsToDevice{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("Device", "model.Device"),
		User: struct {
			field.RelationField
		}{
			RelationField: field.NewRelation("Device.User", "model.User"),
		},
		DeviceInfo: struct {
			field.RelationField
		}{
			RelationField: field.NewRelation("Device.DeviceInfo", "model.DeviceInfo"),
		},
	}

	_deviceMessage.ToDevice = deviceMessageBelongsToToDevice{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("ToDevice", "model.Device"),
	}

	_deviceMessage.fillFieldMap()

	return _deviceMessage
}

type deviceMessage struct {
	deviceMessageDo

	ALL          field.Asterisk
	ID           field.Int
	MsgID        field.String
	FromDeviceID field.String
	FromUsername field.String
	ToDeviceID   field.String
	Content      field.String
	Fmt          field.String
	Dur          field.Int
	Read         field.Bool
	CreatedAt    field.Time
	UpdatedAt    field.Time
	Device       deviceMessageBelongsToDevice

	ToDevice deviceMessageBelongsToToDevice

	fieldMap map[string]field.Expr
}

func (d deviceMessage) Table(newTableName string) *deviceMessage {
	d.deviceMessageDo.UseTable(newTableName)
	return d.updateTableName(newTableName)
}

func (d deviceMessage) As(alias string) *deviceMessage {
	d.deviceMessageDo.DO = *(d.deviceMessageDo.As(alias).(*gen.DO))
	return d.updateTableName(alias)
}

func (d *deviceMessage) updateTableName(table string) *deviceMessage {
	d.ALL = field.NewAsterisk(table)
	d.ID = field.NewInt(table, "id")
	d.MsgID = field.NewString(table, "msg_id")
	d.FromDeviceID = field.NewString(table, "from_device_id")
	d.FromUsername = field.NewString(table, "from_username")
	d.ToDeviceID = field.NewString(table, "to_device_id")
	d.Content = field.NewString(table, "content")
	d.Fmt = field.NewString(table, "fmt")
	d.Dur = field.NewInt(table, "dur")
	d.Read = field.NewBool(table, "read")
	d.CreatedAt = field.NewTime(table, "created_at")
	d.UpdatedAt = field.NewTime(table, "updated_at")

	d.fillFieldMap()

	return d
}

func (d *deviceMessage) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := d.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (d *deviceMessage) fillFieldMap() {
	d.fieldMap = make(map[string]field.Expr, 13)
	d.fieldMap["id"] = d.ID
	d.fieldMap["msg_id"] = d.MsgID
	d.fieldMap["from_device_id"] = d.FromDeviceID
	d.fieldMap["from_username"] = d.FromUsername
	d.fieldMap["to_device_id"] = d.ToDeviceID
	d.fieldMap["content"] = d.Content
	d.fieldMap["fmt"] = d.Fmt
	d.fieldMap["dur"] = d.Dur
	d.fieldMap["read"] = d.Read
	d.fieldMap["created_at"] = d.CreatedAt
	d.fieldMap["updated_at"] = d.UpdatedAt

}

func (d deviceMessage) clone(db *gorm.DB) deviceMessage {
	d.deviceMessageDo.ReplaceConnPool(db.Statement.ConnPool)
	d.Device.db = db.Session(&gorm.Session{Initialized: true})
	d.Device.db.Statement.ConnPool = db.Statement.ConnPool
	d.ToDevice.db = db.Session(&gorm.Session{Initialized: true})
	d.ToDevice.db.Statement.ConnPool = db.Statement.ConnPool
	return d
}

func (d deviceMessage) replaceDB(db *gorm.DB) deviceMessage {
	d.deviceMessageDo.ReplaceDB(db)
	d.Device.db = db.Session(&gorm.Session{})
	d.ToDevice.db = db.Session(&gorm.Session{})
	return d
}

type deviceMessageBelongsToDevice struct {
	db *gorm.DB

	field.RelationField

	User struct {
		field.RelationField
	}
	DeviceInfo struct {
		field.RelationField
	}
}

func (a deviceMessageBelongsToDevice) Where(conds ...field.Expr) *deviceMessageBelongsToDevice {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a deviceMessageBelongsToDevice) WithContext(ctx context.Context) *deviceMessageBelongsToDevice {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a deviceMessageBelongsToDevice) Session(session *gorm.Session) *deviceMessageBelongsToDevice {
	a.db = a.db.Session(session)
	return &a
}

func (a deviceMessageBelongsToDevice) Model(m *model.DeviceMessage) *deviceMessageBelongsToDeviceTx {
	return &deviceMessageBelongsToDeviceTx{a.db.Model(m).Association(a.Name())}
}

func (a deviceMessageBelongsToDevice) Unscoped() *deviceMessageBelongsToDevice {
	a.db = a.db.Unscoped()
	return &a
}

type deviceMessageBelongsToDeviceTx struct{ tx *gorm.Association }

func (a deviceMessageBelongsToDeviceTx) Find() (result *model.Device, err error) {
	return result, a.tx.Find(&result)
}

func (a deviceMessageBelongsToDeviceTx) Append(values ...*model.Device) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a deviceMessageBelongsToDeviceTx) Replace(values ...*model.Device) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a deviceMessageBelongsToDeviceTx) Delete(values ...*model.Device) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a deviceMessageBelongsToDeviceTx) Clear() error {
	return a.tx.Clear()
}

func (a deviceMessageBelongsToDeviceTx) Count() int64 {
	return a.tx.Count()
}

func (a deviceMessageBelongsToDeviceTx) Unscoped() *deviceMessageBelongsToDeviceTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type deviceMessageBelongsToToDevice struct {
	db *gorm.DB

	field.RelationField
}

func (a deviceMessageBelongsToToDevice) Where(conds ...field.Expr) *deviceMessageBelongsToToDevice {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a deviceMessageBelongsToToDevice) WithContext(ctx context.Context) *deviceMessageBelongsToToDevice {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a deviceMessageBelongsToToDevice) Session(session *gorm.Session) *deviceMessageBelongsToToDevice {
	a.db = a.db.Session(session)
	return &a
}

func (a deviceMessageBelongsToToDevice) Model(m *model.DeviceMessage) *deviceMessageBelongsToToDeviceTx {
	return &deviceMessageBelongsToToDeviceTx{a.db.Model(m).Association(a.Name())}
}

func (a deviceMessageBelongsToToDevice) Unscoped() *deviceMessageBelongsToToDevice {
	a.db = a.db.Unscoped()
	return &a
}

type deviceMessageBelongsToToDeviceTx struct{ tx *gorm.Association }

func (a deviceMessageBelongsToToDeviceTx) Find() (result *model.Device, err error) {
	return result, a.tx.Find(&result)
}

func (a deviceMessageBelongsToToDeviceTx) Append(values ...*model.Device) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a deviceMessageBelongsToToDeviceTx) Replace(values ...*model.Device) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a deviceMessageBelongsToToDeviceTx) Delete(values ...*model.Device) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a deviceMessageBelongsToToDeviceTx) Clear() error {
	return a.tx.Clear()
}

func (a deviceMessageBelongsToToDeviceTx) Count() int64 {
	return a.tx.Count()
}

func (a deviceMessageBelongsToToDeviceTx) Unscoped() *deviceMessageBelongsToToDeviceTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type deviceMessageDo struct{ gen.DO }

type IDeviceMessageDo interface {
	gen.SubQuery
	Debug() IDeviceMessageDo
	WithContext(ctx context.Context) IDeviceMessageDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IDeviceMessageDo
	WriteDB() IDeviceMessageDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IDeviceMessageDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IDeviceMessageDo
	Not(conds ...gen.Condition) IDeviceMessageDo
	Or(conds ...gen.Condition) IDeviceMessageDo
	Select(conds ...field.Expr) IDeviceMessageDo
	Where(conds ...gen.Condition) IDeviceMessageDo
	Order(conds ...field.Expr) IDeviceMessageDo
	Distinct(cols ...field.Expr) IDeviceMessageDo
	Omit(cols ...field.Expr) IDeviceMessageDo
	Join(table schema.Tabler, on ...field.Expr) IDeviceMessageDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IDeviceMessageDo
	RightJoin(table schema.Tabler, on ...field.Expr) IDeviceMessageDo
	Group(cols ...field.Expr) IDeviceMessageDo
	Having(conds ...gen.Condition) IDeviceMessageDo
	Limit(limit int) IDeviceMessageDo
	Offset(offset int) IDeviceMessageDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IDeviceMessageDo
	Unscoped() IDeviceMessageDo
	Create(values ...*model.DeviceMessage) error
	CreateInBatches(values []*model.DeviceMessage, batchSize int) error
	Save(values ...*model.DeviceMessage) error
	First() (*model.DeviceMessage, error)
	Take() (*model.DeviceMessage, error)
	Last() (*model.DeviceMessage, error)
	Find() ([]*model.DeviceMessage, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.DeviceMessage, err error)
	FindInBatches(result *[]*model.DeviceMessage, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.DeviceMessage) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IDeviceMessageDo
	Assign(attrs ...field.AssignExpr) IDeviceMessageDo
	Joins(fields ...field.RelationField) IDeviceMessageDo
	Preload(fields ...field.RelationField) IDeviceMessageDo
	FirstOrInit() (*model.DeviceMessage, error)
	FirstOrCreate() (*model.DeviceMessage, error)
	FindByPage(offset int, limit int) (result []*model.DeviceMessage, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IDeviceMessageDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (d deviceMessageDo) Debug() IDeviceMessageDo {
	return d.withDO(d.DO.Debug())
}

func (d deviceMessageDo) WithContext(ctx context.Context) IDeviceMessageDo {
	return d.withDO(d.DO.WithContext(ctx))
}

func (d deviceMessageDo) ReadDB() IDeviceMessageDo {
	return d.Clauses(dbresolver.Read)
}

func (d deviceMessageDo) WriteDB() IDeviceMessageDo {
	return d.Clauses(dbresolver.Write)
}

func (d deviceMessageDo) Session(config *gorm.Session) IDeviceMessageDo {
	return d.withDO(d.DO.Session(config))
}

func (d deviceMessageDo) Clauses(conds ...clause.Expression) IDeviceMessageDo {
	return d.withDO(d.DO.Clauses(conds...))
}

func (d deviceMessageDo) Returning(value interface{}, columns ...string) IDeviceMessageDo {
	return d.withDO(d.DO.Returning(value, columns...))
}

func (d deviceMessageDo) Not(conds ...gen.Condition) IDeviceMessageDo {
	return d.withDO(d.DO.Not(conds...))
}

func (d deviceMessageDo) Or(conds ...gen.Condition) IDeviceMessageDo {
	return d.withDO(d.DO.Or(conds...))
}

func (d deviceMessageDo) Select(conds ...field.Expr) IDeviceMessageDo {
	return d.withDO(d.DO.Select(conds...))
}

func (d deviceMessageDo) Where(conds ...gen.Condition) IDeviceMessageDo {
	return d.withDO(d.DO.Where(conds...))
}

func (d deviceMessageDo) Order(conds ...field.Expr) IDeviceMessageDo {
	return d.withDO(d.DO.Order(conds...))
}

func (d deviceMessageDo) Distinct(cols ...field.Expr) IDeviceMessageDo {
	return d.withDO(d.DO.Distinct(cols...))
}

func (d deviceMessageDo) Omit(cols ...field.Expr) IDeviceMessageDo {
	return d.withDO(d.DO.Omit(cols...))
}

func (d deviceMessageDo) Join(table schema.Tabler, on ...field.Expr) IDeviceMessageDo {
	return d.withDO(d.DO.Join(table, on...))
}

func (d deviceMessageDo) LeftJoin(table schema.Tabler, on ...field.Expr) IDeviceMessageDo {
	return d.withDO(d.DO.LeftJoin(table, on...))
}

func (d deviceMessageDo) RightJoin(table schema.Tabler, on ...field.Expr) IDeviceMessageDo {
	return d.withDO(d.DO.RightJoin(table, on...))
}

func (d deviceMessageDo) Group(cols ...field.Expr) IDeviceMessageDo {
	return d.withDO(d.DO.Group(cols...))
}

func (d deviceMessageDo) Having(conds ...gen.Condition) IDeviceMessageDo {
	return d.withDO(d.DO.Having(conds...))
}

func (d deviceMessageDo) Limit(limit int) IDeviceMessageDo {
	return d.withDO(d.DO.Limit(limit))
}

func (d deviceMessageDo) Offset(offset int) IDeviceMessageDo {
	return d.withDO(d.DO.Offset(offset))
}

func (d deviceMessageDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IDeviceMessageDo {
	return d.withDO(d.DO.Scopes(funcs...))
}

func (d deviceMessageDo) Unscoped() IDeviceMessageDo {
	return d.withDO(d.DO.Unscoped())
}

func (d deviceMessageDo) Create(values ...*model.DeviceMessage) error {
	if len(values) == 0 {
		return nil
	}
	return d.DO.Create(values)
}

func (d deviceMessageDo) CreateInBatches(values []*model.DeviceMessage, batchSize int) error {
	return d.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (d deviceMessageDo) Save(values ...*model.DeviceMessage) error {
	if len(values) == 0 {
		return nil
	}
	return d.DO.Save(values)
}

func (d deviceMessageDo) First() (*model.DeviceMessage, error) {
	if result, err := d.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.DeviceMessage), nil
	}
}

func (d deviceMessageDo) Take() (*model.DeviceMessage, error) {
	if result, err := d.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.DeviceMessage), nil
	}
}

func (d deviceMessageDo) Last() (*model.DeviceMessage, error) {
	if result, err := d.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.DeviceMessage), nil
	}
}

func (d deviceMessageDo) Find() ([]*model.DeviceMessage, error) {
	result, err := d.DO.Find()
	return result.([]*model.DeviceMessage), err
}

func (d deviceMessageDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.DeviceMessage, err error) {
	buf := make([]*model.DeviceMessage, 0, batchSize)
	err = d.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (d deviceMessageDo) FindInBatches(result *[]*model.DeviceMessage, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return d.DO.FindInBatches(result, batchSize, fc)
}

func (d deviceMessageDo) Attrs(attrs ...field.AssignExpr) IDeviceMessageDo {
	return d.withDO(d.DO.Attrs(attrs...))
}

func (d deviceMessageDo) Assign(attrs ...field.AssignExpr) IDeviceMessageDo {
	return d.withDO(d.DO.Assign(attrs...))
}

func (d deviceMessageDo) Joins(fields ...field.RelationField) IDeviceMessageDo {
	for _, _f := range fields {
		d = *d.withDO(d.DO.Joins(_f))
	}
	return &d
}

func (d deviceMessageDo) Preload(fields ...field.RelationField) IDeviceMessageDo {
	for _, _f := range fields {
		d = *d.withDO(d.DO.Preload(_f))
	}
	return &d
}

func (d deviceMessageDo) FirstOrInit() (*model.DeviceMessage, error) {
	if result, err := d.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.DeviceMessage), nil
	}
}

func (d deviceMessageDo) FirstOrCreate() (*model.DeviceMessage, error) {
	if result, err := d.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.DeviceMessage), nil
	}
}

func (d deviceMessageDo) FindByPage(offset int, limit int) (result []*model.DeviceMessage, count int64, err error) {
	result, err = d.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = d.Offset(-1).Limit(-1).Count()
	return
}

func (d deviceMessageDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = d.Count()
	if err != nil {
		return
	}

	err = d.Offset(offset).Limit(limit).Scan(result)
	return
}

func (d deviceMessageDo) Scan(result interface{}) (err error) {
	return d.DO.Scan(result)
}

func (d deviceMessageDo) Delete(models ...*model.DeviceMessage) (result gen.ResultInfo, err error) {
	return d.DO.Delete(models)
}

func (d *deviceMessageDo) withDO(do gen.Dao) *deviceMessageDo {
	d.DO = *do.(*gen.DO)
	return d
}
