// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"aibuddy/internal/model"
)

func newDeviceSN(db *gorm.DB, opts ...gen.DOOption) deviceSN {
	_deviceSN := deviceSN{}

	_deviceSN.deviceSNDo.UseDB(db, opts...)
	_deviceSN.deviceSNDo.UseModel(&model.DeviceSN{})

	tableName := _deviceSN.deviceSNDo.TableName()
	_deviceSN.ALL = field.NewAsterisk(tableName)
	_deviceSN.ID = field.NewInt64(tableName, "id")
	_deviceSN.SN = field.NewString(tableName, "sn")
	_deviceSN.DeviceID = field.NewString(tableName, "device_id")
	_deviceSN.IsValid = field.NewBool(tableName, "is_valid")
	_deviceSN.CreatedAt = field.NewTime(tableName, "created_at")
	_deviceSN.UpdatedAt = field.NewTime(tableName, "updated_at")

	_deviceSN.fillFieldMap()

	return _deviceSN
}

type deviceSN struct {
	deviceSNDo

	ALL       field.Asterisk
	ID        field.Int64
	SN        field.String
	DeviceID  field.String
	IsValid   field.Bool
	CreatedAt field.Time
	UpdatedAt field.Time

	fieldMap map[string]field.Expr
}

func (d deviceSN) Table(newTableName string) *deviceSN {
	d.deviceSNDo.UseTable(newTableName)
	return d.updateTableName(newTableName)
}

func (d deviceSN) As(alias string) *deviceSN {
	d.deviceSNDo.DO = *(d.deviceSNDo.As(alias).(*gen.DO))
	return d.updateTableName(alias)
}

func (d *deviceSN) updateTableName(table string) *deviceSN {
	d.ALL = field.NewAsterisk(table)
	d.ID = field.NewInt64(table, "id")
	d.SN = field.NewString(table, "sn")
	d.DeviceID = field.NewString(table, "device_id")
	d.IsValid = field.NewBool(table, "is_valid")
	d.CreatedAt = field.NewTime(table, "created_at")
	d.UpdatedAt = field.NewTime(table, "updated_at")

	d.fillFieldMap()

	return d
}

func (d *deviceSN) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := d.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (d *deviceSN) fillFieldMap() {
	d.fieldMap = make(map[string]field.Expr, 6)
	d.fieldMap["id"] = d.ID
	d.fieldMap["sn"] = d.SN
	d.fieldMap["device_id"] = d.DeviceID
	d.fieldMap["is_valid"] = d.IsValid
	d.fieldMap["created_at"] = d.CreatedAt
	d.fieldMap["updated_at"] = d.UpdatedAt
}

func (d deviceSN) clone(db *gorm.DB) deviceSN {
	d.deviceSNDo.ReplaceConnPool(db.Statement.ConnPool)
	return d
}

func (d deviceSN) replaceDB(db *gorm.DB) deviceSN {
	d.deviceSNDo.ReplaceDB(db)
	return d
}

type deviceSNDo struct{ gen.DO }

type IDeviceSNDo interface {
	gen.SubQuery
	Debug() IDeviceSNDo
	WithContext(ctx context.Context) IDeviceSNDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IDeviceSNDo
	WriteDB() IDeviceSNDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IDeviceSNDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IDeviceSNDo
	Not(conds ...gen.Condition) IDeviceSNDo
	Or(conds ...gen.Condition) IDeviceSNDo
	Select(conds ...field.Expr) IDeviceSNDo
	Where(conds ...gen.Condition) IDeviceSNDo
	Order(conds ...field.Expr) IDeviceSNDo
	Distinct(cols ...field.Expr) IDeviceSNDo
	Omit(cols ...field.Expr) IDeviceSNDo
	Join(table schema.Tabler, on ...field.Expr) IDeviceSNDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IDeviceSNDo
	RightJoin(table schema.Tabler, on ...field.Expr) IDeviceSNDo
	Group(cols ...field.Expr) IDeviceSNDo
	Having(conds ...gen.Condition) IDeviceSNDo
	Limit(limit int) IDeviceSNDo
	Offset(offset int) IDeviceSNDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IDeviceSNDo
	Unscoped() IDeviceSNDo
	Create(values ...*model.DeviceSN) error
	CreateInBatches(values []*model.DeviceSN, batchSize int) error
	Save(values ...*model.DeviceSN) error
	First() (*model.DeviceSN, error)
	Take() (*model.DeviceSN, error)
	Last() (*model.DeviceSN, error)
	Find() ([]*model.DeviceSN, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.DeviceSN, err error)
	FindInBatches(result *[]*model.DeviceSN, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.DeviceSN) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IDeviceSNDo
	Assign(attrs ...field.AssignExpr) IDeviceSNDo
	Joins(fields ...field.RelationField) IDeviceSNDo
	Preload(fields ...field.RelationField) IDeviceSNDo
	FirstOrInit() (*model.DeviceSN, error)
	FirstOrCreate() (*model.DeviceSN, error)
	FindByPage(offset int, limit int) (result []*model.DeviceSN, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IDeviceSNDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (d deviceSNDo) Debug() IDeviceSNDo {
	return d.withDO(d.DO.Debug())
}

func (d deviceSNDo) WithContext(ctx context.Context) IDeviceSNDo {
	return d.withDO(d.DO.WithContext(ctx))
}

func (d deviceSNDo) ReadDB() IDeviceSNDo {
	return d.Clauses(dbresolver.Read)
}

func (d deviceSNDo) WriteDB() IDeviceSNDo {
	return d.Clauses(dbresolver.Write)
}

func (d deviceSNDo) Session(config *gorm.Session) IDeviceSNDo {
	return d.withDO(d.DO.Session(config))
}

func (d deviceSNDo) Clauses(conds ...clause.Expression) IDeviceSNDo {
	return d.withDO(d.DO.Clauses(conds...))
}

func (d deviceSNDo) Returning(value interface{}, columns ...string) IDeviceSNDo {
	return d.withDO(d.DO.Returning(value, columns...))
}

func (d deviceSNDo) Not(conds ...gen.Condition) IDeviceSNDo {
	return d.withDO(d.DO.Not(conds...))
}

func (d deviceSNDo) Or(conds ...gen.Condition) IDeviceSNDo {
	return d.withDO(d.DO.Or(conds...))
}

func (d deviceSNDo) Select(conds ...field.Expr) IDeviceSNDo {
	return d.withDO(d.DO.Select(conds...))
}

func (d deviceSNDo) Where(conds ...gen.Condition) IDeviceSNDo {
	return d.withDO(d.DO.Where(conds...))
}

func (d deviceSNDo) Order(conds ...field.Expr) IDeviceSNDo {
	return d.withDO(d.DO.Order(conds...))
}

func (d deviceSNDo) Distinct(cols ...field.Expr) IDeviceSNDo {
	return d.withDO(d.DO.Distinct(cols...))
}

func (d deviceSNDo) Omit(cols ...field.Expr) IDeviceSNDo {
	return d.withDO(d.DO.Omit(cols...))
}

func (d deviceSNDo) Join(table schema.Tabler, on ...field.Expr) IDeviceSNDo {
	return d.withDO(d.DO.Join(table, on...))
}

func (d deviceSNDo) LeftJoin(table schema.Tabler, on ...field.Expr) IDeviceSNDo {
	return d.withDO(d.DO.LeftJoin(table, on...))
}

func (d deviceSNDo) RightJoin(table schema.Tabler, on ...field.Expr) IDeviceSNDo {
	return d.withDO(d.DO.RightJoin(table, on...))
}

func (d deviceSNDo) Group(cols ...field.Expr) IDeviceSNDo {
	return d.withDO(d.DO.Group(cols...))
}

func (d deviceSNDo) Having(conds ...gen.Condition) IDeviceSNDo {
	return d.withDO(d.DO.Having(conds...))
}

func (d deviceSNDo) Limit(limit int) IDeviceSNDo {
	return d.withDO(d.DO.Limit(limit))
}

func (d deviceSNDo) Offset(offset int) IDeviceSNDo {
	return d.withDO(d.DO.Offset(offset))
}

func (d deviceSNDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IDeviceSNDo {
	return d.withDO(d.DO.Scopes(funcs...))
}

func (d deviceSNDo) Unscoped() IDeviceSNDo {
	return d.withDO(d.DO.Unscoped())
}

func (d deviceSNDo) Create(values ...*model.DeviceSN) error {
	if len(values) == 0 {
		return nil
	}
	return d.DO.Create(values)
}

func (d deviceSNDo) CreateInBatches(values []*model.DeviceSN, batchSize int) error {
	return d.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (d deviceSNDo) Save(values ...*model.DeviceSN) error {
	if len(values) == 0 {
		return nil
	}
	return d.DO.Save(values)
}

func (d deviceSNDo) First() (*model.DeviceSN, error) {
	if result, err := d.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.DeviceSN), nil
	}
}

func (d deviceSNDo) Take() (*model.DeviceSN, error) {
	if result, err := d.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.DeviceSN), nil
	}
}

func (d deviceSNDo) Last() (*model.DeviceSN, error) {
	if result, err := d.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.DeviceSN), nil
	}
}

func (d deviceSNDo) Find() ([]*model.DeviceSN, error) {
	result, err := d.DO.Find()
	return result.([]*model.DeviceSN), err
}

func (d deviceSNDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.DeviceSN, err error) {
	buf := make([]*model.DeviceSN, 0, batchSize)
	err = d.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (d deviceSNDo) FindInBatches(result *[]*model.DeviceSN, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return d.DO.FindInBatches(result, batchSize, fc)
}

func (d deviceSNDo) Attrs(attrs ...field.AssignExpr) IDeviceSNDo {
	return d.withDO(d.DO.Attrs(attrs...))
}

func (d deviceSNDo) Assign(attrs ...field.AssignExpr) IDeviceSNDo {
	return d.withDO(d.DO.Assign(attrs...))
}

func (d deviceSNDo) Joins(fields ...field.RelationField) IDeviceSNDo {
	for _, _f := range fields {
		d = *d.withDO(d.DO.Joins(_f))
	}
	return &d
}

func (d deviceSNDo) Preload(fields ...field.RelationField) IDeviceSNDo {
	for _, _f := range fields {
		d = *d.withDO(d.DO.Preload(_f))
	}
	return &d
}

func (d deviceSNDo) FirstOrInit() (*model.DeviceSN, error) {
	if result, err := d.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.DeviceSN), nil
	}
}

func (d deviceSNDo) FirstOrCreate() (*model.DeviceSN, error) {
	if result, err := d.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.DeviceSN), nil
	}
}

func (d deviceSNDo) FindByPage(offset int, limit int) (result []*model.DeviceSN, count int64, err error) {
	result, err = d.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = d.Offset(-1).Limit(-1).Count()
	return
}

func (d deviceSNDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = d.Count()
	if err != nil {
		return
	}

	err = d.Offset(offset).Limit(limit).Scan(result)
	return
}

func (d deviceSNDo) Scan(result interface{}) (err error) {
	return d.DO.Scan(result)
}

func (d deviceSNDo) Delete(models ...*model.DeviceSN) (result gen.ResultInfo, err error) {
	return d.DO.Delete(models)
}

func (d *deviceSNDo) withDO(do gen.Dao) *deviceSNDo {
	d.DO = *do.(*gen.DO)
	return d
}
