// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"aibuddy/internal/model"
)

func newGoodsActivity(db *gorm.DB, opts ...gen.DOOption) goodsActivity {
	_goodsActivity := goodsActivity{}

	_goodsActivity.goodsActivityDo.UseDB(db, opts...)
	_goodsActivity.goodsActivityDo.UseModel(&model.GoodsActivity{})

	tableName := _goodsActivity.goodsActivityDo.TableName()
	_goodsActivity.ALL = field.NewAsterisk(tableName)
	_goodsActivity.ID = field.NewInt64(tableName, "id")
	_goodsActivity.GoodsID = field.NewInt64(tableName, "goods_id")
	_goodsActivity.Pirce = field.NewInt64(tableName, "price")
	_goodsActivity.Type = field.NewInt(tableName, "type")
	_goodsActivity.Count_ = field.NewInt64(tableName, "count")
	_goodsActivity.Title = field.NewString(tableName, "title")
	_goodsActivity.Desc = field.NewString(tableName, "desc")
	_goodsActivity.StartTime = field.NewTime(tableName, "start_time")
	_goodsActivity.EndTime = field.NewTime(tableName, "end_time")
	_goodsActivity.GoodsInfo = goodsActivityBelongsToGoodsInfo{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("GoodsInfo", "model.Goods"),
	}

	_goodsActivity.fillFieldMap()

	return _goodsActivity
}

type goodsActivity struct {
	goodsActivityDo

	ALL       field.Asterisk
	ID        field.Int64
	GoodsID   field.Int64  // 商品ID
	Pirce     field.Int64  // 活动价格
	Type      field.Int    // 活动类型
	Count_    field.Int64  // 活动数量
	Title     field.String // 活动标题
	Desc      field.String // 活动描述
	StartTime field.Time   // 活动开始时间
	EndTime   field.Time   // 活动结束时间
	GoodsInfo goodsActivityBelongsToGoodsInfo

	fieldMap map[string]field.Expr
}

func (g goodsActivity) Table(newTableName string) *goodsActivity {
	g.goodsActivityDo.UseTable(newTableName)
	return g.updateTableName(newTableName)
}

func (g goodsActivity) As(alias string) *goodsActivity {
	g.goodsActivityDo.DO = *(g.goodsActivityDo.As(alias).(*gen.DO))
	return g.updateTableName(alias)
}

func (g *goodsActivity) updateTableName(table string) *goodsActivity {
	g.ALL = field.NewAsterisk(table)
	g.ID = field.NewInt64(table, "id")
	g.GoodsID = field.NewInt64(table, "goods_id")
	g.Pirce = field.NewInt64(table, "price")
	g.Type = field.NewInt(table, "type")
	g.Count_ = field.NewInt64(table, "count")
	g.Title = field.NewString(table, "title")
	g.Desc = field.NewString(table, "desc")
	g.StartTime = field.NewTime(table, "start_time")
	g.EndTime = field.NewTime(table, "end_time")

	g.fillFieldMap()

	return g
}

func (g *goodsActivity) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := g.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (g *goodsActivity) fillFieldMap() {
	g.fieldMap = make(map[string]field.Expr, 10)
	g.fieldMap["id"] = g.ID
	g.fieldMap["goods_id"] = g.GoodsID
	g.fieldMap["price"] = g.Pirce
	g.fieldMap["type"] = g.Type
	g.fieldMap["count"] = g.Count_
	g.fieldMap["title"] = g.Title
	g.fieldMap["desc"] = g.Desc
	g.fieldMap["start_time"] = g.StartTime
	g.fieldMap["end_time"] = g.EndTime

}

func (g goodsActivity) clone(db *gorm.DB) goodsActivity {
	g.goodsActivityDo.ReplaceConnPool(db.Statement.ConnPool)
	g.GoodsInfo.db = db.Session(&gorm.Session{Initialized: true})
	g.GoodsInfo.db.Statement.ConnPool = db.Statement.ConnPool
	return g
}

func (g goodsActivity) replaceDB(db *gorm.DB) goodsActivity {
	g.goodsActivityDo.ReplaceDB(db)
	g.GoodsInfo.db = db.Session(&gorm.Session{})
	return g
}

type goodsActivityBelongsToGoodsInfo struct {
	db *gorm.DB

	field.RelationField
}

func (a goodsActivityBelongsToGoodsInfo) Where(conds ...field.Expr) *goodsActivityBelongsToGoodsInfo {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a goodsActivityBelongsToGoodsInfo) WithContext(ctx context.Context) *goodsActivityBelongsToGoodsInfo {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a goodsActivityBelongsToGoodsInfo) Session(session *gorm.Session) *goodsActivityBelongsToGoodsInfo {
	a.db = a.db.Session(session)
	return &a
}

func (a goodsActivityBelongsToGoodsInfo) Model(m *model.GoodsActivity) *goodsActivityBelongsToGoodsInfoTx {
	return &goodsActivityBelongsToGoodsInfoTx{a.db.Model(m).Association(a.Name())}
}

func (a goodsActivityBelongsToGoodsInfo) Unscoped() *goodsActivityBelongsToGoodsInfo {
	a.db = a.db.Unscoped()
	return &a
}

type goodsActivityBelongsToGoodsInfoTx struct{ tx *gorm.Association }

func (a goodsActivityBelongsToGoodsInfoTx) Find() (result *model.Goods, err error) {
	return result, a.tx.Find(&result)
}

func (a goodsActivityBelongsToGoodsInfoTx) Append(values ...*model.Goods) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a goodsActivityBelongsToGoodsInfoTx) Replace(values ...*model.Goods) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a goodsActivityBelongsToGoodsInfoTx) Delete(values ...*model.Goods) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a goodsActivityBelongsToGoodsInfoTx) Clear() error {
	return a.tx.Clear()
}

func (a goodsActivityBelongsToGoodsInfoTx) Count() int64 {
	return a.tx.Count()
}

func (a goodsActivityBelongsToGoodsInfoTx) Unscoped() *goodsActivityBelongsToGoodsInfoTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type goodsActivityDo struct{ gen.DO }

type IGoodsActivityDo interface {
	gen.SubQuery
	Debug() IGoodsActivityDo
	WithContext(ctx context.Context) IGoodsActivityDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IGoodsActivityDo
	WriteDB() IGoodsActivityDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IGoodsActivityDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IGoodsActivityDo
	Not(conds ...gen.Condition) IGoodsActivityDo
	Or(conds ...gen.Condition) IGoodsActivityDo
	Select(conds ...field.Expr) IGoodsActivityDo
	Where(conds ...gen.Condition) IGoodsActivityDo
	Order(conds ...field.Expr) IGoodsActivityDo
	Distinct(cols ...field.Expr) IGoodsActivityDo
	Omit(cols ...field.Expr) IGoodsActivityDo
	Join(table schema.Tabler, on ...field.Expr) IGoodsActivityDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IGoodsActivityDo
	RightJoin(table schema.Tabler, on ...field.Expr) IGoodsActivityDo
	Group(cols ...field.Expr) IGoodsActivityDo
	Having(conds ...gen.Condition) IGoodsActivityDo
	Limit(limit int) IGoodsActivityDo
	Offset(offset int) IGoodsActivityDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IGoodsActivityDo
	Unscoped() IGoodsActivityDo
	Create(values ...*model.GoodsActivity) error
	CreateInBatches(values []*model.GoodsActivity, batchSize int) error
	Save(values ...*model.GoodsActivity) error
	First() (*model.GoodsActivity, error)
	Take() (*model.GoodsActivity, error)
	Last() (*model.GoodsActivity, error)
	Find() ([]*model.GoodsActivity, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.GoodsActivity, err error)
	FindInBatches(result *[]*model.GoodsActivity, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.GoodsActivity) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IGoodsActivityDo
	Assign(attrs ...field.AssignExpr) IGoodsActivityDo
	Joins(fields ...field.RelationField) IGoodsActivityDo
	Preload(fields ...field.RelationField) IGoodsActivityDo
	FirstOrInit() (*model.GoodsActivity, error)
	FirstOrCreate() (*model.GoodsActivity, error)
	FindByPage(offset int, limit int) (result []*model.GoodsActivity, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IGoodsActivityDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (g goodsActivityDo) Debug() IGoodsActivityDo {
	return g.withDO(g.DO.Debug())
}

func (g goodsActivityDo) WithContext(ctx context.Context) IGoodsActivityDo {
	return g.withDO(g.DO.WithContext(ctx))
}

func (g goodsActivityDo) ReadDB() IGoodsActivityDo {
	return g.Clauses(dbresolver.Read)
}

func (g goodsActivityDo) WriteDB() IGoodsActivityDo {
	return g.Clauses(dbresolver.Write)
}

func (g goodsActivityDo) Session(config *gorm.Session) IGoodsActivityDo {
	return g.withDO(g.DO.Session(config))
}

func (g goodsActivityDo) Clauses(conds ...clause.Expression) IGoodsActivityDo {
	return g.withDO(g.DO.Clauses(conds...))
}

func (g goodsActivityDo) Returning(value interface{}, columns ...string) IGoodsActivityDo {
	return g.withDO(g.DO.Returning(value, columns...))
}

func (g goodsActivityDo) Not(conds ...gen.Condition) IGoodsActivityDo {
	return g.withDO(g.DO.Not(conds...))
}

func (g goodsActivityDo) Or(conds ...gen.Condition) IGoodsActivityDo {
	return g.withDO(g.DO.Or(conds...))
}

func (g goodsActivityDo) Select(conds ...field.Expr) IGoodsActivityDo {
	return g.withDO(g.DO.Select(conds...))
}

func (g goodsActivityDo) Where(conds ...gen.Condition) IGoodsActivityDo {
	return g.withDO(g.DO.Where(conds...))
}

func (g goodsActivityDo) Order(conds ...field.Expr) IGoodsActivityDo {
	return g.withDO(g.DO.Order(conds...))
}

func (g goodsActivityDo) Distinct(cols ...field.Expr) IGoodsActivityDo {
	return g.withDO(g.DO.Distinct(cols...))
}

func (g goodsActivityDo) Omit(cols ...field.Expr) IGoodsActivityDo {
	return g.withDO(g.DO.Omit(cols...))
}

func (g goodsActivityDo) Join(table schema.Tabler, on ...field.Expr) IGoodsActivityDo {
	return g.withDO(g.DO.Join(table, on...))
}

func (g goodsActivityDo) LeftJoin(table schema.Tabler, on ...field.Expr) IGoodsActivityDo {
	return g.withDO(g.DO.LeftJoin(table, on...))
}

func (g goodsActivityDo) RightJoin(table schema.Tabler, on ...field.Expr) IGoodsActivityDo {
	return g.withDO(g.DO.RightJoin(table, on...))
}

func (g goodsActivityDo) Group(cols ...field.Expr) IGoodsActivityDo {
	return g.withDO(g.DO.Group(cols...))
}

func (g goodsActivityDo) Having(conds ...gen.Condition) IGoodsActivityDo {
	return g.withDO(g.DO.Having(conds...))
}

func (g goodsActivityDo) Limit(limit int) IGoodsActivityDo {
	return g.withDO(g.DO.Limit(limit))
}

func (g goodsActivityDo) Offset(offset int) IGoodsActivityDo {
	return g.withDO(g.DO.Offset(offset))
}

func (g goodsActivityDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IGoodsActivityDo {
	return g.withDO(g.DO.Scopes(funcs...))
}

func (g goodsActivityDo) Unscoped() IGoodsActivityDo {
	return g.withDO(g.DO.Unscoped())
}

func (g goodsActivityDo) Create(values ...*model.GoodsActivity) error {
	if len(values) == 0 {
		return nil
	}
	return g.DO.Create(values)
}

func (g goodsActivityDo) CreateInBatches(values []*model.GoodsActivity, batchSize int) error {
	return g.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (g goodsActivityDo) Save(values ...*model.GoodsActivity) error {
	if len(values) == 0 {
		return nil
	}
	return g.DO.Save(values)
}

func (g goodsActivityDo) First() (*model.GoodsActivity, error) {
	if result, err := g.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.GoodsActivity), nil
	}
}

func (g goodsActivityDo) Take() (*model.GoodsActivity, error) {
	if result, err := g.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.GoodsActivity), nil
	}
}

func (g goodsActivityDo) Last() (*model.GoodsActivity, error) {
	if result, err := g.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.GoodsActivity), nil
	}
}

func (g goodsActivityDo) Find() ([]*model.GoodsActivity, error) {
	result, err := g.DO.Find()
	return result.([]*model.GoodsActivity), err
}

func (g goodsActivityDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.GoodsActivity, err error) {
	buf := make([]*model.GoodsActivity, 0, batchSize)
	err = g.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (g goodsActivityDo) FindInBatches(result *[]*model.GoodsActivity, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return g.DO.FindInBatches(result, batchSize, fc)
}

func (g goodsActivityDo) Attrs(attrs ...field.AssignExpr) IGoodsActivityDo {
	return g.withDO(g.DO.Attrs(attrs...))
}

func (g goodsActivityDo) Assign(attrs ...field.AssignExpr) IGoodsActivityDo {
	return g.withDO(g.DO.Assign(attrs...))
}

func (g goodsActivityDo) Joins(fields ...field.RelationField) IGoodsActivityDo {
	for _, _f := range fields {
		g = *g.withDO(g.DO.Joins(_f))
	}
	return &g
}

func (g goodsActivityDo) Preload(fields ...field.RelationField) IGoodsActivityDo {
	for _, _f := range fields {
		g = *g.withDO(g.DO.Preload(_f))
	}
	return &g
}

func (g goodsActivityDo) FirstOrInit() (*model.GoodsActivity, error) {
	if result, err := g.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.GoodsActivity), nil
	}
}

func (g goodsActivityDo) FirstOrCreate() (*model.GoodsActivity, error) {
	if result, err := g.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.GoodsActivity), nil
	}
}

func (g goodsActivityDo) FindByPage(offset int, limit int) (result []*model.GoodsActivity, count int64, err error) {
	result, err = g.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = g.Offset(-1).Limit(-1).Count()
	return
}

func (g goodsActivityDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = g.Count()
	if err != nil {
		return
	}

	err = g.Offset(offset).Limit(limit).Scan(result)
	return
}

func (g goodsActivityDo) Scan(result interface{}) (err error) {
	return g.DO.Scan(result)
}

func (g goodsActivityDo) Delete(models ...*model.GoodsActivity) (result gen.ResultInfo, err error) {
	return g.DO.Delete(models)
}

func (g *goodsActivityDo) withDO(do gen.Dao) *goodsActivityDo {
	g.DO = *do.(*gen.DO)
	return g
}
