// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"aibuddy/internal/model"
)

func newUserAgent(db *gorm.DB, opts ...gen.DOOption) userAgent {
	_userAgent := userAgent{}

	_userAgent.userAgentDo.UseDB(db, opts...)
	_userAgent.userAgentDo.UseModel(&model.UserAgent{})

	tableName := _userAgent.userAgentDo.TableName()
	_userAgent.ALL = field.NewAsterisk(tableName)
	_userAgent.ID = field.NewInt(tableName, "id")
	_userAgent.DeviceID = field.NewString(tableName, "device_id")
	_userAgent.AgentName = field.NewString(tableName, "agent_name")
	_userAgent.ConversationAnalysis = field.NewField(tableName, "conversation_analysis")
	_userAgent.EmotionAnalysis = field.NewField(tableName, "emotion_analysis")
	_userAgent.CreatedAt = field.NewTime(tableName, "created_at")
	_userAgent.UpdatedAt = field.NewTime(tableName, "updated_at")

	_userAgent.fillFieldMap()

	return _userAgent
}

type userAgent struct {
	userAgentDo

	ALL                  field.Asterisk
	ID                   field.Int
	DeviceID             field.String // 设备ID
	AgentName            field.String // 角色名称
	ConversationAnalysis field.Field  // 对话分析
	EmotionAnalysis      field.Field  // 情绪分析
	CreatedAt            field.Time   // 创建时间
	UpdatedAt            field.Time   // 更新时间

	fieldMap map[string]field.Expr
}

func (u userAgent) Table(newTableName string) *userAgent {
	u.userAgentDo.UseTable(newTableName)
	return u.updateTableName(newTableName)
}

func (u userAgent) As(alias string) *userAgent {
	u.userAgentDo.DO = *(u.userAgentDo.As(alias).(*gen.DO))
	return u.updateTableName(alias)
}

func (u *userAgent) updateTableName(table string) *userAgent {
	u.ALL = field.NewAsterisk(table)
	u.ID = field.NewInt(table, "id")
	u.DeviceID = field.NewString(table, "device_id")
	u.AgentName = field.NewString(table, "agent_name")
	u.ConversationAnalysis = field.NewField(table, "conversation_analysis")
	u.EmotionAnalysis = field.NewField(table, "emotion_analysis")
	u.CreatedAt = field.NewTime(table, "created_at")
	u.UpdatedAt = field.NewTime(table, "updated_at")

	u.fillFieldMap()

	return u
}

func (u *userAgent) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := u.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (u *userAgent) fillFieldMap() {
	u.fieldMap = make(map[string]field.Expr, 7)
	u.fieldMap["id"] = u.ID
	u.fieldMap["device_id"] = u.DeviceID
	u.fieldMap["agent_name"] = u.AgentName
	u.fieldMap["conversation_analysis"] = u.ConversationAnalysis
	u.fieldMap["emotion_analysis"] = u.EmotionAnalysis
	u.fieldMap["created_at"] = u.CreatedAt
	u.fieldMap["updated_at"] = u.UpdatedAt
}

func (u userAgent) clone(db *gorm.DB) userAgent {
	u.userAgentDo.ReplaceConnPool(db.Statement.ConnPool)
	return u
}

func (u userAgent) replaceDB(db *gorm.DB) userAgent {
	u.userAgentDo.ReplaceDB(db)
	return u
}

type userAgentDo struct{ gen.DO }

type IUserAgentDo interface {
	gen.SubQuery
	Debug() IUserAgentDo
	WithContext(ctx context.Context) IUserAgentDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IUserAgentDo
	WriteDB() IUserAgentDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IUserAgentDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IUserAgentDo
	Not(conds ...gen.Condition) IUserAgentDo
	Or(conds ...gen.Condition) IUserAgentDo
	Select(conds ...field.Expr) IUserAgentDo
	Where(conds ...gen.Condition) IUserAgentDo
	Order(conds ...field.Expr) IUserAgentDo
	Distinct(cols ...field.Expr) IUserAgentDo
	Omit(cols ...field.Expr) IUserAgentDo
	Join(table schema.Tabler, on ...field.Expr) IUserAgentDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IUserAgentDo
	RightJoin(table schema.Tabler, on ...field.Expr) IUserAgentDo
	Group(cols ...field.Expr) IUserAgentDo
	Having(conds ...gen.Condition) IUserAgentDo
	Limit(limit int) IUserAgentDo
	Offset(offset int) IUserAgentDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IUserAgentDo
	Unscoped() IUserAgentDo
	Create(values ...*model.UserAgent) error
	CreateInBatches(values []*model.UserAgent, batchSize int) error
	Save(values ...*model.UserAgent) error
	First() (*model.UserAgent, error)
	Take() (*model.UserAgent, error)
	Last() (*model.UserAgent, error)
	Find() ([]*model.UserAgent, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.UserAgent, err error)
	FindInBatches(result *[]*model.UserAgent, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.UserAgent) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IUserAgentDo
	Assign(attrs ...field.AssignExpr) IUserAgentDo
	Joins(fields ...field.RelationField) IUserAgentDo
	Preload(fields ...field.RelationField) IUserAgentDo
	FirstOrInit() (*model.UserAgent, error)
	FirstOrCreate() (*model.UserAgent, error)
	FindByPage(offset int, limit int) (result []*model.UserAgent, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IUserAgentDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (u userAgentDo) Debug() IUserAgentDo {
	return u.withDO(u.DO.Debug())
}

func (u userAgentDo) WithContext(ctx context.Context) IUserAgentDo {
	return u.withDO(u.DO.WithContext(ctx))
}

func (u userAgentDo) ReadDB() IUserAgentDo {
	return u.Clauses(dbresolver.Read)
}

func (u userAgentDo) WriteDB() IUserAgentDo {
	return u.Clauses(dbresolver.Write)
}

func (u userAgentDo) Session(config *gorm.Session) IUserAgentDo {
	return u.withDO(u.DO.Session(config))
}

func (u userAgentDo) Clauses(conds ...clause.Expression) IUserAgentDo {
	return u.withDO(u.DO.Clauses(conds...))
}

func (u userAgentDo) Returning(value interface{}, columns ...string) IUserAgentDo {
	return u.withDO(u.DO.Returning(value, columns...))
}

func (u userAgentDo) Not(conds ...gen.Condition) IUserAgentDo {
	return u.withDO(u.DO.Not(conds...))
}

func (u userAgentDo) Or(conds ...gen.Condition) IUserAgentDo {
	return u.withDO(u.DO.Or(conds...))
}

func (u userAgentDo) Select(conds ...field.Expr) IUserAgentDo {
	return u.withDO(u.DO.Select(conds...))
}

func (u userAgentDo) Where(conds ...gen.Condition) IUserAgentDo {
	return u.withDO(u.DO.Where(conds...))
}

func (u userAgentDo) Order(conds ...field.Expr) IUserAgentDo {
	return u.withDO(u.DO.Order(conds...))
}

func (u userAgentDo) Distinct(cols ...field.Expr) IUserAgentDo {
	return u.withDO(u.DO.Distinct(cols...))
}

func (u userAgentDo) Omit(cols ...field.Expr) IUserAgentDo {
	return u.withDO(u.DO.Omit(cols...))
}

func (u userAgentDo) Join(table schema.Tabler, on ...field.Expr) IUserAgentDo {
	return u.withDO(u.DO.Join(table, on...))
}

func (u userAgentDo) LeftJoin(table schema.Tabler, on ...field.Expr) IUserAgentDo {
	return u.withDO(u.DO.LeftJoin(table, on...))
}

func (u userAgentDo) RightJoin(table schema.Tabler, on ...field.Expr) IUserAgentDo {
	return u.withDO(u.DO.RightJoin(table, on...))
}

func (u userAgentDo) Group(cols ...field.Expr) IUserAgentDo {
	return u.withDO(u.DO.Group(cols...))
}

func (u userAgentDo) Having(conds ...gen.Condition) IUserAgentDo {
	return u.withDO(u.DO.Having(conds...))
}

func (u userAgentDo) Limit(limit int) IUserAgentDo {
	return u.withDO(u.DO.Limit(limit))
}

func (u userAgentDo) Offset(offset int) IUserAgentDo {
	return u.withDO(u.DO.Offset(offset))
}

func (u userAgentDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IUserAgentDo {
	return u.withDO(u.DO.Scopes(funcs...))
}

func (u userAgentDo) Unscoped() IUserAgentDo {
	return u.withDO(u.DO.Unscoped())
}

func (u userAgentDo) Create(values ...*model.UserAgent) error {
	if len(values) == 0 {
		return nil
	}
	return u.DO.Create(values)
}

func (u userAgentDo) CreateInBatches(values []*model.UserAgent, batchSize int) error {
	return u.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (u userAgentDo) Save(values ...*model.UserAgent) error {
	if len(values) == 0 {
		return nil
	}
	return u.DO.Save(values)
}

func (u userAgentDo) First() (*model.UserAgent, error) {
	if result, err := u.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.UserAgent), nil
	}
}

func (u userAgentDo) Take() (*model.UserAgent, error) {
	if result, err := u.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.UserAgent), nil
	}
}

func (u userAgentDo) Last() (*model.UserAgent, error) {
	if result, err := u.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.UserAgent), nil
	}
}

func (u userAgentDo) Find() ([]*model.UserAgent, error) {
	result, err := u.DO.Find()
	return result.([]*model.UserAgent), err
}

func (u userAgentDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.UserAgent, err error) {
	buf := make([]*model.UserAgent, 0, batchSize)
	err = u.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (u userAgentDo) FindInBatches(result *[]*model.UserAgent, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return u.DO.FindInBatches(result, batchSize, fc)
}

func (u userAgentDo) Attrs(attrs ...field.AssignExpr) IUserAgentDo {
	return u.withDO(u.DO.Attrs(attrs...))
}

func (u userAgentDo) Assign(attrs ...field.AssignExpr) IUserAgentDo {
	return u.withDO(u.DO.Assign(attrs...))
}

func (u userAgentDo) Joins(fields ...field.RelationField) IUserAgentDo {
	for _, _f := range fields {
		u = *u.withDO(u.DO.Joins(_f))
	}
	return &u
}

func (u userAgentDo) Preload(fields ...field.RelationField) IUserAgentDo {
	for _, _f := range fields {
		u = *u.withDO(u.DO.Preload(_f))
	}
	return &u
}

func (u userAgentDo) FirstOrInit() (*model.UserAgent, error) {
	if result, err := u.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.UserAgent), nil
	}
}

func (u userAgentDo) FirstOrCreate() (*model.UserAgent, error) {
	if result, err := u.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.UserAgent), nil
	}
}

func (u userAgentDo) FindByPage(offset int, limit int) (result []*model.UserAgent, count int64, err error) {
	result, err = u.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = u.Offset(-1).Limit(-1).Count()
	return
}

func (u userAgentDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = u.Count()
	if err != nil {
		return
	}

	err = u.Offset(offset).Limit(limit).Scan(result)
	return
}

func (u userAgentDo) Scan(result interface{}) (err error) {
	return u.DO.Scan(result)
}

func (u userAgentDo) Delete(models ...*model.UserAgent) (result gen.ResultInfo, err error) {
	return u.DO.Delete(models)
}

func (u *userAgentDo) withDO(do gen.Dao) *userAgentDo {
	u.DO = *do.(*gen.DO)
	return u
}
