// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"aibuddy/internal/model"
)

func newPomodoroClock(db *gorm.DB, opts ...gen.DOOption) pomodoroClock {
	_pomodoroClock := pomodoroClock{}

	_pomodoroClock.pomodoroClockDo.UseDB(db, opts...)
	_pomodoroClock.pomodoroClockDo.UseModel(&model.PomodoroClock{})

	tableName := _pomodoroClock.pomodoroClockDo.TableName()
	_pomodoroClock.ALL = field.NewAsterisk(tableName)
	_pomodoroClock.ID = field.NewInt(tableName, "id")
	_pomodoroClock.DeviceID = field.NewString(tableName, "device_id")
	_pomodoroClock.TotalDuration = field.NewInt(tableName, "total_duration")
	_pomodoroClock.StudyDuration = field.NewInt(tableName, "study_duration")
	_pomodoroClock.DistractionDuration = field.NewInt(tableName, "distraction_duration")
	_pomodoroClock.CreatedAt = field.NewTime(tableName, "created_at")
	_pomodoroClock.UpdatedAt = field.NewTime(tableName, "updated_at")

	_pomodoroClock.fillFieldMap()

	return _pomodoroClock
}

type pomodoroClock struct {
	pomodoroClockDo

	ALL                 field.Asterisk
	ID                  field.Int    // ID
	DeviceID            field.String // 设备ID
	TotalDuration       field.Int    // 总时长
	StudyDuration       field.Int    // 学习时长
	DistractionDuration field.Int    // 分心时长
	CreatedAt           field.Time   // 创建时间
	UpdatedAt           field.Time   // 更新时间

	fieldMap map[string]field.Expr
}

func (p pomodoroClock) Table(newTableName string) *pomodoroClock {
	p.pomodoroClockDo.UseTable(newTableName)
	return p.updateTableName(newTableName)
}

func (p pomodoroClock) As(alias string) *pomodoroClock {
	p.pomodoroClockDo.DO = *(p.pomodoroClockDo.As(alias).(*gen.DO))
	return p.updateTableName(alias)
}

func (p *pomodoroClock) updateTableName(table string) *pomodoroClock {
	p.ALL = field.NewAsterisk(table)
	p.ID = field.NewInt(table, "id")
	p.DeviceID = field.NewString(table, "device_id")
	p.TotalDuration = field.NewInt(table, "total_duration")
	p.StudyDuration = field.NewInt(table, "study_duration")
	p.DistractionDuration = field.NewInt(table, "distraction_duration")
	p.CreatedAt = field.NewTime(table, "created_at")
	p.UpdatedAt = field.NewTime(table, "updated_at")

	p.fillFieldMap()

	return p
}

func (p *pomodoroClock) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := p.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (p *pomodoroClock) fillFieldMap() {
	p.fieldMap = make(map[string]field.Expr, 7)
	p.fieldMap["id"] = p.ID
	p.fieldMap["device_id"] = p.DeviceID
	p.fieldMap["total_duration"] = p.TotalDuration
	p.fieldMap["study_duration"] = p.StudyDuration
	p.fieldMap["distraction_duration"] = p.DistractionDuration
	p.fieldMap["created_at"] = p.CreatedAt
	p.fieldMap["updated_at"] = p.UpdatedAt
}

func (p pomodoroClock) clone(db *gorm.DB) pomodoroClock {
	p.pomodoroClockDo.ReplaceConnPool(db.Statement.ConnPool)
	return p
}

func (p pomodoroClock) replaceDB(db *gorm.DB) pomodoroClock {
	p.pomodoroClockDo.ReplaceDB(db)
	return p
}

type pomodoroClockDo struct{ gen.DO }

type IPomodoroClockDo interface {
	gen.SubQuery
	Debug() IPomodoroClockDo
	WithContext(ctx context.Context) IPomodoroClockDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IPomodoroClockDo
	WriteDB() IPomodoroClockDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IPomodoroClockDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IPomodoroClockDo
	Not(conds ...gen.Condition) IPomodoroClockDo
	Or(conds ...gen.Condition) IPomodoroClockDo
	Select(conds ...field.Expr) IPomodoroClockDo
	Where(conds ...gen.Condition) IPomodoroClockDo
	Order(conds ...field.Expr) IPomodoroClockDo
	Distinct(cols ...field.Expr) IPomodoroClockDo
	Omit(cols ...field.Expr) IPomodoroClockDo
	Join(table schema.Tabler, on ...field.Expr) IPomodoroClockDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IPomodoroClockDo
	RightJoin(table schema.Tabler, on ...field.Expr) IPomodoroClockDo
	Group(cols ...field.Expr) IPomodoroClockDo
	Having(conds ...gen.Condition) IPomodoroClockDo
	Limit(limit int) IPomodoroClockDo
	Offset(offset int) IPomodoroClockDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IPomodoroClockDo
	Unscoped() IPomodoroClockDo
	Create(values ...*model.PomodoroClock) error
	CreateInBatches(values []*model.PomodoroClock, batchSize int) error
	Save(values ...*model.PomodoroClock) error
	First() (*model.PomodoroClock, error)
	Take() (*model.PomodoroClock, error)
	Last() (*model.PomodoroClock, error)
	Find() ([]*model.PomodoroClock, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.PomodoroClock, err error)
	FindInBatches(result *[]*model.PomodoroClock, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.PomodoroClock) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IPomodoroClockDo
	Assign(attrs ...field.AssignExpr) IPomodoroClockDo
	Joins(fields ...field.RelationField) IPomodoroClockDo
	Preload(fields ...field.RelationField) IPomodoroClockDo
	FirstOrInit() (*model.PomodoroClock, error)
	FirstOrCreate() (*model.PomodoroClock, error)
	FindByPage(offset int, limit int) (result []*model.PomodoroClock, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IPomodoroClockDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (p pomodoroClockDo) Debug() IPomodoroClockDo {
	return p.withDO(p.DO.Debug())
}

func (p pomodoroClockDo) WithContext(ctx context.Context) IPomodoroClockDo {
	return p.withDO(p.DO.WithContext(ctx))
}

func (p pomodoroClockDo) ReadDB() IPomodoroClockDo {
	return p.Clauses(dbresolver.Read)
}

func (p pomodoroClockDo) WriteDB() IPomodoroClockDo {
	return p.Clauses(dbresolver.Write)
}

func (p pomodoroClockDo) Session(config *gorm.Session) IPomodoroClockDo {
	return p.withDO(p.DO.Session(config))
}

func (p pomodoroClockDo) Clauses(conds ...clause.Expression) IPomodoroClockDo {
	return p.withDO(p.DO.Clauses(conds...))
}

func (p pomodoroClockDo) Returning(value interface{}, columns ...string) IPomodoroClockDo {
	return p.withDO(p.DO.Returning(value, columns...))
}

func (p pomodoroClockDo) Not(conds ...gen.Condition) IPomodoroClockDo {
	return p.withDO(p.DO.Not(conds...))
}

func (p pomodoroClockDo) Or(conds ...gen.Condition) IPomodoroClockDo {
	return p.withDO(p.DO.Or(conds...))
}

func (p pomodoroClockDo) Select(conds ...field.Expr) IPomodoroClockDo {
	return p.withDO(p.DO.Select(conds...))
}

func (p pomodoroClockDo) Where(conds ...gen.Condition) IPomodoroClockDo {
	return p.withDO(p.DO.Where(conds...))
}

func (p pomodoroClockDo) Order(conds ...field.Expr) IPomodoroClockDo {
	return p.withDO(p.DO.Order(conds...))
}

func (p pomodoroClockDo) Distinct(cols ...field.Expr) IPomodoroClockDo {
	return p.withDO(p.DO.Distinct(cols...))
}

func (p pomodoroClockDo) Omit(cols ...field.Expr) IPomodoroClockDo {
	return p.withDO(p.DO.Omit(cols...))
}

func (p pomodoroClockDo) Join(table schema.Tabler, on ...field.Expr) IPomodoroClockDo {
	return p.withDO(p.DO.Join(table, on...))
}

func (p pomodoroClockDo) LeftJoin(table schema.Tabler, on ...field.Expr) IPomodoroClockDo {
	return p.withDO(p.DO.LeftJoin(table, on...))
}

func (p pomodoroClockDo) RightJoin(table schema.Tabler, on ...field.Expr) IPomodoroClockDo {
	return p.withDO(p.DO.RightJoin(table, on...))
}

func (p pomodoroClockDo) Group(cols ...field.Expr) IPomodoroClockDo {
	return p.withDO(p.DO.Group(cols...))
}

func (p pomodoroClockDo) Having(conds ...gen.Condition) IPomodoroClockDo {
	return p.withDO(p.DO.Having(conds...))
}

func (p pomodoroClockDo) Limit(limit int) IPomodoroClockDo {
	return p.withDO(p.DO.Limit(limit))
}

func (p pomodoroClockDo) Offset(offset int) IPomodoroClockDo {
	return p.withDO(p.DO.Offset(offset))
}

func (p pomodoroClockDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IPomodoroClockDo {
	return p.withDO(p.DO.Scopes(funcs...))
}

func (p pomodoroClockDo) Unscoped() IPomodoroClockDo {
	return p.withDO(p.DO.Unscoped())
}

func (p pomodoroClockDo) Create(values ...*model.PomodoroClock) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Create(values)
}

func (p pomodoroClockDo) CreateInBatches(values []*model.PomodoroClock, batchSize int) error {
	return p.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (p pomodoroClockDo) Save(values ...*model.PomodoroClock) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Save(values)
}

func (p pomodoroClockDo) First() (*model.PomodoroClock, error) {
	if result, err := p.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.PomodoroClock), nil
	}
}

func (p pomodoroClockDo) Take() (*model.PomodoroClock, error) {
	if result, err := p.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.PomodoroClock), nil
	}
}

func (p pomodoroClockDo) Last() (*model.PomodoroClock, error) {
	if result, err := p.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.PomodoroClock), nil
	}
}

func (p pomodoroClockDo) Find() ([]*model.PomodoroClock, error) {
	result, err := p.DO.Find()
	return result.([]*model.PomodoroClock), err
}

func (p pomodoroClockDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.PomodoroClock, err error) {
	buf := make([]*model.PomodoroClock, 0, batchSize)
	err = p.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (p pomodoroClockDo) FindInBatches(result *[]*model.PomodoroClock, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return p.DO.FindInBatches(result, batchSize, fc)
}

func (p pomodoroClockDo) Attrs(attrs ...field.AssignExpr) IPomodoroClockDo {
	return p.withDO(p.DO.Attrs(attrs...))
}

func (p pomodoroClockDo) Assign(attrs ...field.AssignExpr) IPomodoroClockDo {
	return p.withDO(p.DO.Assign(attrs...))
}

func (p pomodoroClockDo) Joins(fields ...field.RelationField) IPomodoroClockDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Joins(_f))
	}
	return &p
}

func (p pomodoroClockDo) Preload(fields ...field.RelationField) IPomodoroClockDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Preload(_f))
	}
	return &p
}

func (p pomodoroClockDo) FirstOrInit() (*model.PomodoroClock, error) {
	if result, err := p.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.PomodoroClock), nil
	}
}

func (p pomodoroClockDo) FirstOrCreate() (*model.PomodoroClock, error) {
	if result, err := p.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.PomodoroClock), nil
	}
}

func (p pomodoroClockDo) FindByPage(offset int, limit int) (result []*model.PomodoroClock, count int64, err error) {
	result, err = p.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = p.Offset(-1).Limit(-1).Count()
	return
}

func (p pomodoroClockDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = p.Count()
	if err != nil {
		return
	}

	err = p.Offset(offset).Limit(limit).Scan(result)
	return
}

func (p pomodoroClockDo) Scan(result interface{}) (err error) {
	return p.DO.Scan(result)
}

func (p pomodoroClockDo) Delete(models ...*model.PomodoroClock) (result gen.ResultInfo, err error) {
	return p.DO.Delete(models)
}

func (p *pomodoroClockDo) withDO(do gen.Dao) *pomodoroClockDo {
	p.DO = *do.(*gen.DO)
	return p
}
