// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"aibuddy/internal/model"
)

func newDeviceOta(db *gorm.DB, opts ...gen.DOOption) deviceOta {
	_deviceOta := deviceOta{}

	_deviceOta.deviceOtaDo.UseDB(db, opts...)
	_deviceOta.deviceOtaDo.UseModel(&model.DeviceOta{})

	tableName := _deviceOta.deviceOtaDo.TableName()
	_deviceOta.ALL = field.NewAsterisk(tableName)
	_deviceOta.ID = field.NewInt(tableName, "id")
	_deviceOta.DeviceID = field.NewString(tableName, "device_id")
	_deviceOta.Version = field.NewString(tableName, "version")
	_deviceOta.OtaURL = field.NewString(tableName, "ota_url")
	_deviceOta.ModelURL = field.NewString(tableName, "model_url")
	_deviceOta.ResourceURL = field.NewString(tableName, "resource_url")
	_deviceOta.ForceUpdate = field.NewBool(tableName, "force_update")
	_deviceOta.CreatedAt = field.NewTime(tableName, "created_at")
	_deviceOta.UpdatedAt = field.NewTime(tableName, "updated_at")
	_deviceOta.Device = deviceOtaHasOneDevice{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("Device", "model.Device"),
		Agent: struct {
			field.RelationField
		}{
			RelationField: field.NewRelation("Device.Agent", "model.Agent"),
		},
		DeviceInfo: struct {
			field.RelationField
		}{
			RelationField: field.NewRelation("Device.DeviceInfo", "model.DeviceInfo"),
		},
	}

	_deviceOta.fillFieldMap()

	return _deviceOta
}

type deviceOta struct {
	deviceOtaDo

	ALL         field.Asterisk
	ID          field.Int
	DeviceID    field.String
	Version     field.String
	OtaURL      field.String
	ModelURL    field.String
	ResourceURL field.String
	ForceUpdate field.Bool
	CreatedAt   field.Time
	UpdatedAt   field.Time
	Device      deviceOtaHasOneDevice

	fieldMap map[string]field.Expr
}

func (d deviceOta) Table(newTableName string) *deviceOta {
	d.deviceOtaDo.UseTable(newTableName)
	return d.updateTableName(newTableName)
}

func (d deviceOta) As(alias string) *deviceOta {
	d.deviceOtaDo.DO = *(d.deviceOtaDo.As(alias).(*gen.DO))
	return d.updateTableName(alias)
}

func (d *deviceOta) updateTableName(table string) *deviceOta {
	d.ALL = field.NewAsterisk(table)
	d.ID = field.NewInt(table, "id")
	d.DeviceID = field.NewString(table, "device_id")
	d.Version = field.NewString(table, "version")
	d.OtaURL = field.NewString(table, "ota_url")
	d.ModelURL = field.NewString(table, "model_url")
	d.ResourceURL = field.NewString(table, "resource_url")
	d.ForceUpdate = field.NewBool(table, "force_update")
	d.CreatedAt = field.NewTime(table, "created_at")
	d.UpdatedAt = field.NewTime(table, "updated_at")

	d.fillFieldMap()

	return d
}

func (d *deviceOta) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := d.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (d *deviceOta) fillFieldMap() {
	d.fieldMap = make(map[string]field.Expr, 10)
	d.fieldMap["id"] = d.ID
	d.fieldMap["device_id"] = d.DeviceID
	d.fieldMap["version"] = d.Version
	d.fieldMap["ota_url"] = d.OtaURL
	d.fieldMap["model_url"] = d.ModelURL
	d.fieldMap["resource_url"] = d.ResourceURL
	d.fieldMap["force_update"] = d.ForceUpdate
	d.fieldMap["created_at"] = d.CreatedAt
	d.fieldMap["updated_at"] = d.UpdatedAt

}

func (d deviceOta) clone(db *gorm.DB) deviceOta {
	d.deviceOtaDo.ReplaceConnPool(db.Statement.ConnPool)
	d.Device.db = db.Session(&gorm.Session{Initialized: true})
	d.Device.db.Statement.ConnPool = db.Statement.ConnPool
	return d
}

func (d deviceOta) replaceDB(db *gorm.DB) deviceOta {
	d.deviceOtaDo.ReplaceDB(db)
	d.Device.db = db.Session(&gorm.Session{})
	return d
}

type deviceOtaHasOneDevice struct {
	db *gorm.DB

	field.RelationField

	Agent struct {
		field.RelationField
	}
	DeviceInfo struct {
		field.RelationField
	}
}

func (a deviceOtaHasOneDevice) Where(conds ...field.Expr) *deviceOtaHasOneDevice {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a deviceOtaHasOneDevice) WithContext(ctx context.Context) *deviceOtaHasOneDevice {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a deviceOtaHasOneDevice) Session(session *gorm.Session) *deviceOtaHasOneDevice {
	a.db = a.db.Session(session)
	return &a
}

func (a deviceOtaHasOneDevice) Model(m *model.DeviceOta) *deviceOtaHasOneDeviceTx {
	return &deviceOtaHasOneDeviceTx{a.db.Model(m).Association(a.Name())}
}

func (a deviceOtaHasOneDevice) Unscoped() *deviceOtaHasOneDevice {
	a.db = a.db.Unscoped()
	return &a
}

type deviceOtaHasOneDeviceTx struct{ tx *gorm.Association }

func (a deviceOtaHasOneDeviceTx) Find() (result *model.Device, err error) {
	return result, a.tx.Find(&result)
}

func (a deviceOtaHasOneDeviceTx) Append(values ...*model.Device) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a deviceOtaHasOneDeviceTx) Replace(values ...*model.Device) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a deviceOtaHasOneDeviceTx) Delete(values ...*model.Device) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a deviceOtaHasOneDeviceTx) Clear() error {
	return a.tx.Clear()
}

func (a deviceOtaHasOneDeviceTx) Count() int64 {
	return a.tx.Count()
}

func (a deviceOtaHasOneDeviceTx) Unscoped() *deviceOtaHasOneDeviceTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type deviceOtaDo struct{ gen.DO }

type IDeviceOtaDo interface {
	gen.SubQuery
	Debug() IDeviceOtaDo
	WithContext(ctx context.Context) IDeviceOtaDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IDeviceOtaDo
	WriteDB() IDeviceOtaDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IDeviceOtaDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IDeviceOtaDo
	Not(conds ...gen.Condition) IDeviceOtaDo
	Or(conds ...gen.Condition) IDeviceOtaDo
	Select(conds ...field.Expr) IDeviceOtaDo
	Where(conds ...gen.Condition) IDeviceOtaDo
	Order(conds ...field.Expr) IDeviceOtaDo
	Distinct(cols ...field.Expr) IDeviceOtaDo
	Omit(cols ...field.Expr) IDeviceOtaDo
	Join(table schema.Tabler, on ...field.Expr) IDeviceOtaDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IDeviceOtaDo
	RightJoin(table schema.Tabler, on ...field.Expr) IDeviceOtaDo
	Group(cols ...field.Expr) IDeviceOtaDo
	Having(conds ...gen.Condition) IDeviceOtaDo
	Limit(limit int) IDeviceOtaDo
	Offset(offset int) IDeviceOtaDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IDeviceOtaDo
	Unscoped() IDeviceOtaDo
	Create(values ...*model.DeviceOta) error
	CreateInBatches(values []*model.DeviceOta, batchSize int) error
	Save(values ...*model.DeviceOta) error
	First() (*model.DeviceOta, error)
	Take() (*model.DeviceOta, error)
	Last() (*model.DeviceOta, error)
	Find() ([]*model.DeviceOta, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.DeviceOta, err error)
	FindInBatches(result *[]*model.DeviceOta, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.DeviceOta) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IDeviceOtaDo
	Assign(attrs ...field.AssignExpr) IDeviceOtaDo
	Joins(fields ...field.RelationField) IDeviceOtaDo
	Preload(fields ...field.RelationField) IDeviceOtaDo
	FirstOrInit() (*model.DeviceOta, error)
	FirstOrCreate() (*model.DeviceOta, error)
	FindByPage(offset int, limit int) (result []*model.DeviceOta, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IDeviceOtaDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (d deviceOtaDo) Debug() IDeviceOtaDo {
	return d.withDO(d.DO.Debug())
}

func (d deviceOtaDo) WithContext(ctx context.Context) IDeviceOtaDo {
	return d.withDO(d.DO.WithContext(ctx))
}

func (d deviceOtaDo) ReadDB() IDeviceOtaDo {
	return d.Clauses(dbresolver.Read)
}

func (d deviceOtaDo) WriteDB() IDeviceOtaDo {
	return d.Clauses(dbresolver.Write)
}

func (d deviceOtaDo) Session(config *gorm.Session) IDeviceOtaDo {
	return d.withDO(d.DO.Session(config))
}

func (d deviceOtaDo) Clauses(conds ...clause.Expression) IDeviceOtaDo {
	return d.withDO(d.DO.Clauses(conds...))
}

func (d deviceOtaDo) Returning(value interface{}, columns ...string) IDeviceOtaDo {
	return d.withDO(d.DO.Returning(value, columns...))
}

func (d deviceOtaDo) Not(conds ...gen.Condition) IDeviceOtaDo {
	return d.withDO(d.DO.Not(conds...))
}

func (d deviceOtaDo) Or(conds ...gen.Condition) IDeviceOtaDo {
	return d.withDO(d.DO.Or(conds...))
}

func (d deviceOtaDo) Select(conds ...field.Expr) IDeviceOtaDo {
	return d.withDO(d.DO.Select(conds...))
}

func (d deviceOtaDo) Where(conds ...gen.Condition) IDeviceOtaDo {
	return d.withDO(d.DO.Where(conds...))
}

func (d deviceOtaDo) Order(conds ...field.Expr) IDeviceOtaDo {
	return d.withDO(d.DO.Order(conds...))
}

func (d deviceOtaDo) Distinct(cols ...field.Expr) IDeviceOtaDo {
	return d.withDO(d.DO.Distinct(cols...))
}

func (d deviceOtaDo) Omit(cols ...field.Expr) IDeviceOtaDo {
	return d.withDO(d.DO.Omit(cols...))
}

func (d deviceOtaDo) Join(table schema.Tabler, on ...field.Expr) IDeviceOtaDo {
	return d.withDO(d.DO.Join(table, on...))
}

func (d deviceOtaDo) LeftJoin(table schema.Tabler, on ...field.Expr) IDeviceOtaDo {
	return d.withDO(d.DO.LeftJoin(table, on...))
}

func (d deviceOtaDo) RightJoin(table schema.Tabler, on ...field.Expr) IDeviceOtaDo {
	return d.withDO(d.DO.RightJoin(table, on...))
}

func (d deviceOtaDo) Group(cols ...field.Expr) IDeviceOtaDo {
	return d.withDO(d.DO.Group(cols...))
}

func (d deviceOtaDo) Having(conds ...gen.Condition) IDeviceOtaDo {
	return d.withDO(d.DO.Having(conds...))
}

func (d deviceOtaDo) Limit(limit int) IDeviceOtaDo {
	return d.withDO(d.DO.Limit(limit))
}

func (d deviceOtaDo) Offset(offset int) IDeviceOtaDo {
	return d.withDO(d.DO.Offset(offset))
}

func (d deviceOtaDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IDeviceOtaDo {
	return d.withDO(d.DO.Scopes(funcs...))
}

func (d deviceOtaDo) Unscoped() IDeviceOtaDo {
	return d.withDO(d.DO.Unscoped())
}

func (d deviceOtaDo) Create(values ...*model.DeviceOta) error {
	if len(values) == 0 {
		return nil
	}
	return d.DO.Create(values)
}

func (d deviceOtaDo) CreateInBatches(values []*model.DeviceOta, batchSize int) error {
	return d.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (d deviceOtaDo) Save(values ...*model.DeviceOta) error {
	if len(values) == 0 {
		return nil
	}
	return d.DO.Save(values)
}

func (d deviceOtaDo) First() (*model.DeviceOta, error) {
	if result, err := d.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.DeviceOta), nil
	}
}

func (d deviceOtaDo) Take() (*model.DeviceOta, error) {
	if result, err := d.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.DeviceOta), nil
	}
}

func (d deviceOtaDo) Last() (*model.DeviceOta, error) {
	if result, err := d.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.DeviceOta), nil
	}
}

func (d deviceOtaDo) Find() ([]*model.DeviceOta, error) {
	result, err := d.DO.Find()
	return result.([]*model.DeviceOta), err
}

func (d deviceOtaDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.DeviceOta, err error) {
	buf := make([]*model.DeviceOta, 0, batchSize)
	err = d.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (d deviceOtaDo) FindInBatches(result *[]*model.DeviceOta, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return d.DO.FindInBatches(result, batchSize, fc)
}

func (d deviceOtaDo) Attrs(attrs ...field.AssignExpr) IDeviceOtaDo {
	return d.withDO(d.DO.Attrs(attrs...))
}

func (d deviceOtaDo) Assign(attrs ...field.AssignExpr) IDeviceOtaDo {
	return d.withDO(d.DO.Assign(attrs...))
}

func (d deviceOtaDo) Joins(fields ...field.RelationField) IDeviceOtaDo {
	for _, _f := range fields {
		d = *d.withDO(d.DO.Joins(_f))
	}
	return &d
}

func (d deviceOtaDo) Preload(fields ...field.RelationField) IDeviceOtaDo {
	for _, _f := range fields {
		d = *d.withDO(d.DO.Preload(_f))
	}
	return &d
}

func (d deviceOtaDo) FirstOrInit() (*model.DeviceOta, error) {
	if result, err := d.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.DeviceOta), nil
	}
}

func (d deviceOtaDo) FirstOrCreate() (*model.DeviceOta, error) {
	if result, err := d.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.DeviceOta), nil
	}
}

func (d deviceOtaDo) FindByPage(offset int, limit int) (result []*model.DeviceOta, count int64, err error) {
	result, err = d.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = d.Offset(-1).Limit(-1).Count()
	return
}

func (d deviceOtaDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = d.Count()
	if err != nil {
		return
	}

	err = d.Offset(offset).Limit(limit).Scan(result)
	return
}

func (d deviceOtaDo) Scan(result interface{}) (err error) {
	return d.DO.Scan(result)
}

func (d deviceOtaDo) Delete(models ...*model.DeviceOta) (result gen.ResultInfo, err error) {
	return d.DO.Delete(models)
}

func (d *deviceOtaDo) withDO(do gen.Dao) *deviceOtaDo {
	d.DO = *do.(*gen.DO)
	return d
}
