// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"aibuddy/internal/model"
)

func newDeviceActivate(db *gorm.DB, opts ...gen.DOOption) deviceActivate {
	_deviceActivate := deviceActivate{}

	_deviceActivate.deviceActivateDo.UseDB(db, opts...)
	_deviceActivate.deviceActivateDo.UseModel(&model.DeviceActivate{})

	tableName := _deviceActivate.deviceActivateDo.TableName()
	_deviceActivate.ALL = field.NewAsterisk(tableName)
	_deviceActivate.ID = field.NewInt64(tableName, "id")
	_deviceActivate.DeviceID = field.NewString(tableName, "device_id")
	_deviceActivate.ActivateTime = field.NewField(tableName, "activate_time")
	_deviceActivate.CreatedAt = field.NewField(tableName, "created_at")
	_deviceActivate.UpdatedAt = field.NewField(tableName, "updated_at")

	_deviceActivate.fillFieldMap()

	return _deviceActivate
}

type deviceActivate struct {
	deviceActivateDo

	ALL          field.Asterisk
	ID           field.Int64
	DeviceID     field.String // 设备ID
	ActivateTime field.Field  // 激活时间
	CreatedAt    field.Field  // 创建时间
	UpdatedAt    field.Field  // 更新时间

	fieldMap map[string]field.Expr
}

func (d deviceActivate) Table(newTableName string) *deviceActivate {
	d.deviceActivateDo.UseTable(newTableName)
	return d.updateTableName(newTableName)
}

func (d deviceActivate) As(alias string) *deviceActivate {
	d.deviceActivateDo.DO = *(d.deviceActivateDo.As(alias).(*gen.DO))
	return d.updateTableName(alias)
}

func (d *deviceActivate) updateTableName(table string) *deviceActivate {
	d.ALL = field.NewAsterisk(table)
	d.ID = field.NewInt64(table, "id")
	d.DeviceID = field.NewString(table, "device_id")
	d.ActivateTime = field.NewField(table, "activate_time")
	d.CreatedAt = field.NewField(table, "created_at")
	d.UpdatedAt = field.NewField(table, "updated_at")

	d.fillFieldMap()

	return d
}

func (d *deviceActivate) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := d.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (d *deviceActivate) fillFieldMap() {
	d.fieldMap = make(map[string]field.Expr, 5)
	d.fieldMap["id"] = d.ID
	d.fieldMap["device_id"] = d.DeviceID
	d.fieldMap["activate_time"] = d.ActivateTime
	d.fieldMap["created_at"] = d.CreatedAt
	d.fieldMap["updated_at"] = d.UpdatedAt
}

func (d deviceActivate) clone(db *gorm.DB) deviceActivate {
	d.deviceActivateDo.ReplaceConnPool(db.Statement.ConnPool)
	return d
}

func (d deviceActivate) replaceDB(db *gorm.DB) deviceActivate {
	d.deviceActivateDo.ReplaceDB(db)
	return d
}

type deviceActivateDo struct{ gen.DO }

type IDeviceActivateDo interface {
	gen.SubQuery
	Debug() IDeviceActivateDo
	WithContext(ctx context.Context) IDeviceActivateDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IDeviceActivateDo
	WriteDB() IDeviceActivateDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IDeviceActivateDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IDeviceActivateDo
	Not(conds ...gen.Condition) IDeviceActivateDo
	Or(conds ...gen.Condition) IDeviceActivateDo
	Select(conds ...field.Expr) IDeviceActivateDo
	Where(conds ...gen.Condition) IDeviceActivateDo
	Order(conds ...field.Expr) IDeviceActivateDo
	Distinct(cols ...field.Expr) IDeviceActivateDo
	Omit(cols ...field.Expr) IDeviceActivateDo
	Join(table schema.Tabler, on ...field.Expr) IDeviceActivateDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IDeviceActivateDo
	RightJoin(table schema.Tabler, on ...field.Expr) IDeviceActivateDo
	Group(cols ...field.Expr) IDeviceActivateDo
	Having(conds ...gen.Condition) IDeviceActivateDo
	Limit(limit int) IDeviceActivateDo
	Offset(offset int) IDeviceActivateDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IDeviceActivateDo
	Unscoped() IDeviceActivateDo
	Create(values ...*model.DeviceActivate) error
	CreateInBatches(values []*model.DeviceActivate, batchSize int) error
	Save(values ...*model.DeviceActivate) error
	First() (*model.DeviceActivate, error)
	Take() (*model.DeviceActivate, error)
	Last() (*model.DeviceActivate, error)
	Find() ([]*model.DeviceActivate, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.DeviceActivate, err error)
	FindInBatches(result *[]*model.DeviceActivate, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.DeviceActivate) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IDeviceActivateDo
	Assign(attrs ...field.AssignExpr) IDeviceActivateDo
	Joins(fields ...field.RelationField) IDeviceActivateDo
	Preload(fields ...field.RelationField) IDeviceActivateDo
	FirstOrInit() (*model.DeviceActivate, error)
	FirstOrCreate() (*model.DeviceActivate, error)
	FindByPage(offset int, limit int) (result []*model.DeviceActivate, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IDeviceActivateDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (d deviceActivateDo) Debug() IDeviceActivateDo {
	return d.withDO(d.DO.Debug())
}

func (d deviceActivateDo) WithContext(ctx context.Context) IDeviceActivateDo {
	return d.withDO(d.DO.WithContext(ctx))
}

func (d deviceActivateDo) ReadDB() IDeviceActivateDo {
	return d.Clauses(dbresolver.Read)
}

func (d deviceActivateDo) WriteDB() IDeviceActivateDo {
	return d.Clauses(dbresolver.Write)
}

func (d deviceActivateDo) Session(config *gorm.Session) IDeviceActivateDo {
	return d.withDO(d.DO.Session(config))
}

func (d deviceActivateDo) Clauses(conds ...clause.Expression) IDeviceActivateDo {
	return d.withDO(d.DO.Clauses(conds...))
}

func (d deviceActivateDo) Returning(value interface{}, columns ...string) IDeviceActivateDo {
	return d.withDO(d.DO.Returning(value, columns...))
}

func (d deviceActivateDo) Not(conds ...gen.Condition) IDeviceActivateDo {
	return d.withDO(d.DO.Not(conds...))
}

func (d deviceActivateDo) Or(conds ...gen.Condition) IDeviceActivateDo {
	return d.withDO(d.DO.Or(conds...))
}

func (d deviceActivateDo) Select(conds ...field.Expr) IDeviceActivateDo {
	return d.withDO(d.DO.Select(conds...))
}

func (d deviceActivateDo) Where(conds ...gen.Condition) IDeviceActivateDo {
	return d.withDO(d.DO.Where(conds...))
}

func (d deviceActivateDo) Order(conds ...field.Expr) IDeviceActivateDo {
	return d.withDO(d.DO.Order(conds...))
}

func (d deviceActivateDo) Distinct(cols ...field.Expr) IDeviceActivateDo {
	return d.withDO(d.DO.Distinct(cols...))
}

func (d deviceActivateDo) Omit(cols ...field.Expr) IDeviceActivateDo {
	return d.withDO(d.DO.Omit(cols...))
}

func (d deviceActivateDo) Join(table schema.Tabler, on ...field.Expr) IDeviceActivateDo {
	return d.withDO(d.DO.Join(table, on...))
}

func (d deviceActivateDo) LeftJoin(table schema.Tabler, on ...field.Expr) IDeviceActivateDo {
	return d.withDO(d.DO.LeftJoin(table, on...))
}

func (d deviceActivateDo) RightJoin(table schema.Tabler, on ...field.Expr) IDeviceActivateDo {
	return d.withDO(d.DO.RightJoin(table, on...))
}

func (d deviceActivateDo) Group(cols ...field.Expr) IDeviceActivateDo {
	return d.withDO(d.DO.Group(cols...))
}

func (d deviceActivateDo) Having(conds ...gen.Condition) IDeviceActivateDo {
	return d.withDO(d.DO.Having(conds...))
}

func (d deviceActivateDo) Limit(limit int) IDeviceActivateDo {
	return d.withDO(d.DO.Limit(limit))
}

func (d deviceActivateDo) Offset(offset int) IDeviceActivateDo {
	return d.withDO(d.DO.Offset(offset))
}

func (d deviceActivateDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IDeviceActivateDo {
	return d.withDO(d.DO.Scopes(funcs...))
}

func (d deviceActivateDo) Unscoped() IDeviceActivateDo {
	return d.withDO(d.DO.Unscoped())
}

func (d deviceActivateDo) Create(values ...*model.DeviceActivate) error {
	if len(values) == 0 {
		return nil
	}
	return d.DO.Create(values)
}

func (d deviceActivateDo) CreateInBatches(values []*model.DeviceActivate, batchSize int) error {
	return d.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (d deviceActivateDo) Save(values ...*model.DeviceActivate) error {
	if len(values) == 0 {
		return nil
	}
	return d.DO.Save(values)
}

func (d deviceActivateDo) First() (*model.DeviceActivate, error) {
	if result, err := d.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.DeviceActivate), nil
	}
}

func (d deviceActivateDo) Take() (*model.DeviceActivate, error) {
	if result, err := d.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.DeviceActivate), nil
	}
}

func (d deviceActivateDo) Last() (*model.DeviceActivate, error) {
	if result, err := d.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.DeviceActivate), nil
	}
}

func (d deviceActivateDo) Find() ([]*model.DeviceActivate, error) {
	result, err := d.DO.Find()
	return result.([]*model.DeviceActivate), err
}

func (d deviceActivateDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.DeviceActivate, err error) {
	buf := make([]*model.DeviceActivate, 0, batchSize)
	err = d.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (d deviceActivateDo) FindInBatches(result *[]*model.DeviceActivate, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return d.DO.FindInBatches(result, batchSize, fc)
}

func (d deviceActivateDo) Attrs(attrs ...field.AssignExpr) IDeviceActivateDo {
	return d.withDO(d.DO.Attrs(attrs...))
}

func (d deviceActivateDo) Assign(attrs ...field.AssignExpr) IDeviceActivateDo {
	return d.withDO(d.DO.Assign(attrs...))
}

func (d deviceActivateDo) Joins(fields ...field.RelationField) IDeviceActivateDo {
	for _, _f := range fields {
		d = *d.withDO(d.DO.Joins(_f))
	}
	return &d
}

func (d deviceActivateDo) Preload(fields ...field.RelationField) IDeviceActivateDo {
	for _, _f := range fields {
		d = *d.withDO(d.DO.Preload(_f))
	}
	return &d
}

func (d deviceActivateDo) FirstOrInit() (*model.DeviceActivate, error) {
	if result, err := d.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.DeviceActivate), nil
	}
}

func (d deviceActivateDo) FirstOrCreate() (*model.DeviceActivate, error) {
	if result, err := d.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.DeviceActivate), nil
	}
}

func (d deviceActivateDo) FindByPage(offset int, limit int) (result []*model.DeviceActivate, count int64, err error) {
	result, err = d.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = d.Offset(-1).Limit(-1).Count()
	return
}

func (d deviceActivateDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = d.Count()
	if err != nil {
		return
	}

	err = d.Offset(offset).Limit(limit).Scan(result)
	return
}

func (d deviceActivateDo) Scan(result interface{}) (err error) {
	return d.DO.Scan(result)
}

func (d deviceActivateDo) Delete(models ...*model.DeviceActivate) (result gen.ResultInfo, err error) {
	return d.DO.Delete(models)
}

func (d *deviceActivateDo) withDO(do gen.Dao) *deviceActivateDo {
	d.DO = *do.(*gen.DO)
	return d
}
