// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"aibuddy/internal/model"
)

func newGoods(db *gorm.DB, opts ...gen.DOOption) goods {
	_goods := goods{}

	_goods.goodsDo.UseDB(db, opts...)
	_goods.goodsDo.UseModel(&model.Goods{})

	tableName := _goods.goodsDo.TableName()
	_goods.ALL = field.NewAsterisk(tableName)
	_goods.ID = field.NewInt64(tableName, "id")
	_goods.Name = field.NewString(tableName, "name")
	_goods.Price = field.NewInt64(tableName, "price")
	_goods.Stock = field.NewInt64(tableName, "stock")
	_goods.ActivityPrice = field.NewInt64(tableName, "activity_price")
	_goods.Description = field.NewString(tableName, "description")
	_goods.Status = field.NewString(tableName, "status")
	_goods.CreatedAt = field.NewField(tableName, "created_at")
	_goods.UpdatedAt = field.NewField(tableName, "updated_at")

	_goods.fillFieldMap()

	return _goods
}

type goods struct {
	goodsDo

	ALL           field.Asterisk
	ID            field.Int64
	Name          field.String // 商品名称
	Price         field.Int64  // 商品价格
	Stock         field.Int64  // 商品库存
	ActivityPrice field.Int64  // 活动价格
	Description   field.String // 商品描述
	Status        field.String // 商品状态
	CreatedAt     field.Field  // 创建时间
	UpdatedAt     field.Field  // 更新时间

	fieldMap map[string]field.Expr
}

func (g goods) Table(newTableName string) *goods {
	g.goodsDo.UseTable(newTableName)
	return g.updateTableName(newTableName)
}

func (g goods) As(alias string) *goods {
	g.goodsDo.DO = *(g.goodsDo.As(alias).(*gen.DO))
	return g.updateTableName(alias)
}

func (g *goods) updateTableName(table string) *goods {
	g.ALL = field.NewAsterisk(table)
	g.ID = field.NewInt64(table, "id")
	g.Name = field.NewString(table, "name")
	g.Price = field.NewInt64(table, "price")
	g.Stock = field.NewInt64(table, "stock")
	g.ActivityPrice = field.NewInt64(table, "activity_price")
	g.Description = field.NewString(table, "description")
	g.Status = field.NewString(table, "status")
	g.CreatedAt = field.NewField(table, "created_at")
	g.UpdatedAt = field.NewField(table, "updated_at")

	g.fillFieldMap()

	return g
}

func (g *goods) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := g.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (g *goods) fillFieldMap() {
	g.fieldMap = make(map[string]field.Expr, 9)
	g.fieldMap["id"] = g.ID
	g.fieldMap["name"] = g.Name
	g.fieldMap["price"] = g.Price
	g.fieldMap["stock"] = g.Stock
	g.fieldMap["activity_price"] = g.ActivityPrice
	g.fieldMap["description"] = g.Description
	g.fieldMap["status"] = g.Status
	g.fieldMap["created_at"] = g.CreatedAt
	g.fieldMap["updated_at"] = g.UpdatedAt
}

func (g goods) clone(db *gorm.DB) goods {
	g.goodsDo.ReplaceConnPool(db.Statement.ConnPool)
	return g
}

func (g goods) replaceDB(db *gorm.DB) goods {
	g.goodsDo.ReplaceDB(db)
	return g
}

type goodsDo struct{ gen.DO }

type IGoodsDo interface {
	gen.SubQuery
	Debug() IGoodsDo
	WithContext(ctx context.Context) IGoodsDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IGoodsDo
	WriteDB() IGoodsDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IGoodsDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IGoodsDo
	Not(conds ...gen.Condition) IGoodsDo
	Or(conds ...gen.Condition) IGoodsDo
	Select(conds ...field.Expr) IGoodsDo
	Where(conds ...gen.Condition) IGoodsDo
	Order(conds ...field.Expr) IGoodsDo
	Distinct(cols ...field.Expr) IGoodsDo
	Omit(cols ...field.Expr) IGoodsDo
	Join(table schema.Tabler, on ...field.Expr) IGoodsDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IGoodsDo
	RightJoin(table schema.Tabler, on ...field.Expr) IGoodsDo
	Group(cols ...field.Expr) IGoodsDo
	Having(conds ...gen.Condition) IGoodsDo
	Limit(limit int) IGoodsDo
	Offset(offset int) IGoodsDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IGoodsDo
	Unscoped() IGoodsDo
	Create(values ...*model.Goods) error
	CreateInBatches(values []*model.Goods, batchSize int) error
	Save(values ...*model.Goods) error
	First() (*model.Goods, error)
	Take() (*model.Goods, error)
	Last() (*model.Goods, error)
	Find() ([]*model.Goods, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Goods, err error)
	FindInBatches(result *[]*model.Goods, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.Goods) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IGoodsDo
	Assign(attrs ...field.AssignExpr) IGoodsDo
	Joins(fields ...field.RelationField) IGoodsDo
	Preload(fields ...field.RelationField) IGoodsDo
	FirstOrInit() (*model.Goods, error)
	FirstOrCreate() (*model.Goods, error)
	FindByPage(offset int, limit int) (result []*model.Goods, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IGoodsDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (g goodsDo) Debug() IGoodsDo {
	return g.withDO(g.DO.Debug())
}

func (g goodsDo) WithContext(ctx context.Context) IGoodsDo {
	return g.withDO(g.DO.WithContext(ctx))
}

func (g goodsDo) ReadDB() IGoodsDo {
	return g.Clauses(dbresolver.Read)
}

func (g goodsDo) WriteDB() IGoodsDo {
	return g.Clauses(dbresolver.Write)
}

func (g goodsDo) Session(config *gorm.Session) IGoodsDo {
	return g.withDO(g.DO.Session(config))
}

func (g goodsDo) Clauses(conds ...clause.Expression) IGoodsDo {
	return g.withDO(g.DO.Clauses(conds...))
}

func (g goodsDo) Returning(value interface{}, columns ...string) IGoodsDo {
	return g.withDO(g.DO.Returning(value, columns...))
}

func (g goodsDo) Not(conds ...gen.Condition) IGoodsDo {
	return g.withDO(g.DO.Not(conds...))
}

func (g goodsDo) Or(conds ...gen.Condition) IGoodsDo {
	return g.withDO(g.DO.Or(conds...))
}

func (g goodsDo) Select(conds ...field.Expr) IGoodsDo {
	return g.withDO(g.DO.Select(conds...))
}

func (g goodsDo) Where(conds ...gen.Condition) IGoodsDo {
	return g.withDO(g.DO.Where(conds...))
}

func (g goodsDo) Order(conds ...field.Expr) IGoodsDo {
	return g.withDO(g.DO.Order(conds...))
}

func (g goodsDo) Distinct(cols ...field.Expr) IGoodsDo {
	return g.withDO(g.DO.Distinct(cols...))
}

func (g goodsDo) Omit(cols ...field.Expr) IGoodsDo {
	return g.withDO(g.DO.Omit(cols...))
}

func (g goodsDo) Join(table schema.Tabler, on ...field.Expr) IGoodsDo {
	return g.withDO(g.DO.Join(table, on...))
}

func (g goodsDo) LeftJoin(table schema.Tabler, on ...field.Expr) IGoodsDo {
	return g.withDO(g.DO.LeftJoin(table, on...))
}

func (g goodsDo) RightJoin(table schema.Tabler, on ...field.Expr) IGoodsDo {
	return g.withDO(g.DO.RightJoin(table, on...))
}

func (g goodsDo) Group(cols ...field.Expr) IGoodsDo {
	return g.withDO(g.DO.Group(cols...))
}

func (g goodsDo) Having(conds ...gen.Condition) IGoodsDo {
	return g.withDO(g.DO.Having(conds...))
}

func (g goodsDo) Limit(limit int) IGoodsDo {
	return g.withDO(g.DO.Limit(limit))
}

func (g goodsDo) Offset(offset int) IGoodsDo {
	return g.withDO(g.DO.Offset(offset))
}

func (g goodsDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IGoodsDo {
	return g.withDO(g.DO.Scopes(funcs...))
}

func (g goodsDo) Unscoped() IGoodsDo {
	return g.withDO(g.DO.Unscoped())
}

func (g goodsDo) Create(values ...*model.Goods) error {
	if len(values) == 0 {
		return nil
	}
	return g.DO.Create(values)
}

func (g goodsDo) CreateInBatches(values []*model.Goods, batchSize int) error {
	return g.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (g goodsDo) Save(values ...*model.Goods) error {
	if len(values) == 0 {
		return nil
	}
	return g.DO.Save(values)
}

func (g goodsDo) First() (*model.Goods, error) {
	if result, err := g.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.Goods), nil
	}
}

func (g goodsDo) Take() (*model.Goods, error) {
	if result, err := g.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.Goods), nil
	}
}

func (g goodsDo) Last() (*model.Goods, error) {
	if result, err := g.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.Goods), nil
	}
}

func (g goodsDo) Find() ([]*model.Goods, error) {
	result, err := g.DO.Find()
	return result.([]*model.Goods), err
}

func (g goodsDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Goods, err error) {
	buf := make([]*model.Goods, 0, batchSize)
	err = g.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (g goodsDo) FindInBatches(result *[]*model.Goods, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return g.DO.FindInBatches(result, batchSize, fc)
}

func (g goodsDo) Attrs(attrs ...field.AssignExpr) IGoodsDo {
	return g.withDO(g.DO.Attrs(attrs...))
}

func (g goodsDo) Assign(attrs ...field.AssignExpr) IGoodsDo {
	return g.withDO(g.DO.Assign(attrs...))
}

func (g goodsDo) Joins(fields ...field.RelationField) IGoodsDo {
	for _, _f := range fields {
		g = *g.withDO(g.DO.Joins(_f))
	}
	return &g
}

func (g goodsDo) Preload(fields ...field.RelationField) IGoodsDo {
	for _, _f := range fields {
		g = *g.withDO(g.DO.Preload(_f))
	}
	return &g
}

func (g goodsDo) FirstOrInit() (*model.Goods, error) {
	if result, err := g.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.Goods), nil
	}
}

func (g goodsDo) FirstOrCreate() (*model.Goods, error) {
	if result, err := g.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.Goods), nil
	}
}

func (g goodsDo) FindByPage(offset int, limit int) (result []*model.Goods, count int64, err error) {
	result, err = g.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = g.Offset(-1).Limit(-1).Count()
	return
}

func (g goodsDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = g.Count()
	if err != nil {
		return
	}

	err = g.Offset(offset).Limit(limit).Scan(result)
	return
}

func (g goodsDo) Scan(result interface{}) (err error) {
	return g.DO.Scan(result)
}

func (g goodsDo) Delete(models ...*model.Goods) (result gen.ResultInfo, err error) {
	return g.DO.Delete(models)
}

func (g *goodsDo) withDO(do gen.Dao) *goodsDo {
	g.DO = *do.(*gen.DO)
	return g
}
