// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"aibuddy/internal/model"
)

func newDeviceInfo(db *gorm.DB, opts ...gen.DOOption) deviceInfo {
	_deviceInfo := deviceInfo{}

	_deviceInfo.deviceInfoDo.UseDB(db, opts...)
	_deviceInfo.deviceInfoDo.UseModel(&model.DeviceInfo{})

	tableName := _deviceInfo.deviceInfoDo.TableName()
	_deviceInfo.ALL = field.NewAsterisk(tableName)
	_deviceInfo.ID = field.NewInt64(tableName, "id")
	_deviceInfo.DeviceID = field.NewString(tableName, "device_id")
	_deviceInfo.NickName = field.NewString(tableName, "nickname")
	_deviceInfo.Avatar = field.NewString(tableName, "avatar")
	_deviceInfo.Gender = field.NewInt8(tableName, "gender")
	_deviceInfo.Birthday = field.NewTime(tableName, "birthday")
	_deviceInfo.Relation = field.NewString(tableName, "relation")
	_deviceInfo.Hobbies = field.NewField(tableName, "hobbies")
	_deviceInfo.Values = field.NewField(tableName, "values")
	_deviceInfo.Skills = field.NewField(tableName, "skills")
	_deviceInfo.Personality = field.NewField(tableName, "personality")
	_deviceInfo.CreatedAt = field.NewTime(tableName, "created_at")
	_deviceInfo.UpdatedAt = field.NewTime(tableName, "updated_at")

	_deviceInfo.fillFieldMap()

	return _deviceInfo
}

type deviceInfo struct {
	deviceInfoDo

	ALL         field.Asterisk
	ID          field.Int64
	DeviceID    field.String // 设备ID
	NickName    field.String // 设备昵称
	Avatar      field.String // 头像
	Gender      field.Int8   // 性别
	Birthday    field.Time   // 生日
	Relation    field.String // 关系
	Hobbies     field.Field  // 兴趣
	Values      field.Field  // 价值观
	Skills      field.Field  // 技能
	Personality field.Field  // 性格
	CreatedAt   field.Time   // 创建时间
	UpdatedAt   field.Time   // 更新时间

	fieldMap map[string]field.Expr
}

func (d deviceInfo) Table(newTableName string) *deviceInfo {
	d.deviceInfoDo.UseTable(newTableName)
	return d.updateTableName(newTableName)
}

func (d deviceInfo) As(alias string) *deviceInfo {
	d.deviceInfoDo.DO = *(d.deviceInfoDo.As(alias).(*gen.DO))
	return d.updateTableName(alias)
}

func (d *deviceInfo) updateTableName(table string) *deviceInfo {
	d.ALL = field.NewAsterisk(table)
	d.ID = field.NewInt64(table, "id")
	d.DeviceID = field.NewString(table, "device_id")
	d.NickName = field.NewString(table, "nickname")
	d.Avatar = field.NewString(table, "avatar")
	d.Gender = field.NewInt8(table, "gender")
	d.Birthday = field.NewTime(table, "birthday")
	d.Relation = field.NewString(table, "relation")
	d.Hobbies = field.NewField(table, "hobbies")
	d.Values = field.NewField(table, "values")
	d.Skills = field.NewField(table, "skills")
	d.Personality = field.NewField(table, "personality")
	d.CreatedAt = field.NewTime(table, "created_at")
	d.UpdatedAt = field.NewTime(table, "updated_at")

	d.fillFieldMap()

	return d
}

func (d *deviceInfo) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := d.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (d *deviceInfo) fillFieldMap() {
	d.fieldMap = make(map[string]field.Expr, 13)
	d.fieldMap["id"] = d.ID
	d.fieldMap["device_id"] = d.DeviceID
	d.fieldMap["nickname"] = d.NickName
	d.fieldMap["avatar"] = d.Avatar
	d.fieldMap["gender"] = d.Gender
	d.fieldMap["birthday"] = d.Birthday
	d.fieldMap["relation"] = d.Relation
	d.fieldMap["hobbies"] = d.Hobbies
	d.fieldMap["values"] = d.Values
	d.fieldMap["skills"] = d.Skills
	d.fieldMap["personality"] = d.Personality
	d.fieldMap["created_at"] = d.CreatedAt
	d.fieldMap["updated_at"] = d.UpdatedAt
}

func (d deviceInfo) clone(db *gorm.DB) deviceInfo {
	d.deviceInfoDo.ReplaceConnPool(db.Statement.ConnPool)
	return d
}

func (d deviceInfo) replaceDB(db *gorm.DB) deviceInfo {
	d.deviceInfoDo.ReplaceDB(db)
	return d
}

type deviceInfoDo struct{ gen.DO }

type IDeviceInfoDo interface {
	gen.SubQuery
	Debug() IDeviceInfoDo
	WithContext(ctx context.Context) IDeviceInfoDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IDeviceInfoDo
	WriteDB() IDeviceInfoDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IDeviceInfoDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IDeviceInfoDo
	Not(conds ...gen.Condition) IDeviceInfoDo
	Or(conds ...gen.Condition) IDeviceInfoDo
	Select(conds ...field.Expr) IDeviceInfoDo
	Where(conds ...gen.Condition) IDeviceInfoDo
	Order(conds ...field.Expr) IDeviceInfoDo
	Distinct(cols ...field.Expr) IDeviceInfoDo
	Omit(cols ...field.Expr) IDeviceInfoDo
	Join(table schema.Tabler, on ...field.Expr) IDeviceInfoDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IDeviceInfoDo
	RightJoin(table schema.Tabler, on ...field.Expr) IDeviceInfoDo
	Group(cols ...field.Expr) IDeviceInfoDo
	Having(conds ...gen.Condition) IDeviceInfoDo
	Limit(limit int) IDeviceInfoDo
	Offset(offset int) IDeviceInfoDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IDeviceInfoDo
	Unscoped() IDeviceInfoDo
	Create(values ...*model.DeviceInfo) error
	CreateInBatches(values []*model.DeviceInfo, batchSize int) error
	Save(values ...*model.DeviceInfo) error
	First() (*model.DeviceInfo, error)
	Take() (*model.DeviceInfo, error)
	Last() (*model.DeviceInfo, error)
	Find() ([]*model.DeviceInfo, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.DeviceInfo, err error)
	FindInBatches(result *[]*model.DeviceInfo, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.DeviceInfo) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IDeviceInfoDo
	Assign(attrs ...field.AssignExpr) IDeviceInfoDo
	Joins(fields ...field.RelationField) IDeviceInfoDo
	Preload(fields ...field.RelationField) IDeviceInfoDo
	FirstOrInit() (*model.DeviceInfo, error)
	FirstOrCreate() (*model.DeviceInfo, error)
	FindByPage(offset int, limit int) (result []*model.DeviceInfo, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IDeviceInfoDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (d deviceInfoDo) Debug() IDeviceInfoDo {
	return d.withDO(d.DO.Debug())
}

func (d deviceInfoDo) WithContext(ctx context.Context) IDeviceInfoDo {
	return d.withDO(d.DO.WithContext(ctx))
}

func (d deviceInfoDo) ReadDB() IDeviceInfoDo {
	return d.Clauses(dbresolver.Read)
}

func (d deviceInfoDo) WriteDB() IDeviceInfoDo {
	return d.Clauses(dbresolver.Write)
}

func (d deviceInfoDo) Session(config *gorm.Session) IDeviceInfoDo {
	return d.withDO(d.DO.Session(config))
}

func (d deviceInfoDo) Clauses(conds ...clause.Expression) IDeviceInfoDo {
	return d.withDO(d.DO.Clauses(conds...))
}

func (d deviceInfoDo) Returning(value interface{}, columns ...string) IDeviceInfoDo {
	return d.withDO(d.DO.Returning(value, columns...))
}

func (d deviceInfoDo) Not(conds ...gen.Condition) IDeviceInfoDo {
	return d.withDO(d.DO.Not(conds...))
}

func (d deviceInfoDo) Or(conds ...gen.Condition) IDeviceInfoDo {
	return d.withDO(d.DO.Or(conds...))
}

func (d deviceInfoDo) Select(conds ...field.Expr) IDeviceInfoDo {
	return d.withDO(d.DO.Select(conds...))
}

func (d deviceInfoDo) Where(conds ...gen.Condition) IDeviceInfoDo {
	return d.withDO(d.DO.Where(conds...))
}

func (d deviceInfoDo) Order(conds ...field.Expr) IDeviceInfoDo {
	return d.withDO(d.DO.Order(conds...))
}

func (d deviceInfoDo) Distinct(cols ...field.Expr) IDeviceInfoDo {
	return d.withDO(d.DO.Distinct(cols...))
}

func (d deviceInfoDo) Omit(cols ...field.Expr) IDeviceInfoDo {
	return d.withDO(d.DO.Omit(cols...))
}

func (d deviceInfoDo) Join(table schema.Tabler, on ...field.Expr) IDeviceInfoDo {
	return d.withDO(d.DO.Join(table, on...))
}

func (d deviceInfoDo) LeftJoin(table schema.Tabler, on ...field.Expr) IDeviceInfoDo {
	return d.withDO(d.DO.LeftJoin(table, on...))
}

func (d deviceInfoDo) RightJoin(table schema.Tabler, on ...field.Expr) IDeviceInfoDo {
	return d.withDO(d.DO.RightJoin(table, on...))
}

func (d deviceInfoDo) Group(cols ...field.Expr) IDeviceInfoDo {
	return d.withDO(d.DO.Group(cols...))
}

func (d deviceInfoDo) Having(conds ...gen.Condition) IDeviceInfoDo {
	return d.withDO(d.DO.Having(conds...))
}

func (d deviceInfoDo) Limit(limit int) IDeviceInfoDo {
	return d.withDO(d.DO.Limit(limit))
}

func (d deviceInfoDo) Offset(offset int) IDeviceInfoDo {
	return d.withDO(d.DO.Offset(offset))
}

func (d deviceInfoDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IDeviceInfoDo {
	return d.withDO(d.DO.Scopes(funcs...))
}

func (d deviceInfoDo) Unscoped() IDeviceInfoDo {
	return d.withDO(d.DO.Unscoped())
}

func (d deviceInfoDo) Create(values ...*model.DeviceInfo) error {
	if len(values) == 0 {
		return nil
	}
	return d.DO.Create(values)
}

func (d deviceInfoDo) CreateInBatches(values []*model.DeviceInfo, batchSize int) error {
	return d.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (d deviceInfoDo) Save(values ...*model.DeviceInfo) error {
	if len(values) == 0 {
		return nil
	}
	return d.DO.Save(values)
}

func (d deviceInfoDo) First() (*model.DeviceInfo, error) {
	if result, err := d.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.DeviceInfo), nil
	}
}

func (d deviceInfoDo) Take() (*model.DeviceInfo, error) {
	if result, err := d.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.DeviceInfo), nil
	}
}

func (d deviceInfoDo) Last() (*model.DeviceInfo, error) {
	if result, err := d.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.DeviceInfo), nil
	}
}

func (d deviceInfoDo) Find() ([]*model.DeviceInfo, error) {
	result, err := d.DO.Find()
	return result.([]*model.DeviceInfo), err
}

func (d deviceInfoDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.DeviceInfo, err error) {
	buf := make([]*model.DeviceInfo, 0, batchSize)
	err = d.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (d deviceInfoDo) FindInBatches(result *[]*model.DeviceInfo, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return d.DO.FindInBatches(result, batchSize, fc)
}

func (d deviceInfoDo) Attrs(attrs ...field.AssignExpr) IDeviceInfoDo {
	return d.withDO(d.DO.Attrs(attrs...))
}

func (d deviceInfoDo) Assign(attrs ...field.AssignExpr) IDeviceInfoDo {
	return d.withDO(d.DO.Assign(attrs...))
}

func (d deviceInfoDo) Joins(fields ...field.RelationField) IDeviceInfoDo {
	for _, _f := range fields {
		d = *d.withDO(d.DO.Joins(_f))
	}
	return &d
}

func (d deviceInfoDo) Preload(fields ...field.RelationField) IDeviceInfoDo {
	for _, _f := range fields {
		d = *d.withDO(d.DO.Preload(_f))
	}
	return &d
}

func (d deviceInfoDo) FirstOrInit() (*model.DeviceInfo, error) {
	if result, err := d.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.DeviceInfo), nil
	}
}

func (d deviceInfoDo) FirstOrCreate() (*model.DeviceInfo, error) {
	if result, err := d.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.DeviceInfo), nil
	}
}

func (d deviceInfoDo) FindByPage(offset int, limit int) (result []*model.DeviceInfo, count int64, err error) {
	result, err = d.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = d.Offset(-1).Limit(-1).Count()
	return
}

func (d deviceInfoDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = d.Count()
	if err != nil {
		return
	}

	err = d.Offset(offset).Limit(limit).Scan(result)
	return
}

func (d deviceInfoDo) Scan(result interface{}) (err error) {
	return d.DO.Scan(result)
}

func (d deviceInfoDo) Delete(models ...*model.DeviceInfo) (result gen.ResultInfo, err error) {
	return d.DO.Delete(models)
}

func (d *deviceInfoDo) withDO(do gen.Dao) *deviceInfoDo {
	d.DO = *do.(*gen.DO)
	return d
}
