// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"aibuddy/internal/model"
)

func newDeviceRelationship(db *gorm.DB, opts ...gen.DOOption) deviceRelationship {
	_deviceRelationship := deviceRelationship{}

	_deviceRelationship.deviceRelationshipDo.UseDB(db, opts...)
	_deviceRelationship.deviceRelationshipDo.UseModel(&model.DeviceRelationship{})

	tableName := _deviceRelationship.deviceRelationshipDo.TableName()
	_deviceRelationship.ALL = field.NewAsterisk(tableName)
	_deviceRelationship.ID = field.NewInt64(tableName, "id")
	_deviceRelationship.DeviceID = field.NewString(tableName, "device_id")
	_deviceRelationship.TargetDeviceID = field.NewString(tableName, "target_device_id")
	_deviceRelationship.Status = field.NewString(tableName, "status")
	_deviceRelationship.CreatedAt = field.NewTime(tableName, "created_at")
	_deviceRelationship.UpdatedAt = field.NewTime(tableName, "updated_at")

	_deviceRelationship.fillFieldMap()

	return _deviceRelationship
}

type deviceRelationship struct {
	deviceRelationshipDo

	ALL            field.Asterisk
	ID             field.Int64
	DeviceID       field.String // 发起方用户ID
	TargetDeviceID field.String // 目标用户ID
	Status         field.String // 关系状态
	CreatedAt      field.Time   // 创建时间
	UpdatedAt      field.Time   // 更新时间

	fieldMap map[string]field.Expr
}

func (d deviceRelationship) Table(newTableName string) *deviceRelationship {
	d.deviceRelationshipDo.UseTable(newTableName)
	return d.updateTableName(newTableName)
}

func (d deviceRelationship) As(alias string) *deviceRelationship {
	d.deviceRelationshipDo.DO = *(d.deviceRelationshipDo.As(alias).(*gen.DO))
	return d.updateTableName(alias)
}

func (d *deviceRelationship) updateTableName(table string) *deviceRelationship {
	d.ALL = field.NewAsterisk(table)
	d.ID = field.NewInt64(table, "id")
	d.DeviceID = field.NewString(table, "device_id")
	d.TargetDeviceID = field.NewString(table, "target_device_id")
	d.Status = field.NewString(table, "status")
	d.CreatedAt = field.NewTime(table, "created_at")
	d.UpdatedAt = field.NewTime(table, "updated_at")

	d.fillFieldMap()

	return d
}

func (d *deviceRelationship) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := d.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (d *deviceRelationship) fillFieldMap() {
	d.fieldMap = make(map[string]field.Expr, 6)
	d.fieldMap["id"] = d.ID
	d.fieldMap["device_id"] = d.DeviceID
	d.fieldMap["target_device_id"] = d.TargetDeviceID
	d.fieldMap["status"] = d.Status
	d.fieldMap["created_at"] = d.CreatedAt
	d.fieldMap["updated_at"] = d.UpdatedAt
}

func (d deviceRelationship) clone(db *gorm.DB) deviceRelationship {
	d.deviceRelationshipDo.ReplaceConnPool(db.Statement.ConnPool)
	return d
}

func (d deviceRelationship) replaceDB(db *gorm.DB) deviceRelationship {
	d.deviceRelationshipDo.ReplaceDB(db)
	return d
}

type deviceRelationshipDo struct{ gen.DO }

type IDeviceRelationshipDo interface {
	gen.SubQuery
	Debug() IDeviceRelationshipDo
	WithContext(ctx context.Context) IDeviceRelationshipDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IDeviceRelationshipDo
	WriteDB() IDeviceRelationshipDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IDeviceRelationshipDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IDeviceRelationshipDo
	Not(conds ...gen.Condition) IDeviceRelationshipDo
	Or(conds ...gen.Condition) IDeviceRelationshipDo
	Select(conds ...field.Expr) IDeviceRelationshipDo
	Where(conds ...gen.Condition) IDeviceRelationshipDo
	Order(conds ...field.Expr) IDeviceRelationshipDo
	Distinct(cols ...field.Expr) IDeviceRelationshipDo
	Omit(cols ...field.Expr) IDeviceRelationshipDo
	Join(table schema.Tabler, on ...field.Expr) IDeviceRelationshipDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IDeviceRelationshipDo
	RightJoin(table schema.Tabler, on ...field.Expr) IDeviceRelationshipDo
	Group(cols ...field.Expr) IDeviceRelationshipDo
	Having(conds ...gen.Condition) IDeviceRelationshipDo
	Limit(limit int) IDeviceRelationshipDo
	Offset(offset int) IDeviceRelationshipDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IDeviceRelationshipDo
	Unscoped() IDeviceRelationshipDo
	Create(values ...*model.DeviceRelationship) error
	CreateInBatches(values []*model.DeviceRelationship, batchSize int) error
	Save(values ...*model.DeviceRelationship) error
	First() (*model.DeviceRelationship, error)
	Take() (*model.DeviceRelationship, error)
	Last() (*model.DeviceRelationship, error)
	Find() ([]*model.DeviceRelationship, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.DeviceRelationship, err error)
	FindInBatches(result *[]*model.DeviceRelationship, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.DeviceRelationship) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IDeviceRelationshipDo
	Assign(attrs ...field.AssignExpr) IDeviceRelationshipDo
	Joins(fields ...field.RelationField) IDeviceRelationshipDo
	Preload(fields ...field.RelationField) IDeviceRelationshipDo
	FirstOrInit() (*model.DeviceRelationship, error)
	FirstOrCreate() (*model.DeviceRelationship, error)
	FindByPage(offset int, limit int) (result []*model.DeviceRelationship, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IDeviceRelationshipDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (d deviceRelationshipDo) Debug() IDeviceRelationshipDo {
	return d.withDO(d.DO.Debug())
}

func (d deviceRelationshipDo) WithContext(ctx context.Context) IDeviceRelationshipDo {
	return d.withDO(d.DO.WithContext(ctx))
}

func (d deviceRelationshipDo) ReadDB() IDeviceRelationshipDo {
	return d.Clauses(dbresolver.Read)
}

func (d deviceRelationshipDo) WriteDB() IDeviceRelationshipDo {
	return d.Clauses(dbresolver.Write)
}

func (d deviceRelationshipDo) Session(config *gorm.Session) IDeviceRelationshipDo {
	return d.withDO(d.DO.Session(config))
}

func (d deviceRelationshipDo) Clauses(conds ...clause.Expression) IDeviceRelationshipDo {
	return d.withDO(d.DO.Clauses(conds...))
}

func (d deviceRelationshipDo) Returning(value interface{}, columns ...string) IDeviceRelationshipDo {
	return d.withDO(d.DO.Returning(value, columns...))
}

func (d deviceRelationshipDo) Not(conds ...gen.Condition) IDeviceRelationshipDo {
	return d.withDO(d.DO.Not(conds...))
}

func (d deviceRelationshipDo) Or(conds ...gen.Condition) IDeviceRelationshipDo {
	return d.withDO(d.DO.Or(conds...))
}

func (d deviceRelationshipDo) Select(conds ...field.Expr) IDeviceRelationshipDo {
	return d.withDO(d.DO.Select(conds...))
}

func (d deviceRelationshipDo) Where(conds ...gen.Condition) IDeviceRelationshipDo {
	return d.withDO(d.DO.Where(conds...))
}

func (d deviceRelationshipDo) Order(conds ...field.Expr) IDeviceRelationshipDo {
	return d.withDO(d.DO.Order(conds...))
}

func (d deviceRelationshipDo) Distinct(cols ...field.Expr) IDeviceRelationshipDo {
	return d.withDO(d.DO.Distinct(cols...))
}

func (d deviceRelationshipDo) Omit(cols ...field.Expr) IDeviceRelationshipDo {
	return d.withDO(d.DO.Omit(cols...))
}

func (d deviceRelationshipDo) Join(table schema.Tabler, on ...field.Expr) IDeviceRelationshipDo {
	return d.withDO(d.DO.Join(table, on...))
}

func (d deviceRelationshipDo) LeftJoin(table schema.Tabler, on ...field.Expr) IDeviceRelationshipDo {
	return d.withDO(d.DO.LeftJoin(table, on...))
}

func (d deviceRelationshipDo) RightJoin(table schema.Tabler, on ...field.Expr) IDeviceRelationshipDo {
	return d.withDO(d.DO.RightJoin(table, on...))
}

func (d deviceRelationshipDo) Group(cols ...field.Expr) IDeviceRelationshipDo {
	return d.withDO(d.DO.Group(cols...))
}

func (d deviceRelationshipDo) Having(conds ...gen.Condition) IDeviceRelationshipDo {
	return d.withDO(d.DO.Having(conds...))
}

func (d deviceRelationshipDo) Limit(limit int) IDeviceRelationshipDo {
	return d.withDO(d.DO.Limit(limit))
}

func (d deviceRelationshipDo) Offset(offset int) IDeviceRelationshipDo {
	return d.withDO(d.DO.Offset(offset))
}

func (d deviceRelationshipDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IDeviceRelationshipDo {
	return d.withDO(d.DO.Scopes(funcs...))
}

func (d deviceRelationshipDo) Unscoped() IDeviceRelationshipDo {
	return d.withDO(d.DO.Unscoped())
}

func (d deviceRelationshipDo) Create(values ...*model.DeviceRelationship) error {
	if len(values) == 0 {
		return nil
	}
	return d.DO.Create(values)
}

func (d deviceRelationshipDo) CreateInBatches(values []*model.DeviceRelationship, batchSize int) error {
	return d.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (d deviceRelationshipDo) Save(values ...*model.DeviceRelationship) error {
	if len(values) == 0 {
		return nil
	}
	return d.DO.Save(values)
}

func (d deviceRelationshipDo) First() (*model.DeviceRelationship, error) {
	if result, err := d.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.DeviceRelationship), nil
	}
}

func (d deviceRelationshipDo) Take() (*model.DeviceRelationship, error) {
	if result, err := d.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.DeviceRelationship), nil
	}
}

func (d deviceRelationshipDo) Last() (*model.DeviceRelationship, error) {
	if result, err := d.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.DeviceRelationship), nil
	}
}

func (d deviceRelationshipDo) Find() ([]*model.DeviceRelationship, error) {
	result, err := d.DO.Find()
	return result.([]*model.DeviceRelationship), err
}

func (d deviceRelationshipDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.DeviceRelationship, err error) {
	buf := make([]*model.DeviceRelationship, 0, batchSize)
	err = d.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (d deviceRelationshipDo) FindInBatches(result *[]*model.DeviceRelationship, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return d.DO.FindInBatches(result, batchSize, fc)
}

func (d deviceRelationshipDo) Attrs(attrs ...field.AssignExpr) IDeviceRelationshipDo {
	return d.withDO(d.DO.Attrs(attrs...))
}

func (d deviceRelationshipDo) Assign(attrs ...field.AssignExpr) IDeviceRelationshipDo {
	return d.withDO(d.DO.Assign(attrs...))
}

func (d deviceRelationshipDo) Joins(fields ...field.RelationField) IDeviceRelationshipDo {
	for _, _f := range fields {
		d = *d.withDO(d.DO.Joins(_f))
	}
	return &d
}

func (d deviceRelationshipDo) Preload(fields ...field.RelationField) IDeviceRelationshipDo {
	for _, _f := range fields {
		d = *d.withDO(d.DO.Preload(_f))
	}
	return &d
}

func (d deviceRelationshipDo) FirstOrInit() (*model.DeviceRelationship, error) {
	if result, err := d.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.DeviceRelationship), nil
	}
}

func (d deviceRelationshipDo) FirstOrCreate() (*model.DeviceRelationship, error) {
	if result, err := d.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.DeviceRelationship), nil
	}
}

func (d deviceRelationshipDo) FindByPage(offset int, limit int) (result []*model.DeviceRelationship, count int64, err error) {
	result, err = d.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = d.Offset(-1).Limit(-1).Count()
	return
}

func (d deviceRelationshipDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = d.Count()
	if err != nil {
		return
	}

	err = d.Offset(offset).Limit(limit).Scan(result)
	return
}

func (d deviceRelationshipDo) Scan(result interface{}) (err error) {
	return d.DO.Scan(result)
}

func (d deviceRelationshipDo) Delete(models ...*model.DeviceRelationship) (result gen.ResultInfo, err error) {
	return d.DO.Delete(models)
}

func (d *deviceRelationshipDo) withDO(do gen.Dao) *deviceRelationshipDo {
	d.DO = *do.(*gen.DO)
	return d
}
