// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"aibuddy/internal/model"
)

func newNFC(db *gorm.DB, opts ...gen.DOOption) nFC {
	_nFC := nFC{}

	_nFC.nFCDo.UseDB(db, opts...)
	_nFC.nFCDo.UseModel(&model.NFC{})

	tableName := _nFC.nFCDo.TableName()
	_nFC.ALL = field.NewAsterisk(tableName)
	_nFC.ID = field.NewInt64(tableName, "id")
	_nFC.DeviceID = field.NewString(tableName, "device_id")
	_nFC.UID = field.NewInt64(tableName, "uid")
	_nFC.Cid = field.NewString(tableName, "cid")
	_nFC.Ctype = field.NewString(tableName, "ctype")
	_nFC.NFCID = field.NewString(tableName, "nfc_id")
	_nFC.Title = field.NewString(tableName, "title")
	_nFC.Content = field.NewString(tableName, "content")
	_nFC.Voice = field.NewString(tableName, "voice")
	_nFC.Picture = field.NewString(tableName, "picture")
	_nFC.Status = field.NewString(tableName, "status")
	_nFC.CreatedAt = field.NewTime(tableName, "created_at")
	_nFC.UpdatedAt = field.NewTime(tableName, "updated_at")

	_nFC.fillFieldMap()

	return _nFC
}

type nFC struct {
	nFCDo

	ALL       field.Asterisk
	ID        field.Int64
	DeviceID  field.String
	UID       field.Int64
	Cid       field.String
	Ctype     field.String
	NFCID     field.String
	Title     field.String
	Content   field.String
	Voice     field.String
	Picture   field.String
	Status    field.String
	CreatedAt field.Time
	UpdatedAt field.Time

	fieldMap map[string]field.Expr
}

func (n nFC) Table(newTableName string) *nFC {
	n.nFCDo.UseTable(newTableName)
	return n.updateTableName(newTableName)
}

func (n nFC) As(alias string) *nFC {
	n.nFCDo.DO = *(n.nFCDo.As(alias).(*gen.DO))
	return n.updateTableName(alias)
}

func (n *nFC) updateTableName(table string) *nFC {
	n.ALL = field.NewAsterisk(table)
	n.ID = field.NewInt64(table, "id")
	n.DeviceID = field.NewString(table, "device_id")
	n.UID = field.NewInt64(table, "uid")
	n.Cid = field.NewString(table, "cid")
	n.Ctype = field.NewString(table, "ctype")
	n.NFCID = field.NewString(table, "nfc_id")
	n.Title = field.NewString(table, "title")
	n.Content = field.NewString(table, "content")
	n.Voice = field.NewString(table, "voice")
	n.Picture = field.NewString(table, "picture")
	n.Status = field.NewString(table, "status")
	n.CreatedAt = field.NewTime(table, "created_at")
	n.UpdatedAt = field.NewTime(table, "updated_at")

	n.fillFieldMap()

	return n
}

func (n *nFC) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := n.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (n *nFC) fillFieldMap() {
	n.fieldMap = make(map[string]field.Expr, 13)
	n.fieldMap["id"] = n.ID
	n.fieldMap["device_id"] = n.DeviceID
	n.fieldMap["uid"] = n.UID
	n.fieldMap["cid"] = n.Cid
	n.fieldMap["ctype"] = n.Ctype
	n.fieldMap["nfc_id"] = n.NFCID
	n.fieldMap["title"] = n.Title
	n.fieldMap["content"] = n.Content
	n.fieldMap["voice"] = n.Voice
	n.fieldMap["picture"] = n.Picture
	n.fieldMap["status"] = n.Status
	n.fieldMap["created_at"] = n.CreatedAt
	n.fieldMap["updated_at"] = n.UpdatedAt
}

func (n nFC) clone(db *gorm.DB) nFC {
	n.nFCDo.ReplaceConnPool(db.Statement.ConnPool)
	return n
}

func (n nFC) replaceDB(db *gorm.DB) nFC {
	n.nFCDo.ReplaceDB(db)
	return n
}

type nFCDo struct{ gen.DO }

type INFCDo interface {
	gen.SubQuery
	Debug() INFCDo
	WithContext(ctx context.Context) INFCDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() INFCDo
	WriteDB() INFCDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) INFCDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) INFCDo
	Not(conds ...gen.Condition) INFCDo
	Or(conds ...gen.Condition) INFCDo
	Select(conds ...field.Expr) INFCDo
	Where(conds ...gen.Condition) INFCDo
	Order(conds ...field.Expr) INFCDo
	Distinct(cols ...field.Expr) INFCDo
	Omit(cols ...field.Expr) INFCDo
	Join(table schema.Tabler, on ...field.Expr) INFCDo
	LeftJoin(table schema.Tabler, on ...field.Expr) INFCDo
	RightJoin(table schema.Tabler, on ...field.Expr) INFCDo
	Group(cols ...field.Expr) INFCDo
	Having(conds ...gen.Condition) INFCDo
	Limit(limit int) INFCDo
	Offset(offset int) INFCDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) INFCDo
	Unscoped() INFCDo
	Create(values ...*model.NFC) error
	CreateInBatches(values []*model.NFC, batchSize int) error
	Save(values ...*model.NFC) error
	First() (*model.NFC, error)
	Take() (*model.NFC, error)
	Last() (*model.NFC, error)
	Find() ([]*model.NFC, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.NFC, err error)
	FindInBatches(result *[]*model.NFC, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.NFC) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) INFCDo
	Assign(attrs ...field.AssignExpr) INFCDo
	Joins(fields ...field.RelationField) INFCDo
	Preload(fields ...field.RelationField) INFCDo
	FirstOrInit() (*model.NFC, error)
	FirstOrCreate() (*model.NFC, error)
	FindByPage(offset int, limit int) (result []*model.NFC, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) INFCDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (n nFCDo) Debug() INFCDo {
	return n.withDO(n.DO.Debug())
}

func (n nFCDo) WithContext(ctx context.Context) INFCDo {
	return n.withDO(n.DO.WithContext(ctx))
}

func (n nFCDo) ReadDB() INFCDo {
	return n.Clauses(dbresolver.Read)
}

func (n nFCDo) WriteDB() INFCDo {
	return n.Clauses(dbresolver.Write)
}

func (n nFCDo) Session(config *gorm.Session) INFCDo {
	return n.withDO(n.DO.Session(config))
}

func (n nFCDo) Clauses(conds ...clause.Expression) INFCDo {
	return n.withDO(n.DO.Clauses(conds...))
}

func (n nFCDo) Returning(value interface{}, columns ...string) INFCDo {
	return n.withDO(n.DO.Returning(value, columns...))
}

func (n nFCDo) Not(conds ...gen.Condition) INFCDo {
	return n.withDO(n.DO.Not(conds...))
}

func (n nFCDo) Or(conds ...gen.Condition) INFCDo {
	return n.withDO(n.DO.Or(conds...))
}

func (n nFCDo) Select(conds ...field.Expr) INFCDo {
	return n.withDO(n.DO.Select(conds...))
}

func (n nFCDo) Where(conds ...gen.Condition) INFCDo {
	return n.withDO(n.DO.Where(conds...))
}

func (n nFCDo) Order(conds ...field.Expr) INFCDo {
	return n.withDO(n.DO.Order(conds...))
}

func (n nFCDo) Distinct(cols ...field.Expr) INFCDo {
	return n.withDO(n.DO.Distinct(cols...))
}

func (n nFCDo) Omit(cols ...field.Expr) INFCDo {
	return n.withDO(n.DO.Omit(cols...))
}

func (n nFCDo) Join(table schema.Tabler, on ...field.Expr) INFCDo {
	return n.withDO(n.DO.Join(table, on...))
}

func (n nFCDo) LeftJoin(table schema.Tabler, on ...field.Expr) INFCDo {
	return n.withDO(n.DO.LeftJoin(table, on...))
}

func (n nFCDo) RightJoin(table schema.Tabler, on ...field.Expr) INFCDo {
	return n.withDO(n.DO.RightJoin(table, on...))
}

func (n nFCDo) Group(cols ...field.Expr) INFCDo {
	return n.withDO(n.DO.Group(cols...))
}

func (n nFCDo) Having(conds ...gen.Condition) INFCDo {
	return n.withDO(n.DO.Having(conds...))
}

func (n nFCDo) Limit(limit int) INFCDo {
	return n.withDO(n.DO.Limit(limit))
}

func (n nFCDo) Offset(offset int) INFCDo {
	return n.withDO(n.DO.Offset(offset))
}

func (n nFCDo) Scopes(funcs ...func(gen.Dao) gen.Dao) INFCDo {
	return n.withDO(n.DO.Scopes(funcs...))
}

func (n nFCDo) Unscoped() INFCDo {
	return n.withDO(n.DO.Unscoped())
}

func (n nFCDo) Create(values ...*model.NFC) error {
	if len(values) == 0 {
		return nil
	}
	return n.DO.Create(values)
}

func (n nFCDo) CreateInBatches(values []*model.NFC, batchSize int) error {
	return n.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (n nFCDo) Save(values ...*model.NFC) error {
	if len(values) == 0 {
		return nil
	}
	return n.DO.Save(values)
}

func (n nFCDo) First() (*model.NFC, error) {
	if result, err := n.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.NFC), nil
	}
}

func (n nFCDo) Take() (*model.NFC, error) {
	if result, err := n.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.NFC), nil
	}
}

func (n nFCDo) Last() (*model.NFC, error) {
	if result, err := n.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.NFC), nil
	}
}

func (n nFCDo) Find() ([]*model.NFC, error) {
	result, err := n.DO.Find()
	return result.([]*model.NFC), err
}

func (n nFCDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.NFC, err error) {
	buf := make([]*model.NFC, 0, batchSize)
	err = n.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (n nFCDo) FindInBatches(result *[]*model.NFC, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return n.DO.FindInBatches(result, batchSize, fc)
}

func (n nFCDo) Attrs(attrs ...field.AssignExpr) INFCDo {
	return n.withDO(n.DO.Attrs(attrs...))
}

func (n nFCDo) Assign(attrs ...field.AssignExpr) INFCDo {
	return n.withDO(n.DO.Assign(attrs...))
}

func (n nFCDo) Joins(fields ...field.RelationField) INFCDo {
	for _, _f := range fields {
		n = *n.withDO(n.DO.Joins(_f))
	}
	return &n
}

func (n nFCDo) Preload(fields ...field.RelationField) INFCDo {
	for _, _f := range fields {
		n = *n.withDO(n.DO.Preload(_f))
	}
	return &n
}

func (n nFCDo) FirstOrInit() (*model.NFC, error) {
	if result, err := n.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.NFC), nil
	}
}

func (n nFCDo) FirstOrCreate() (*model.NFC, error) {
	if result, err := n.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.NFC), nil
	}
}

func (n nFCDo) FindByPage(offset int, limit int) (result []*model.NFC, count int64, err error) {
	result, err = n.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = n.Offset(-1).Limit(-1).Count()
	return
}

func (n nFCDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = n.Count()
	if err != nil {
		return
	}

	err = n.Offset(offset).Limit(limit).Scan(result)
	return
}

func (n nFCDo) Scan(result interface{}) (err error) {
	return n.DO.Scan(result)
}

func (n nFCDo) Delete(models ...*model.NFC) (result gen.ResultInfo, err error) {
	return n.DO.Delete(models)
}

func (n *nFCDo) withDO(do gen.Dao) *nFCDo {
	n.DO = *do.(*gen.DO)
	return n
}
