// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"aibuddy/internal/model"
)

func newChatDialogue(db *gorm.DB, opts ...gen.DOOption) chatDialogue {
	_chatDialogue := chatDialogue{}

	_chatDialogue.chatDialogueDo.UseDB(db, opts...)
	_chatDialogue.chatDialogueDo.UseModel(&model.ChatDialogue{})

	tableName := _chatDialogue.chatDialogueDo.TableName()
	_chatDialogue.ALL = field.NewAsterisk(tableName)
	_chatDialogue.ID = field.NewInt64(tableName, "id")
	_chatDialogue.DeviceID = field.NewString(tableName, "device_id")
	_chatDialogue.Question = field.NewString(tableName, "question")
	_chatDialogue.QuestionTime = field.NewTime(tableName, "question_time")
	_chatDialogue.Answer = field.NewString(tableName, "answer")
	_chatDialogue.AnswerTime = field.NewTime(tableName, "answer_time")
	_chatDialogue.CreatedAt = field.NewTime(tableName, "created_at")
	_chatDialogue.UpdatedAt = field.NewTime(tableName, "updated_at")

	_chatDialogue.fillFieldMap()

	return _chatDialogue
}

type chatDialogue struct {
	chatDialogueDo

	ALL          field.Asterisk
	ID           field.Int64
	DeviceID     field.String // 设备ID
	Question     field.String // 问题内容
	QuestionTime field.Time   // 问题时间
	Answer       field.String // 回答内容
	AnswerTime   field.Time   // 回答时间
	CreatedAt    field.Time   // 创建时间
	UpdatedAt    field.Time   // 更新时间

	fieldMap map[string]field.Expr
}

func (c chatDialogue) Table(newTableName string) *chatDialogue {
	c.chatDialogueDo.UseTable(newTableName)
	return c.updateTableName(newTableName)
}

func (c chatDialogue) As(alias string) *chatDialogue {
	c.chatDialogueDo.DO = *(c.chatDialogueDo.As(alias).(*gen.DO))
	return c.updateTableName(alias)
}

func (c *chatDialogue) updateTableName(table string) *chatDialogue {
	c.ALL = field.NewAsterisk(table)
	c.ID = field.NewInt64(table, "id")
	c.DeviceID = field.NewString(table, "device_id")
	c.Question = field.NewString(table, "question")
	c.QuestionTime = field.NewTime(table, "question_time")
	c.Answer = field.NewString(table, "answer")
	c.AnswerTime = field.NewTime(table, "answer_time")
	c.CreatedAt = field.NewTime(table, "created_at")
	c.UpdatedAt = field.NewTime(table, "updated_at")

	c.fillFieldMap()

	return c
}

func (c *chatDialogue) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := c.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (c *chatDialogue) fillFieldMap() {
	c.fieldMap = make(map[string]field.Expr, 8)
	c.fieldMap["id"] = c.ID
	c.fieldMap["device_id"] = c.DeviceID
	c.fieldMap["question"] = c.Question
	c.fieldMap["question_time"] = c.QuestionTime
	c.fieldMap["answer"] = c.Answer
	c.fieldMap["answer_time"] = c.AnswerTime
	c.fieldMap["created_at"] = c.CreatedAt
	c.fieldMap["updated_at"] = c.UpdatedAt
}

func (c chatDialogue) clone(db *gorm.DB) chatDialogue {
	c.chatDialogueDo.ReplaceConnPool(db.Statement.ConnPool)
	return c
}

func (c chatDialogue) replaceDB(db *gorm.DB) chatDialogue {
	c.chatDialogueDo.ReplaceDB(db)
	return c
}

type chatDialogueDo struct{ gen.DO }

type IChatDialogueDo interface {
	gen.SubQuery
	Debug() IChatDialogueDo
	WithContext(ctx context.Context) IChatDialogueDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IChatDialogueDo
	WriteDB() IChatDialogueDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IChatDialogueDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IChatDialogueDo
	Not(conds ...gen.Condition) IChatDialogueDo
	Or(conds ...gen.Condition) IChatDialogueDo
	Select(conds ...field.Expr) IChatDialogueDo
	Where(conds ...gen.Condition) IChatDialogueDo
	Order(conds ...field.Expr) IChatDialogueDo
	Distinct(cols ...field.Expr) IChatDialogueDo
	Omit(cols ...field.Expr) IChatDialogueDo
	Join(table schema.Tabler, on ...field.Expr) IChatDialogueDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IChatDialogueDo
	RightJoin(table schema.Tabler, on ...field.Expr) IChatDialogueDo
	Group(cols ...field.Expr) IChatDialogueDo
	Having(conds ...gen.Condition) IChatDialogueDo
	Limit(limit int) IChatDialogueDo
	Offset(offset int) IChatDialogueDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IChatDialogueDo
	Unscoped() IChatDialogueDo
	Create(values ...*model.ChatDialogue) error
	CreateInBatches(values []*model.ChatDialogue, batchSize int) error
	Save(values ...*model.ChatDialogue) error
	First() (*model.ChatDialogue, error)
	Take() (*model.ChatDialogue, error)
	Last() (*model.ChatDialogue, error)
	Find() ([]*model.ChatDialogue, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.ChatDialogue, err error)
	FindInBatches(result *[]*model.ChatDialogue, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.ChatDialogue) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IChatDialogueDo
	Assign(attrs ...field.AssignExpr) IChatDialogueDo
	Joins(fields ...field.RelationField) IChatDialogueDo
	Preload(fields ...field.RelationField) IChatDialogueDo
	FirstOrInit() (*model.ChatDialogue, error)
	FirstOrCreate() (*model.ChatDialogue, error)
	FindByPage(offset int, limit int) (result []*model.ChatDialogue, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IChatDialogueDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (c chatDialogueDo) Debug() IChatDialogueDo {
	return c.withDO(c.DO.Debug())
}

func (c chatDialogueDo) WithContext(ctx context.Context) IChatDialogueDo {
	return c.withDO(c.DO.WithContext(ctx))
}

func (c chatDialogueDo) ReadDB() IChatDialogueDo {
	return c.Clauses(dbresolver.Read)
}

func (c chatDialogueDo) WriteDB() IChatDialogueDo {
	return c.Clauses(dbresolver.Write)
}

func (c chatDialogueDo) Session(config *gorm.Session) IChatDialogueDo {
	return c.withDO(c.DO.Session(config))
}

func (c chatDialogueDo) Clauses(conds ...clause.Expression) IChatDialogueDo {
	return c.withDO(c.DO.Clauses(conds...))
}

func (c chatDialogueDo) Returning(value interface{}, columns ...string) IChatDialogueDo {
	return c.withDO(c.DO.Returning(value, columns...))
}

func (c chatDialogueDo) Not(conds ...gen.Condition) IChatDialogueDo {
	return c.withDO(c.DO.Not(conds...))
}

func (c chatDialogueDo) Or(conds ...gen.Condition) IChatDialogueDo {
	return c.withDO(c.DO.Or(conds...))
}

func (c chatDialogueDo) Select(conds ...field.Expr) IChatDialogueDo {
	return c.withDO(c.DO.Select(conds...))
}

func (c chatDialogueDo) Where(conds ...gen.Condition) IChatDialogueDo {
	return c.withDO(c.DO.Where(conds...))
}

func (c chatDialogueDo) Order(conds ...field.Expr) IChatDialogueDo {
	return c.withDO(c.DO.Order(conds...))
}

func (c chatDialogueDo) Distinct(cols ...field.Expr) IChatDialogueDo {
	return c.withDO(c.DO.Distinct(cols...))
}

func (c chatDialogueDo) Omit(cols ...field.Expr) IChatDialogueDo {
	return c.withDO(c.DO.Omit(cols...))
}

func (c chatDialogueDo) Join(table schema.Tabler, on ...field.Expr) IChatDialogueDo {
	return c.withDO(c.DO.Join(table, on...))
}

func (c chatDialogueDo) LeftJoin(table schema.Tabler, on ...field.Expr) IChatDialogueDo {
	return c.withDO(c.DO.LeftJoin(table, on...))
}

func (c chatDialogueDo) RightJoin(table schema.Tabler, on ...field.Expr) IChatDialogueDo {
	return c.withDO(c.DO.RightJoin(table, on...))
}

func (c chatDialogueDo) Group(cols ...field.Expr) IChatDialogueDo {
	return c.withDO(c.DO.Group(cols...))
}

func (c chatDialogueDo) Having(conds ...gen.Condition) IChatDialogueDo {
	return c.withDO(c.DO.Having(conds...))
}

func (c chatDialogueDo) Limit(limit int) IChatDialogueDo {
	return c.withDO(c.DO.Limit(limit))
}

func (c chatDialogueDo) Offset(offset int) IChatDialogueDo {
	return c.withDO(c.DO.Offset(offset))
}

func (c chatDialogueDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IChatDialogueDo {
	return c.withDO(c.DO.Scopes(funcs...))
}

func (c chatDialogueDo) Unscoped() IChatDialogueDo {
	return c.withDO(c.DO.Unscoped())
}

func (c chatDialogueDo) Create(values ...*model.ChatDialogue) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Create(values)
}

func (c chatDialogueDo) CreateInBatches(values []*model.ChatDialogue, batchSize int) error {
	return c.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (c chatDialogueDo) Save(values ...*model.ChatDialogue) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Save(values)
}

func (c chatDialogueDo) First() (*model.ChatDialogue, error) {
	if result, err := c.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.ChatDialogue), nil
	}
}

func (c chatDialogueDo) Take() (*model.ChatDialogue, error) {
	if result, err := c.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.ChatDialogue), nil
	}
}

func (c chatDialogueDo) Last() (*model.ChatDialogue, error) {
	if result, err := c.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.ChatDialogue), nil
	}
}

func (c chatDialogueDo) Find() ([]*model.ChatDialogue, error) {
	result, err := c.DO.Find()
	return result.([]*model.ChatDialogue), err
}

func (c chatDialogueDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.ChatDialogue, err error) {
	buf := make([]*model.ChatDialogue, 0, batchSize)
	err = c.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (c chatDialogueDo) FindInBatches(result *[]*model.ChatDialogue, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return c.DO.FindInBatches(result, batchSize, fc)
}

func (c chatDialogueDo) Attrs(attrs ...field.AssignExpr) IChatDialogueDo {
	return c.withDO(c.DO.Attrs(attrs...))
}

func (c chatDialogueDo) Assign(attrs ...field.AssignExpr) IChatDialogueDo {
	return c.withDO(c.DO.Assign(attrs...))
}

func (c chatDialogueDo) Joins(fields ...field.RelationField) IChatDialogueDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Joins(_f))
	}
	return &c
}

func (c chatDialogueDo) Preload(fields ...field.RelationField) IChatDialogueDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Preload(_f))
	}
	return &c
}

func (c chatDialogueDo) FirstOrInit() (*model.ChatDialogue, error) {
	if result, err := c.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.ChatDialogue), nil
	}
}

func (c chatDialogueDo) FirstOrCreate() (*model.ChatDialogue, error) {
	if result, err := c.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.ChatDialogue), nil
	}
}

func (c chatDialogueDo) FindByPage(offset int, limit int) (result []*model.ChatDialogue, count int64, err error) {
	result, err = c.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = c.Offset(-1).Limit(-1).Count()
	return
}

func (c chatDialogueDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = c.Count()
	if err != nil {
		return
	}

	err = c.Offset(offset).Limit(limit).Scan(result)
	return
}

func (c chatDialogueDo) Scan(result interface{}) (err error) {
	return c.DO.Scan(result)
}

func (c chatDialogueDo) Delete(models ...*model.ChatDialogue) (result gen.ResultInfo, err error) {
	return c.DO.Delete(models)
}

func (c *chatDialogueDo) withDO(do gen.Dao) *chatDialogueDo {
	c.DO = *do.(*gen.DO)
	return c
}
