// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"aibuddy/internal/model"
)

func newAnniversaryReminder(db *gorm.DB, opts ...gen.DOOption) anniversaryReminder {
	_anniversaryReminder := anniversaryReminder{}

	_anniversaryReminder.anniversaryReminderDo.UseDB(db, opts...)
	_anniversaryReminder.anniversaryReminderDo.UseModel(&model.AnniversaryReminder{})

	tableName := _anniversaryReminder.anniversaryReminderDo.TableName()
	_anniversaryReminder.ALL = field.NewAsterisk(tableName)
	_anniversaryReminder.ID = field.NewInt64(tableName, "id")
	_anniversaryReminder.AnniversaryType = field.NewString(tableName, "anniversary_type")
	_anniversaryReminder.ReminderUsername = field.NewString(tableName, "reminder_username")
	_anniversaryReminder.ReminderUserSex = field.NewString(tableName, "reminder_user_sex")
	_anniversaryReminder.AnniversaryTime = field.NewTime(tableName, "anniversary_time")
	_anniversaryReminder.ReminderWay = field.NewString(tableName, "reminder_way")
	_anniversaryReminder.Remarks = field.NewString(tableName, "remarks")
	_anniversaryReminder.CreatedAt = field.NewTime(tableName, "created_at")
	_anniversaryReminder.UpdatedAt = field.NewTime(tableName, "updated_at")

	_anniversaryReminder.fillFieldMap()

	return _anniversaryReminder
}

type anniversaryReminder struct {
	anniversaryReminderDo

	ALL              field.Asterisk
	ID               field.Int64
	AnniversaryType  field.String // 纪念日类型
	ReminderUsername field.String // 提醒人用户名
	ReminderUserSex  field.String // 提醒人性别
	AnniversaryTime  field.Time   // 纪念日时间
	ReminderWay      field.String // 提醒方式
	Remarks          field.String // 备注
	CreatedAt        field.Time   // 创建时间
	UpdatedAt        field.Time   // 更新时间

	fieldMap map[string]field.Expr
}

func (a anniversaryReminder) Table(newTableName string) *anniversaryReminder {
	a.anniversaryReminderDo.UseTable(newTableName)
	return a.updateTableName(newTableName)
}

func (a anniversaryReminder) As(alias string) *anniversaryReminder {
	a.anniversaryReminderDo.DO = *(a.anniversaryReminderDo.As(alias).(*gen.DO))
	return a.updateTableName(alias)
}

func (a *anniversaryReminder) updateTableName(table string) *anniversaryReminder {
	a.ALL = field.NewAsterisk(table)
	a.ID = field.NewInt64(table, "id")
	a.AnniversaryType = field.NewString(table, "anniversary_type")
	a.ReminderUsername = field.NewString(table, "reminder_username")
	a.ReminderUserSex = field.NewString(table, "reminder_user_sex")
	a.AnniversaryTime = field.NewTime(table, "anniversary_time")
	a.ReminderWay = field.NewString(table, "reminder_way")
	a.Remarks = field.NewString(table, "remarks")
	a.CreatedAt = field.NewTime(table, "created_at")
	a.UpdatedAt = field.NewTime(table, "updated_at")

	a.fillFieldMap()

	return a
}

func (a *anniversaryReminder) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := a.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (a *anniversaryReminder) fillFieldMap() {
	a.fieldMap = make(map[string]field.Expr, 9)
	a.fieldMap["id"] = a.ID
	a.fieldMap["anniversary_type"] = a.AnniversaryType
	a.fieldMap["reminder_username"] = a.ReminderUsername
	a.fieldMap["reminder_user_sex"] = a.ReminderUserSex
	a.fieldMap["anniversary_time"] = a.AnniversaryTime
	a.fieldMap["reminder_way"] = a.ReminderWay
	a.fieldMap["remarks"] = a.Remarks
	a.fieldMap["created_at"] = a.CreatedAt
	a.fieldMap["updated_at"] = a.UpdatedAt
}

func (a anniversaryReminder) clone(db *gorm.DB) anniversaryReminder {
	a.anniversaryReminderDo.ReplaceConnPool(db.Statement.ConnPool)
	return a
}

func (a anniversaryReminder) replaceDB(db *gorm.DB) anniversaryReminder {
	a.anniversaryReminderDo.ReplaceDB(db)
	return a
}

type anniversaryReminderDo struct{ gen.DO }

type IAnniversaryReminderDo interface {
	gen.SubQuery
	Debug() IAnniversaryReminderDo
	WithContext(ctx context.Context) IAnniversaryReminderDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IAnniversaryReminderDo
	WriteDB() IAnniversaryReminderDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IAnniversaryReminderDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IAnniversaryReminderDo
	Not(conds ...gen.Condition) IAnniversaryReminderDo
	Or(conds ...gen.Condition) IAnniversaryReminderDo
	Select(conds ...field.Expr) IAnniversaryReminderDo
	Where(conds ...gen.Condition) IAnniversaryReminderDo
	Order(conds ...field.Expr) IAnniversaryReminderDo
	Distinct(cols ...field.Expr) IAnniversaryReminderDo
	Omit(cols ...field.Expr) IAnniversaryReminderDo
	Join(table schema.Tabler, on ...field.Expr) IAnniversaryReminderDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IAnniversaryReminderDo
	RightJoin(table schema.Tabler, on ...field.Expr) IAnniversaryReminderDo
	Group(cols ...field.Expr) IAnniversaryReminderDo
	Having(conds ...gen.Condition) IAnniversaryReminderDo
	Limit(limit int) IAnniversaryReminderDo
	Offset(offset int) IAnniversaryReminderDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IAnniversaryReminderDo
	Unscoped() IAnniversaryReminderDo
	Create(values ...*model.AnniversaryReminder) error
	CreateInBatches(values []*model.AnniversaryReminder, batchSize int) error
	Save(values ...*model.AnniversaryReminder) error
	First() (*model.AnniversaryReminder, error)
	Take() (*model.AnniversaryReminder, error)
	Last() (*model.AnniversaryReminder, error)
	Find() ([]*model.AnniversaryReminder, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.AnniversaryReminder, err error)
	FindInBatches(result *[]*model.AnniversaryReminder, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.AnniversaryReminder) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IAnniversaryReminderDo
	Assign(attrs ...field.AssignExpr) IAnniversaryReminderDo
	Joins(fields ...field.RelationField) IAnniversaryReminderDo
	Preload(fields ...field.RelationField) IAnniversaryReminderDo
	FirstOrInit() (*model.AnniversaryReminder, error)
	FirstOrCreate() (*model.AnniversaryReminder, error)
	FindByPage(offset int, limit int) (result []*model.AnniversaryReminder, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IAnniversaryReminderDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (a anniversaryReminderDo) Debug() IAnniversaryReminderDo {
	return a.withDO(a.DO.Debug())
}

func (a anniversaryReminderDo) WithContext(ctx context.Context) IAnniversaryReminderDo {
	return a.withDO(a.DO.WithContext(ctx))
}

func (a anniversaryReminderDo) ReadDB() IAnniversaryReminderDo {
	return a.Clauses(dbresolver.Read)
}

func (a anniversaryReminderDo) WriteDB() IAnniversaryReminderDo {
	return a.Clauses(dbresolver.Write)
}

func (a anniversaryReminderDo) Session(config *gorm.Session) IAnniversaryReminderDo {
	return a.withDO(a.DO.Session(config))
}

func (a anniversaryReminderDo) Clauses(conds ...clause.Expression) IAnniversaryReminderDo {
	return a.withDO(a.DO.Clauses(conds...))
}

func (a anniversaryReminderDo) Returning(value interface{}, columns ...string) IAnniversaryReminderDo {
	return a.withDO(a.DO.Returning(value, columns...))
}

func (a anniversaryReminderDo) Not(conds ...gen.Condition) IAnniversaryReminderDo {
	return a.withDO(a.DO.Not(conds...))
}

func (a anniversaryReminderDo) Or(conds ...gen.Condition) IAnniversaryReminderDo {
	return a.withDO(a.DO.Or(conds...))
}

func (a anniversaryReminderDo) Select(conds ...field.Expr) IAnniversaryReminderDo {
	return a.withDO(a.DO.Select(conds...))
}

func (a anniversaryReminderDo) Where(conds ...gen.Condition) IAnniversaryReminderDo {
	return a.withDO(a.DO.Where(conds...))
}

func (a anniversaryReminderDo) Order(conds ...field.Expr) IAnniversaryReminderDo {
	return a.withDO(a.DO.Order(conds...))
}

func (a anniversaryReminderDo) Distinct(cols ...field.Expr) IAnniversaryReminderDo {
	return a.withDO(a.DO.Distinct(cols...))
}

func (a anniversaryReminderDo) Omit(cols ...field.Expr) IAnniversaryReminderDo {
	return a.withDO(a.DO.Omit(cols...))
}

func (a anniversaryReminderDo) Join(table schema.Tabler, on ...field.Expr) IAnniversaryReminderDo {
	return a.withDO(a.DO.Join(table, on...))
}

func (a anniversaryReminderDo) LeftJoin(table schema.Tabler, on ...field.Expr) IAnniversaryReminderDo {
	return a.withDO(a.DO.LeftJoin(table, on...))
}

func (a anniversaryReminderDo) RightJoin(table schema.Tabler, on ...field.Expr) IAnniversaryReminderDo {
	return a.withDO(a.DO.RightJoin(table, on...))
}

func (a anniversaryReminderDo) Group(cols ...field.Expr) IAnniversaryReminderDo {
	return a.withDO(a.DO.Group(cols...))
}

func (a anniversaryReminderDo) Having(conds ...gen.Condition) IAnniversaryReminderDo {
	return a.withDO(a.DO.Having(conds...))
}

func (a anniversaryReminderDo) Limit(limit int) IAnniversaryReminderDo {
	return a.withDO(a.DO.Limit(limit))
}

func (a anniversaryReminderDo) Offset(offset int) IAnniversaryReminderDo {
	return a.withDO(a.DO.Offset(offset))
}

func (a anniversaryReminderDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IAnniversaryReminderDo {
	return a.withDO(a.DO.Scopes(funcs...))
}

func (a anniversaryReminderDo) Unscoped() IAnniversaryReminderDo {
	return a.withDO(a.DO.Unscoped())
}

func (a anniversaryReminderDo) Create(values ...*model.AnniversaryReminder) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Create(values)
}

func (a anniversaryReminderDo) CreateInBatches(values []*model.AnniversaryReminder, batchSize int) error {
	return a.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (a anniversaryReminderDo) Save(values ...*model.AnniversaryReminder) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Save(values)
}

func (a anniversaryReminderDo) First() (*model.AnniversaryReminder, error) {
	if result, err := a.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.AnniversaryReminder), nil
	}
}

func (a anniversaryReminderDo) Take() (*model.AnniversaryReminder, error) {
	if result, err := a.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.AnniversaryReminder), nil
	}
}

func (a anniversaryReminderDo) Last() (*model.AnniversaryReminder, error) {
	if result, err := a.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.AnniversaryReminder), nil
	}
}

func (a anniversaryReminderDo) Find() ([]*model.AnniversaryReminder, error) {
	result, err := a.DO.Find()
	return result.([]*model.AnniversaryReminder), err
}

func (a anniversaryReminderDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.AnniversaryReminder, err error) {
	buf := make([]*model.AnniversaryReminder, 0, batchSize)
	err = a.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (a anniversaryReminderDo) FindInBatches(result *[]*model.AnniversaryReminder, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return a.DO.FindInBatches(result, batchSize, fc)
}

func (a anniversaryReminderDo) Attrs(attrs ...field.AssignExpr) IAnniversaryReminderDo {
	return a.withDO(a.DO.Attrs(attrs...))
}

func (a anniversaryReminderDo) Assign(attrs ...field.AssignExpr) IAnniversaryReminderDo {
	return a.withDO(a.DO.Assign(attrs...))
}

func (a anniversaryReminderDo) Joins(fields ...field.RelationField) IAnniversaryReminderDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Joins(_f))
	}
	return &a
}

func (a anniversaryReminderDo) Preload(fields ...field.RelationField) IAnniversaryReminderDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Preload(_f))
	}
	return &a
}

func (a anniversaryReminderDo) FirstOrInit() (*model.AnniversaryReminder, error) {
	if result, err := a.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.AnniversaryReminder), nil
	}
}

func (a anniversaryReminderDo) FirstOrCreate() (*model.AnniversaryReminder, error) {
	if result, err := a.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.AnniversaryReminder), nil
	}
}

func (a anniversaryReminderDo) FindByPage(offset int, limit int) (result []*model.AnniversaryReminder, count int64, err error) {
	result, err = a.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = a.Offset(-1).Limit(-1).Count()
	return
}

func (a anniversaryReminderDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = a.Count()
	if err != nil {
		return
	}

	err = a.Offset(offset).Limit(limit).Scan(result)
	return
}

func (a anniversaryReminderDo) Scan(result interface{}) (err error) {
	return a.DO.Scan(result)
}

func (a anniversaryReminderDo) Delete(models ...*model.AnniversaryReminder) (result gen.ResultInfo, err error) {
	return a.DO.Delete(models)
}

func (a *anniversaryReminderDo) withDO(do gen.Dao) *anniversaryReminderDo {
	a.DO = *do.(*gen.DO)
	return a
}
