// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"aibuddy/internal/model"
)

func newReminder(db *gorm.DB, opts ...gen.DOOption) reminder {
	_reminder := reminder{}

	_reminder.reminderDo.UseDB(db, opts...)
	_reminder.reminderDo.UseModel(&model.Reminder{})

	tableName := _reminder.reminderDo.TableName()
	_reminder.ALL = field.NewAsterisk(tableName)
	_reminder.Id = field.NewInt64(tableName, "id")
	_reminder.ReminderType = field.NewString(tableName, "reminder_type")
	_reminder.ReminderTime = field.NewTime(tableName, "reminder_time")
	_reminder.ReminderContent = field.NewString(tableName, "reminder_content")
	_reminder.DeviceId = field.NewString(tableName, "device_id")
	_reminder.CronExpression = field.NewString(tableName, "cron_expression")
	_reminder.Status = field.NewString(tableName, "status")
	_reminder.ReminderDeviceId = field.NewInt64(tableName, "reminder_device_id")
	_reminder.CreatedAt = field.NewTime(tableName, "created_at")
	_reminder.UpdatedAt = field.NewTime(tableName, "updated_at")
	_reminder.Device = reminderHasOneDevice{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("Device", "model.Device"),
		Agent: struct {
			field.RelationField
		}{
			RelationField: field.NewRelation("Device.Agent", "model.Agent"),
		},
		User: struct {
			field.RelationField
			Device struct {
				field.RelationField
			}
		}{
			RelationField: field.NewRelation("Device.User", "model.User"),
			Device: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("Device.User.Device", "model.Device"),
			},
		},
	}

	_reminder.fillFieldMap()

	return _reminder
}

type reminder struct {
	reminderDo

	ALL              field.Asterisk
	Id               field.Int64
	ReminderType     field.String // 提醒类型
	ReminderTime     field.Time   // 提醒时间
	ReminderContent  field.String // 提醒内容
	DeviceId         field.String // 设备ID
	CronExpression   field.String // cron表达式
	Status           field.String
	ReminderDeviceId field.Int64 // 提醒设备ID
	CreatedAt        field.Time  // 创建时间
	UpdatedAt        field.Time  // 更新时间
	Device           reminderHasOneDevice

	fieldMap map[string]field.Expr
}

func (r reminder) Table(newTableName string) *reminder {
	r.reminderDo.UseTable(newTableName)
	return r.updateTableName(newTableName)
}

func (r reminder) As(alias string) *reminder {
	r.reminderDo.DO = *(r.reminderDo.As(alias).(*gen.DO))
	return r.updateTableName(alias)
}

func (r *reminder) updateTableName(table string) *reminder {
	r.ALL = field.NewAsterisk(table)
	r.Id = field.NewInt64(table, "id")
	r.ReminderType = field.NewString(table, "reminder_type")
	r.ReminderTime = field.NewTime(table, "reminder_time")
	r.ReminderContent = field.NewString(table, "reminder_content")
	r.DeviceId = field.NewString(table, "device_id")
	r.CronExpression = field.NewString(table, "cron_expression")
	r.Status = field.NewString(table, "status")
	r.ReminderDeviceId = field.NewInt64(table, "reminder_device_id")
	r.CreatedAt = field.NewTime(table, "created_at")
	r.UpdatedAt = field.NewTime(table, "updated_at")

	r.fillFieldMap()

	return r
}

func (r *reminder) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := r.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (r *reminder) fillFieldMap() {
	r.fieldMap = make(map[string]field.Expr, 11)
	r.fieldMap["id"] = r.Id
	r.fieldMap["reminder_type"] = r.ReminderType
	r.fieldMap["reminder_time"] = r.ReminderTime
	r.fieldMap["reminder_content"] = r.ReminderContent
	r.fieldMap["device_id"] = r.DeviceId
	r.fieldMap["cron_expression"] = r.CronExpression
	r.fieldMap["status"] = r.Status
	r.fieldMap["reminder_device_id"] = r.ReminderDeviceId
	r.fieldMap["created_at"] = r.CreatedAt
	r.fieldMap["updated_at"] = r.UpdatedAt

}

func (r reminder) clone(db *gorm.DB) reminder {
	r.reminderDo.ReplaceConnPool(db.Statement.ConnPool)
	r.Device.db = db.Session(&gorm.Session{Initialized: true})
	r.Device.db.Statement.ConnPool = db.Statement.ConnPool
	return r
}

func (r reminder) replaceDB(db *gorm.DB) reminder {
	r.reminderDo.ReplaceDB(db)
	r.Device.db = db.Session(&gorm.Session{})
	return r
}

type reminderHasOneDevice struct {
	db *gorm.DB

	field.RelationField

	Agent struct {
		field.RelationField
	}
	User struct {
		field.RelationField
		Device struct {
			field.RelationField
		}
	}
}

func (a reminderHasOneDevice) Where(conds ...field.Expr) *reminderHasOneDevice {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a reminderHasOneDevice) WithContext(ctx context.Context) *reminderHasOneDevice {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a reminderHasOneDevice) Session(session *gorm.Session) *reminderHasOneDevice {
	a.db = a.db.Session(session)
	return &a
}

func (a reminderHasOneDevice) Model(m *model.Reminder) *reminderHasOneDeviceTx {
	return &reminderHasOneDeviceTx{a.db.Model(m).Association(a.Name())}
}

func (a reminderHasOneDevice) Unscoped() *reminderHasOneDevice {
	a.db = a.db.Unscoped()
	return &a
}

type reminderHasOneDeviceTx struct{ tx *gorm.Association }

func (a reminderHasOneDeviceTx) Find() (result *model.Device, err error) {
	return result, a.tx.Find(&result)
}

func (a reminderHasOneDeviceTx) Append(values ...*model.Device) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a reminderHasOneDeviceTx) Replace(values ...*model.Device) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a reminderHasOneDeviceTx) Delete(values ...*model.Device) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a reminderHasOneDeviceTx) Clear() error {
	return a.tx.Clear()
}

func (a reminderHasOneDeviceTx) Count() int64 {
	return a.tx.Count()
}

func (a reminderHasOneDeviceTx) Unscoped() *reminderHasOneDeviceTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type reminderDo struct{ gen.DO }

type IReminderDo interface {
	gen.SubQuery
	Debug() IReminderDo
	WithContext(ctx context.Context) IReminderDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IReminderDo
	WriteDB() IReminderDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IReminderDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IReminderDo
	Not(conds ...gen.Condition) IReminderDo
	Or(conds ...gen.Condition) IReminderDo
	Select(conds ...field.Expr) IReminderDo
	Where(conds ...gen.Condition) IReminderDo
	Order(conds ...field.Expr) IReminderDo
	Distinct(cols ...field.Expr) IReminderDo
	Omit(cols ...field.Expr) IReminderDo
	Join(table schema.Tabler, on ...field.Expr) IReminderDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IReminderDo
	RightJoin(table schema.Tabler, on ...field.Expr) IReminderDo
	Group(cols ...field.Expr) IReminderDo
	Having(conds ...gen.Condition) IReminderDo
	Limit(limit int) IReminderDo
	Offset(offset int) IReminderDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IReminderDo
	Unscoped() IReminderDo
	Create(values ...*model.Reminder) error
	CreateInBatches(values []*model.Reminder, batchSize int) error
	Save(values ...*model.Reminder) error
	First() (*model.Reminder, error)
	Take() (*model.Reminder, error)
	Last() (*model.Reminder, error)
	Find() ([]*model.Reminder, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Reminder, err error)
	FindInBatches(result *[]*model.Reminder, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.Reminder) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IReminderDo
	Assign(attrs ...field.AssignExpr) IReminderDo
	Joins(fields ...field.RelationField) IReminderDo
	Preload(fields ...field.RelationField) IReminderDo
	FirstOrInit() (*model.Reminder, error)
	FirstOrCreate() (*model.Reminder, error)
	FindByPage(offset int, limit int) (result []*model.Reminder, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IReminderDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (r reminderDo) Debug() IReminderDo {
	return r.withDO(r.DO.Debug())
}

func (r reminderDo) WithContext(ctx context.Context) IReminderDo {
	return r.withDO(r.DO.WithContext(ctx))
}

func (r reminderDo) ReadDB() IReminderDo {
	return r.Clauses(dbresolver.Read)
}

func (r reminderDo) WriteDB() IReminderDo {
	return r.Clauses(dbresolver.Write)
}

func (r reminderDo) Session(config *gorm.Session) IReminderDo {
	return r.withDO(r.DO.Session(config))
}

func (r reminderDo) Clauses(conds ...clause.Expression) IReminderDo {
	return r.withDO(r.DO.Clauses(conds...))
}

func (r reminderDo) Returning(value interface{}, columns ...string) IReminderDo {
	return r.withDO(r.DO.Returning(value, columns...))
}

func (r reminderDo) Not(conds ...gen.Condition) IReminderDo {
	return r.withDO(r.DO.Not(conds...))
}

func (r reminderDo) Or(conds ...gen.Condition) IReminderDo {
	return r.withDO(r.DO.Or(conds...))
}

func (r reminderDo) Select(conds ...field.Expr) IReminderDo {
	return r.withDO(r.DO.Select(conds...))
}

func (r reminderDo) Where(conds ...gen.Condition) IReminderDo {
	return r.withDO(r.DO.Where(conds...))
}

func (r reminderDo) Order(conds ...field.Expr) IReminderDo {
	return r.withDO(r.DO.Order(conds...))
}

func (r reminderDo) Distinct(cols ...field.Expr) IReminderDo {
	return r.withDO(r.DO.Distinct(cols...))
}

func (r reminderDo) Omit(cols ...field.Expr) IReminderDo {
	return r.withDO(r.DO.Omit(cols...))
}

func (r reminderDo) Join(table schema.Tabler, on ...field.Expr) IReminderDo {
	return r.withDO(r.DO.Join(table, on...))
}

func (r reminderDo) LeftJoin(table schema.Tabler, on ...field.Expr) IReminderDo {
	return r.withDO(r.DO.LeftJoin(table, on...))
}

func (r reminderDo) RightJoin(table schema.Tabler, on ...field.Expr) IReminderDo {
	return r.withDO(r.DO.RightJoin(table, on...))
}

func (r reminderDo) Group(cols ...field.Expr) IReminderDo {
	return r.withDO(r.DO.Group(cols...))
}

func (r reminderDo) Having(conds ...gen.Condition) IReminderDo {
	return r.withDO(r.DO.Having(conds...))
}

func (r reminderDo) Limit(limit int) IReminderDo {
	return r.withDO(r.DO.Limit(limit))
}

func (r reminderDo) Offset(offset int) IReminderDo {
	return r.withDO(r.DO.Offset(offset))
}

func (r reminderDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IReminderDo {
	return r.withDO(r.DO.Scopes(funcs...))
}

func (r reminderDo) Unscoped() IReminderDo {
	return r.withDO(r.DO.Unscoped())
}

func (r reminderDo) Create(values ...*model.Reminder) error {
	if len(values) == 0 {
		return nil
	}
	return r.DO.Create(values)
}

func (r reminderDo) CreateInBatches(values []*model.Reminder, batchSize int) error {
	return r.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (r reminderDo) Save(values ...*model.Reminder) error {
	if len(values) == 0 {
		return nil
	}
	return r.DO.Save(values)
}

func (r reminderDo) First() (*model.Reminder, error) {
	if result, err := r.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.Reminder), nil
	}
}

func (r reminderDo) Take() (*model.Reminder, error) {
	if result, err := r.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.Reminder), nil
	}
}

func (r reminderDo) Last() (*model.Reminder, error) {
	if result, err := r.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.Reminder), nil
	}
}

func (r reminderDo) Find() ([]*model.Reminder, error) {
	result, err := r.DO.Find()
	return result.([]*model.Reminder), err
}

func (r reminderDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Reminder, err error) {
	buf := make([]*model.Reminder, 0, batchSize)
	err = r.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (r reminderDo) FindInBatches(result *[]*model.Reminder, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return r.DO.FindInBatches(result, batchSize, fc)
}

func (r reminderDo) Attrs(attrs ...field.AssignExpr) IReminderDo {
	return r.withDO(r.DO.Attrs(attrs...))
}

func (r reminderDo) Assign(attrs ...field.AssignExpr) IReminderDo {
	return r.withDO(r.DO.Assign(attrs...))
}

func (r reminderDo) Joins(fields ...field.RelationField) IReminderDo {
	for _, _f := range fields {
		r = *r.withDO(r.DO.Joins(_f))
	}
	return &r
}

func (r reminderDo) Preload(fields ...field.RelationField) IReminderDo {
	for _, _f := range fields {
		r = *r.withDO(r.DO.Preload(_f))
	}
	return &r
}

func (r reminderDo) FirstOrInit() (*model.Reminder, error) {
	if result, err := r.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.Reminder), nil
	}
}

func (r reminderDo) FirstOrCreate() (*model.Reminder, error) {
	if result, err := r.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.Reminder), nil
	}
}

func (r reminderDo) FindByPage(offset int, limit int) (result []*model.Reminder, count int64, err error) {
	result, err = r.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = r.Offset(-1).Limit(-1).Count()
	return
}

func (r reminderDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = r.Count()
	if err != nil {
		return
	}

	err = r.Offset(offset).Limit(limit).Scan(result)
	return
}

func (r reminderDo) Scan(result interface{}) (err error) {
	return r.DO.Scan(result)
}

func (r reminderDo) Delete(models ...*model.Reminder) (result gen.ResultInfo, err error) {
	return r.DO.Delete(models)
}

func (r *reminderDo) withDO(do gen.Dao) *reminderDo {
	r.DO = *do.(*gen.DO)
	return r
}
