// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"aibuddy/internal/model"
)

func newGrowthReport(db *gorm.DB, opts ...gen.DOOption) growthReport {
	_growthReport := growthReport{}

	_growthReport.growthReportDo.UseDB(db, opts...)
	_growthReport.growthReportDo.UseModel(&model.GrowthReport{})

	tableName := _growthReport.growthReportDo.TableName()
	_growthReport.ALL = field.NewAsterisk(tableName)
	_growthReport.ID = field.NewInt64(tableName, "id")
	_growthReport.DeviceID = field.NewString(tableName, "device_id")
	_growthReport.StartTime = field.NewTime(tableName, "start_time")
	_growthReport.EndTime = field.NewTime(tableName, "end_time")
	_growthReport.SummaryText = field.NewString(tableName, "summary_text")
	_growthReport.StatusCards = field.NewField(tableName, "status_cards")
	_growthReport.InteractionSummary = field.NewField(tableName, "interaction_summary")
	_growthReport.SocialSummary = field.NewField(tableName, "social_summary")
	_growthReport.MemoryCapsuleSummary = field.NewField(tableName, "memory_capsule_summary")
	_growthReport.ChildPortrait = field.NewField(tableName, "child_portrait")
	_growthReport.KeyMoments = field.NewField(tableName, "key_moments")
	_growthReport.EmotionTrend = field.NewField(tableName, "emotion_trend")
	_growthReport.AudioSummary = field.NewField(tableName, "audio_summary")
	_growthReport.PomodoroSummary = field.NewField(tableName, "pomodoro_summary")
	_growthReport.SafetyAlert = field.NewField(tableName, "safety_alert")
	_growthReport.NextWeekSuggestions = field.NewField(tableName, "next_week_suggestions")
	_growthReport.ParentScripts = field.NewField(tableName, "parent_scripts")
	_growthReport.ClosingText = field.NewString(tableName, "closing_text")
	_growthReport.CreatedAt = field.NewTime(tableName, "created_at")
	_growthReport.UpdatedAt = field.NewTime(tableName, "updated_at")

	_growthReport.fillFieldMap()

	return _growthReport
}

type growthReport struct {
	growthReportDo

	ALL                  field.Asterisk
	ID                   field.Int64
	DeviceID             field.String
	StartTime            field.Time
	EndTime              field.Time
	SummaryText          field.String
	StatusCards          field.Field
	InteractionSummary   field.Field
	SocialSummary        field.Field
	MemoryCapsuleSummary field.Field
	ChildPortrait        field.Field
	KeyMoments           field.Field
	EmotionTrend         field.Field
	AudioSummary         field.Field
	PomodoroSummary      field.Field
	SafetyAlert          field.Field
	NextWeekSuggestions  field.Field
	ParentScripts        field.Field
	ClosingText          field.String
	CreatedAt            field.Time
	UpdatedAt            field.Time

	fieldMap map[string]field.Expr
}

func (g growthReport) Table(newTableName string) *growthReport {
	g.growthReportDo.UseTable(newTableName)
	return g.updateTableName(newTableName)
}

func (g growthReport) As(alias string) *growthReport {
	g.growthReportDo.DO = *(g.growthReportDo.As(alias).(*gen.DO))
	return g.updateTableName(alias)
}

func (g *growthReport) updateTableName(table string) *growthReport {
	g.ALL = field.NewAsterisk(table)
	g.ID = field.NewInt64(table, "id")
	g.DeviceID = field.NewString(table, "device_id")
	g.StartTime = field.NewTime(table, "start_time")
	g.EndTime = field.NewTime(table, "end_time")
	g.SummaryText = field.NewString(table, "summary_text")
	g.StatusCards = field.NewField(table, "status_cards")
	g.InteractionSummary = field.NewField(table, "interaction_summary")
	g.SocialSummary = field.NewField(table, "social_summary")
	g.MemoryCapsuleSummary = field.NewField(table, "memory_capsule_summary")
	g.ChildPortrait = field.NewField(table, "child_portrait")
	g.KeyMoments = field.NewField(table, "key_moments")
	g.EmotionTrend = field.NewField(table, "emotion_trend")
	g.AudioSummary = field.NewField(table, "audio_summary")
	g.PomodoroSummary = field.NewField(table, "pomodoro_summary")
	g.SafetyAlert = field.NewField(table, "safety_alert")
	g.NextWeekSuggestions = field.NewField(table, "next_week_suggestions")
	g.ParentScripts = field.NewField(table, "parent_scripts")
	g.ClosingText = field.NewString(table, "closing_text")
	g.CreatedAt = field.NewTime(table, "created_at")
	g.UpdatedAt = field.NewTime(table, "updated_at")

	g.fillFieldMap()

	return g
}

func (g *growthReport) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := g.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (g *growthReport) fillFieldMap() {
	g.fieldMap = make(map[string]field.Expr, 20)
	g.fieldMap["id"] = g.ID
	g.fieldMap["device_id"] = g.DeviceID
	g.fieldMap["start_time"] = g.StartTime
	g.fieldMap["end_time"] = g.EndTime
	g.fieldMap["summary_text"] = g.SummaryText
	g.fieldMap["status_cards"] = g.StatusCards
	g.fieldMap["interaction_summary"] = g.InteractionSummary
	g.fieldMap["social_summary"] = g.SocialSummary
	g.fieldMap["memory_capsule_summary"] = g.MemoryCapsuleSummary
	g.fieldMap["child_portrait"] = g.ChildPortrait
	g.fieldMap["key_moments"] = g.KeyMoments
	g.fieldMap["emotion_trend"] = g.EmotionTrend
	g.fieldMap["audio_summary"] = g.AudioSummary
	g.fieldMap["pomodoro_summary"] = g.PomodoroSummary
	g.fieldMap["safety_alert"] = g.SafetyAlert
	g.fieldMap["next_week_suggestions"] = g.NextWeekSuggestions
	g.fieldMap["parent_scripts"] = g.ParentScripts
	g.fieldMap["closing_text"] = g.ClosingText
	g.fieldMap["created_at"] = g.CreatedAt
	g.fieldMap["updated_at"] = g.UpdatedAt
}

func (g growthReport) clone(db *gorm.DB) growthReport {
	g.growthReportDo.ReplaceConnPool(db.Statement.ConnPool)
	return g
}

func (g growthReport) replaceDB(db *gorm.DB) growthReport {
	g.growthReportDo.ReplaceDB(db)
	return g
}

type growthReportDo struct{ gen.DO }

type IGrowthReportDo interface {
	gen.SubQuery
	Debug() IGrowthReportDo
	WithContext(ctx context.Context) IGrowthReportDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IGrowthReportDo
	WriteDB() IGrowthReportDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IGrowthReportDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IGrowthReportDo
	Not(conds ...gen.Condition) IGrowthReportDo
	Or(conds ...gen.Condition) IGrowthReportDo
	Select(conds ...field.Expr) IGrowthReportDo
	Where(conds ...gen.Condition) IGrowthReportDo
	Order(conds ...field.Expr) IGrowthReportDo
	Distinct(cols ...field.Expr) IGrowthReportDo
	Omit(cols ...field.Expr) IGrowthReportDo
	Join(table schema.Tabler, on ...field.Expr) IGrowthReportDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IGrowthReportDo
	RightJoin(table schema.Tabler, on ...field.Expr) IGrowthReportDo
	Group(cols ...field.Expr) IGrowthReportDo
	Having(conds ...gen.Condition) IGrowthReportDo
	Limit(limit int) IGrowthReportDo
	Offset(offset int) IGrowthReportDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IGrowthReportDo
	Unscoped() IGrowthReportDo
	Create(values ...*model.GrowthReport) error
	CreateInBatches(values []*model.GrowthReport, batchSize int) error
	Save(values ...*model.GrowthReport) error
	First() (*model.GrowthReport, error)
	Take() (*model.GrowthReport, error)
	Last() (*model.GrowthReport, error)
	Find() ([]*model.GrowthReport, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.GrowthReport, err error)
	FindInBatches(result *[]*model.GrowthReport, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.GrowthReport) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IGrowthReportDo
	Assign(attrs ...field.AssignExpr) IGrowthReportDo
	Joins(fields ...field.RelationField) IGrowthReportDo
	Preload(fields ...field.RelationField) IGrowthReportDo
	FirstOrInit() (*model.GrowthReport, error)
	FirstOrCreate() (*model.GrowthReport, error)
	FindByPage(offset int, limit int) (result []*model.GrowthReport, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IGrowthReportDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (g growthReportDo) Debug() IGrowthReportDo {
	return g.withDO(g.DO.Debug())
}

func (g growthReportDo) WithContext(ctx context.Context) IGrowthReportDo {
	return g.withDO(g.DO.WithContext(ctx))
}

func (g growthReportDo) ReadDB() IGrowthReportDo {
	return g.Clauses(dbresolver.Read)
}

func (g growthReportDo) WriteDB() IGrowthReportDo {
	return g.Clauses(dbresolver.Write)
}

func (g growthReportDo) Session(config *gorm.Session) IGrowthReportDo {
	return g.withDO(g.DO.Session(config))
}

func (g growthReportDo) Clauses(conds ...clause.Expression) IGrowthReportDo {
	return g.withDO(g.DO.Clauses(conds...))
}

func (g growthReportDo) Returning(value interface{}, columns ...string) IGrowthReportDo {
	return g.withDO(g.DO.Returning(value, columns...))
}

func (g growthReportDo) Not(conds ...gen.Condition) IGrowthReportDo {
	return g.withDO(g.DO.Not(conds...))
}

func (g growthReportDo) Or(conds ...gen.Condition) IGrowthReportDo {
	return g.withDO(g.DO.Or(conds...))
}

func (g growthReportDo) Select(conds ...field.Expr) IGrowthReportDo {
	return g.withDO(g.DO.Select(conds...))
}

func (g growthReportDo) Where(conds ...gen.Condition) IGrowthReportDo {
	return g.withDO(g.DO.Where(conds...))
}

func (g growthReportDo) Order(conds ...field.Expr) IGrowthReportDo {
	return g.withDO(g.DO.Order(conds...))
}

func (g growthReportDo) Distinct(cols ...field.Expr) IGrowthReportDo {
	return g.withDO(g.DO.Distinct(cols...))
}

func (g growthReportDo) Omit(cols ...field.Expr) IGrowthReportDo {
	return g.withDO(g.DO.Omit(cols...))
}

func (g growthReportDo) Join(table schema.Tabler, on ...field.Expr) IGrowthReportDo {
	return g.withDO(g.DO.Join(table, on...))
}

func (g growthReportDo) LeftJoin(table schema.Tabler, on ...field.Expr) IGrowthReportDo {
	return g.withDO(g.DO.LeftJoin(table, on...))
}

func (g growthReportDo) RightJoin(table schema.Tabler, on ...field.Expr) IGrowthReportDo {
	return g.withDO(g.DO.RightJoin(table, on...))
}

func (g growthReportDo) Group(cols ...field.Expr) IGrowthReportDo {
	return g.withDO(g.DO.Group(cols...))
}

func (g growthReportDo) Having(conds ...gen.Condition) IGrowthReportDo {
	return g.withDO(g.DO.Having(conds...))
}

func (g growthReportDo) Limit(limit int) IGrowthReportDo {
	return g.withDO(g.DO.Limit(limit))
}

func (g growthReportDo) Offset(offset int) IGrowthReportDo {
	return g.withDO(g.DO.Offset(offset))
}

func (g growthReportDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IGrowthReportDo {
	return g.withDO(g.DO.Scopes(funcs...))
}

func (g growthReportDo) Unscoped() IGrowthReportDo {
	return g.withDO(g.DO.Unscoped())
}

func (g growthReportDo) Create(values ...*model.GrowthReport) error {
	if len(values) == 0 {
		return nil
	}
	return g.DO.Create(values)
}

func (g growthReportDo) CreateInBatches(values []*model.GrowthReport, batchSize int) error {
	return g.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (g growthReportDo) Save(values ...*model.GrowthReport) error {
	if len(values) == 0 {
		return nil
	}
	return g.DO.Save(values)
}

func (g growthReportDo) First() (*model.GrowthReport, error) {
	if result, err := g.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.GrowthReport), nil
	}
}

func (g growthReportDo) Take() (*model.GrowthReport, error) {
	if result, err := g.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.GrowthReport), nil
	}
}

func (g growthReportDo) Last() (*model.GrowthReport, error) {
	if result, err := g.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.GrowthReport), nil
	}
}

func (g growthReportDo) Find() ([]*model.GrowthReport, error) {
	result, err := g.DO.Find()
	return result.([]*model.GrowthReport), err
}

func (g growthReportDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.GrowthReport, err error) {
	buf := make([]*model.GrowthReport, 0, batchSize)
	err = g.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (g growthReportDo) FindInBatches(result *[]*model.GrowthReport, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return g.DO.FindInBatches(result, batchSize, fc)
}

func (g growthReportDo) Attrs(attrs ...field.AssignExpr) IGrowthReportDo {
	return g.withDO(g.DO.Attrs(attrs...))
}

func (g growthReportDo) Assign(attrs ...field.AssignExpr) IGrowthReportDo {
	return g.withDO(g.DO.Assign(attrs...))
}

func (g growthReportDo) Joins(fields ...field.RelationField) IGrowthReportDo {
	for _, _f := range fields {
		g = *g.withDO(g.DO.Joins(_f))
	}
	return &g
}

func (g growthReportDo) Preload(fields ...field.RelationField) IGrowthReportDo {
	for _, _f := range fields {
		g = *g.withDO(g.DO.Preload(_f))
	}
	return &g
}

func (g growthReportDo) FirstOrInit() (*model.GrowthReport, error) {
	if result, err := g.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.GrowthReport), nil
	}
}

func (g growthReportDo) FirstOrCreate() (*model.GrowthReport, error) {
	if result, err := g.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.GrowthReport), nil
	}
}

func (g growthReportDo) FindByPage(offset int, limit int) (result []*model.GrowthReport, count int64, err error) {
	result, err = g.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = g.Offset(-1).Limit(-1).Count()
	return
}

func (g growthReportDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = g.Count()
	if err != nil {
		return
	}

	err = g.Offset(offset).Limit(limit).Scan(result)
	return
}

func (g growthReportDo) Scan(result interface{}) (err error) {
	return g.DO.Scan(result)
}

func (g growthReportDo) Delete(models ...*model.GrowthReport) (result gen.ResultInfo, err error) {
	return g.DO.Delete(models)
}

func (g *growthReportDo) withDO(do gen.Dao) *growthReportDo {
	g.DO = *do.(*gen.DO)
	return g
}
