// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"aibuddy/internal/model"
)

func newOtaResource(db *gorm.DB, opts ...gen.DOOption) otaResource {
	_otaResource := otaResource{}

	_otaResource.otaResourceDo.UseDB(db, opts...)
	_otaResource.otaResourceDo.UseModel(&model.OtaResource{})

	tableName := _otaResource.otaResourceDo.TableName()
	_otaResource.ALL = field.NewAsterisk(tableName)
	_otaResource.ID = field.NewInt(tableName, "id")
	_otaResource.Version = field.NewString(tableName, "version")
	_otaResource.OtaURL = field.NewString(tableName, "ota_url")
	_otaResource.ModelURL = field.NewString(tableName, "model_url")
	_otaResource.ResourceURL = field.NewString(tableName, "resource_url")
	_otaResource.ForceUpdate = field.NewBool(tableName, "force_update")
	_otaResource.BoardType = field.NewString(tableName, "board_type")
	_otaResource.CreatedAt = field.NewTime(tableName, "created_at")
	_otaResource.UpdatedAt = field.NewTime(tableName, "updated_at")

	_otaResource.fillFieldMap()

	return _otaResource
}

type otaResource struct {
	otaResourceDo

	ALL         field.Asterisk
	ID          field.Int
	Version     field.String // 版本号
	OtaURL      field.String // OTA下载地址
	ModelURL    field.String // 模型下载地址
	ResourceURL field.String // 资源下载地址
	ForceUpdate field.Bool   // 是否强制更新
	BoardType   field.String // 板型
	CreatedAt   field.Time
	UpdatedAt   field.Time

	fieldMap map[string]field.Expr
}

func (o otaResource) Table(newTableName string) *otaResource {
	o.otaResourceDo.UseTable(newTableName)
	return o.updateTableName(newTableName)
}

func (o otaResource) As(alias string) *otaResource {
	o.otaResourceDo.DO = *(o.otaResourceDo.As(alias).(*gen.DO))
	return o.updateTableName(alias)
}

func (o *otaResource) updateTableName(table string) *otaResource {
	o.ALL = field.NewAsterisk(table)
	o.ID = field.NewInt(table, "id")
	o.Version = field.NewString(table, "version")
	o.OtaURL = field.NewString(table, "ota_url")
	o.ModelURL = field.NewString(table, "model_url")
	o.ResourceURL = field.NewString(table, "resource_url")
	o.ForceUpdate = field.NewBool(table, "force_update")
	o.BoardType = field.NewString(table, "board_type")
	o.CreatedAt = field.NewTime(table, "created_at")
	o.UpdatedAt = field.NewTime(table, "updated_at")

	o.fillFieldMap()

	return o
}

func (o *otaResource) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := o.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (o *otaResource) fillFieldMap() {
	o.fieldMap = make(map[string]field.Expr, 9)
	o.fieldMap["id"] = o.ID
	o.fieldMap["version"] = o.Version
	o.fieldMap["ota_url"] = o.OtaURL
	o.fieldMap["model_url"] = o.ModelURL
	o.fieldMap["resource_url"] = o.ResourceURL
	o.fieldMap["force_update"] = o.ForceUpdate
	o.fieldMap["board_type"] = o.BoardType
	o.fieldMap["created_at"] = o.CreatedAt
	o.fieldMap["updated_at"] = o.UpdatedAt
}

func (o otaResource) clone(db *gorm.DB) otaResource {
	o.otaResourceDo.ReplaceConnPool(db.Statement.ConnPool)
	return o
}

func (o otaResource) replaceDB(db *gorm.DB) otaResource {
	o.otaResourceDo.ReplaceDB(db)
	return o
}

type otaResourceDo struct{ gen.DO }

type IOtaResourceDo interface {
	gen.SubQuery
	Debug() IOtaResourceDo
	WithContext(ctx context.Context) IOtaResourceDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IOtaResourceDo
	WriteDB() IOtaResourceDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IOtaResourceDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IOtaResourceDo
	Not(conds ...gen.Condition) IOtaResourceDo
	Or(conds ...gen.Condition) IOtaResourceDo
	Select(conds ...field.Expr) IOtaResourceDo
	Where(conds ...gen.Condition) IOtaResourceDo
	Order(conds ...field.Expr) IOtaResourceDo
	Distinct(cols ...field.Expr) IOtaResourceDo
	Omit(cols ...field.Expr) IOtaResourceDo
	Join(table schema.Tabler, on ...field.Expr) IOtaResourceDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IOtaResourceDo
	RightJoin(table schema.Tabler, on ...field.Expr) IOtaResourceDo
	Group(cols ...field.Expr) IOtaResourceDo
	Having(conds ...gen.Condition) IOtaResourceDo
	Limit(limit int) IOtaResourceDo
	Offset(offset int) IOtaResourceDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IOtaResourceDo
	Unscoped() IOtaResourceDo
	Create(values ...*model.OtaResource) error
	CreateInBatches(values []*model.OtaResource, batchSize int) error
	Save(values ...*model.OtaResource) error
	First() (*model.OtaResource, error)
	Take() (*model.OtaResource, error)
	Last() (*model.OtaResource, error)
	Find() ([]*model.OtaResource, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.OtaResource, err error)
	FindInBatches(result *[]*model.OtaResource, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.OtaResource) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IOtaResourceDo
	Assign(attrs ...field.AssignExpr) IOtaResourceDo
	Joins(fields ...field.RelationField) IOtaResourceDo
	Preload(fields ...field.RelationField) IOtaResourceDo
	FirstOrInit() (*model.OtaResource, error)
	FirstOrCreate() (*model.OtaResource, error)
	FindByPage(offset int, limit int) (result []*model.OtaResource, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IOtaResourceDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (o otaResourceDo) Debug() IOtaResourceDo {
	return o.withDO(o.DO.Debug())
}

func (o otaResourceDo) WithContext(ctx context.Context) IOtaResourceDo {
	return o.withDO(o.DO.WithContext(ctx))
}

func (o otaResourceDo) ReadDB() IOtaResourceDo {
	return o.Clauses(dbresolver.Read)
}

func (o otaResourceDo) WriteDB() IOtaResourceDo {
	return o.Clauses(dbresolver.Write)
}

func (o otaResourceDo) Session(config *gorm.Session) IOtaResourceDo {
	return o.withDO(o.DO.Session(config))
}

func (o otaResourceDo) Clauses(conds ...clause.Expression) IOtaResourceDo {
	return o.withDO(o.DO.Clauses(conds...))
}

func (o otaResourceDo) Returning(value interface{}, columns ...string) IOtaResourceDo {
	return o.withDO(o.DO.Returning(value, columns...))
}

func (o otaResourceDo) Not(conds ...gen.Condition) IOtaResourceDo {
	return o.withDO(o.DO.Not(conds...))
}

func (o otaResourceDo) Or(conds ...gen.Condition) IOtaResourceDo {
	return o.withDO(o.DO.Or(conds...))
}

func (o otaResourceDo) Select(conds ...field.Expr) IOtaResourceDo {
	return o.withDO(o.DO.Select(conds...))
}

func (o otaResourceDo) Where(conds ...gen.Condition) IOtaResourceDo {
	return o.withDO(o.DO.Where(conds...))
}

func (o otaResourceDo) Order(conds ...field.Expr) IOtaResourceDo {
	return o.withDO(o.DO.Order(conds...))
}

func (o otaResourceDo) Distinct(cols ...field.Expr) IOtaResourceDo {
	return o.withDO(o.DO.Distinct(cols...))
}

func (o otaResourceDo) Omit(cols ...field.Expr) IOtaResourceDo {
	return o.withDO(o.DO.Omit(cols...))
}

func (o otaResourceDo) Join(table schema.Tabler, on ...field.Expr) IOtaResourceDo {
	return o.withDO(o.DO.Join(table, on...))
}

func (o otaResourceDo) LeftJoin(table schema.Tabler, on ...field.Expr) IOtaResourceDo {
	return o.withDO(o.DO.LeftJoin(table, on...))
}

func (o otaResourceDo) RightJoin(table schema.Tabler, on ...field.Expr) IOtaResourceDo {
	return o.withDO(o.DO.RightJoin(table, on...))
}

func (o otaResourceDo) Group(cols ...field.Expr) IOtaResourceDo {
	return o.withDO(o.DO.Group(cols...))
}

func (o otaResourceDo) Having(conds ...gen.Condition) IOtaResourceDo {
	return o.withDO(o.DO.Having(conds...))
}

func (o otaResourceDo) Limit(limit int) IOtaResourceDo {
	return o.withDO(o.DO.Limit(limit))
}

func (o otaResourceDo) Offset(offset int) IOtaResourceDo {
	return o.withDO(o.DO.Offset(offset))
}

func (o otaResourceDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IOtaResourceDo {
	return o.withDO(o.DO.Scopes(funcs...))
}

func (o otaResourceDo) Unscoped() IOtaResourceDo {
	return o.withDO(o.DO.Unscoped())
}

func (o otaResourceDo) Create(values ...*model.OtaResource) error {
	if len(values) == 0 {
		return nil
	}
	return o.DO.Create(values)
}

func (o otaResourceDo) CreateInBatches(values []*model.OtaResource, batchSize int) error {
	return o.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (o otaResourceDo) Save(values ...*model.OtaResource) error {
	if len(values) == 0 {
		return nil
	}
	return o.DO.Save(values)
}

func (o otaResourceDo) First() (*model.OtaResource, error) {
	if result, err := o.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.OtaResource), nil
	}
}

func (o otaResourceDo) Take() (*model.OtaResource, error) {
	if result, err := o.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.OtaResource), nil
	}
}

func (o otaResourceDo) Last() (*model.OtaResource, error) {
	if result, err := o.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.OtaResource), nil
	}
}

func (o otaResourceDo) Find() ([]*model.OtaResource, error) {
	result, err := o.DO.Find()
	return result.([]*model.OtaResource), err
}

func (o otaResourceDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.OtaResource, err error) {
	buf := make([]*model.OtaResource, 0, batchSize)
	err = o.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (o otaResourceDo) FindInBatches(result *[]*model.OtaResource, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return o.DO.FindInBatches(result, batchSize, fc)
}

func (o otaResourceDo) Attrs(attrs ...field.AssignExpr) IOtaResourceDo {
	return o.withDO(o.DO.Attrs(attrs...))
}

func (o otaResourceDo) Assign(attrs ...field.AssignExpr) IOtaResourceDo {
	return o.withDO(o.DO.Assign(attrs...))
}

func (o otaResourceDo) Joins(fields ...field.RelationField) IOtaResourceDo {
	for _, _f := range fields {
		o = *o.withDO(o.DO.Joins(_f))
	}
	return &o
}

func (o otaResourceDo) Preload(fields ...field.RelationField) IOtaResourceDo {
	for _, _f := range fields {
		o = *o.withDO(o.DO.Preload(_f))
	}
	return &o
}

func (o otaResourceDo) FirstOrInit() (*model.OtaResource, error) {
	if result, err := o.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.OtaResource), nil
	}
}

func (o otaResourceDo) FirstOrCreate() (*model.OtaResource, error) {
	if result, err := o.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.OtaResource), nil
	}
}

func (o otaResourceDo) FindByPage(offset int, limit int) (result []*model.OtaResource, count int64, err error) {
	result, err = o.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = o.Offset(-1).Limit(-1).Count()
	return
}

func (o otaResourceDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = o.Count()
	if err != nil {
		return
	}

	err = o.Offset(offset).Limit(limit).Scan(result)
	return
}

func (o otaResourceDo) Scan(result interface{}) (err error) {
	return o.DO.Scan(result)
}

func (o otaResourceDo) Delete(models ...*model.OtaResource) (result gen.ResultInfo, err error) {
	return o.DO.Delete(models)
}

func (o *otaResourceDo) withDO(do gen.Dao) *otaResourceDo {
	o.DO = *do.(*gen.DO)
	return o
}
