// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"aibuddy/internal/model"
)

func newEmotion(db *gorm.DB, opts ...gen.DOOption) emotion {
	_emotion := emotion{}

	_emotion.emotionDo.UseDB(db, opts...)
	_emotion.emotionDo.UseModel(&model.Emotion{})

	tableName := _emotion.emotionDo.TableName()
	_emotion.ALL = field.NewAsterisk(tableName)
	_emotion.ID = field.NewInt64(tableName, "id")
	_emotion.DeviceID = field.NewString(tableName, "device_id")
	_emotion.DialogueID = field.NewInt64(tableName, "dialogue_id")
	_emotion.TriggerWarning = field.NewBool(tableName, "trigger_warning")
	_emotion.WarningLevel = field.NewString(tableName, "warning_level")
	_emotion.WarningTypes = field.NewField(tableName, "warning_types")
	_emotion.Confidence = field.NewFloat64(tableName, "confidence")
	_emotion.WarningReason = field.NewField(tableName, "warning_reason")
	_emotion.Evidence = field.NewField(tableName, "evidence")
	_emotion.ParentSuggestions = field.NewField(tableName, "parent_suggestions")
	_emotion.NeedManualFollowup = field.NewBool(tableName, "need_manual_followup")
	_emotion.PrivacyRisk = field.NewField(tableName, "privacy_risk")
	_emotion.ScamRisk = field.NewField(tableName, "scam_risk")
	_emotion.EmotionalRisk = field.NewField(tableName, "emotional_risk")
	_emotion.OverallAssessment = field.NewString(tableName, "overall_assessment")
	_emotion.Read = field.NewBool(tableName, "read")
	_emotion.CreatedAt = field.NewField(tableName, "created_at")
	_emotion.UpdatedAt = field.NewField(tableName, "updated_at")

	_emotion.fillFieldMap()

	return _emotion
}

type emotion struct {
	emotionDo

	ALL                field.Asterisk
	ID                 field.Int64
	DeviceID           field.String  // 设备ID
	DialogueID         field.Int64   // 关联的对话记录ID
	TriggerWarning     field.Bool    // 是否触发预警
	WarningLevel       field.String  // 预警等级(低/中/高)
	WarningTypes       field.Field   // 预警类型,逗号分隔
	Confidence         field.Float64 // 置信度(0-1)
	WarningReason      field.Field   // 预警原因
	Evidence           field.Field   // 证据
	ParentSuggestions  field.Field   // 家长建议
	NeedManualFollowup field.Bool    // 是否需要人工跟进
	PrivacyRisk        field.Field   // 隐私风险
	ScamRisk           field.Field   // 诈骗风险
	EmotionalRisk      field.Field   // 情绪风险
	OverallAssessment  field.String  // 整体评估
	Read               field.Bool    // 是否已读
	CreatedAt          field.Field   // 创建时间
	UpdatedAt          field.Field   // 更新时间

	fieldMap map[string]field.Expr
}

func (e emotion) Table(newTableName string) *emotion {
	e.emotionDo.UseTable(newTableName)
	return e.updateTableName(newTableName)
}

func (e emotion) As(alias string) *emotion {
	e.emotionDo.DO = *(e.emotionDo.As(alias).(*gen.DO))
	return e.updateTableName(alias)
}

func (e *emotion) updateTableName(table string) *emotion {
	e.ALL = field.NewAsterisk(table)
	e.ID = field.NewInt64(table, "id")
	e.DeviceID = field.NewString(table, "device_id")
	e.DialogueID = field.NewInt64(table, "dialogue_id")
	e.TriggerWarning = field.NewBool(table, "trigger_warning")
	e.WarningLevel = field.NewString(table, "warning_level")
	e.WarningTypes = field.NewField(table, "warning_types")
	e.Confidence = field.NewFloat64(table, "confidence")
	e.WarningReason = field.NewField(table, "warning_reason")
	e.Evidence = field.NewField(table, "evidence")
	e.ParentSuggestions = field.NewField(table, "parent_suggestions")
	e.NeedManualFollowup = field.NewBool(table, "need_manual_followup")
	e.PrivacyRisk = field.NewField(table, "privacy_risk")
	e.ScamRisk = field.NewField(table, "scam_risk")
	e.EmotionalRisk = field.NewField(table, "emotional_risk")
	e.OverallAssessment = field.NewString(table, "overall_assessment")
	e.Read = field.NewBool(table, "read")
	e.CreatedAt = field.NewField(table, "created_at")
	e.UpdatedAt = field.NewField(table, "updated_at")

	e.fillFieldMap()

	return e
}

func (e *emotion) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := e.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (e *emotion) fillFieldMap() {
	e.fieldMap = make(map[string]field.Expr, 18)
	e.fieldMap["id"] = e.ID
	e.fieldMap["device_id"] = e.DeviceID
	e.fieldMap["dialogue_id"] = e.DialogueID
	e.fieldMap["trigger_warning"] = e.TriggerWarning
	e.fieldMap["warning_level"] = e.WarningLevel
	e.fieldMap["warning_types"] = e.WarningTypes
	e.fieldMap["confidence"] = e.Confidence
	e.fieldMap["warning_reason"] = e.WarningReason
	e.fieldMap["evidence"] = e.Evidence
	e.fieldMap["parent_suggestions"] = e.ParentSuggestions
	e.fieldMap["need_manual_followup"] = e.NeedManualFollowup
	e.fieldMap["privacy_risk"] = e.PrivacyRisk
	e.fieldMap["scam_risk"] = e.ScamRisk
	e.fieldMap["emotional_risk"] = e.EmotionalRisk
	e.fieldMap["overall_assessment"] = e.OverallAssessment
	e.fieldMap["read"] = e.Read
	e.fieldMap["created_at"] = e.CreatedAt
	e.fieldMap["updated_at"] = e.UpdatedAt
}

func (e emotion) clone(db *gorm.DB) emotion {
	e.emotionDo.ReplaceConnPool(db.Statement.ConnPool)
	return e
}

func (e emotion) replaceDB(db *gorm.DB) emotion {
	e.emotionDo.ReplaceDB(db)
	return e
}

type emotionDo struct{ gen.DO }

type IEmotionDo interface {
	gen.SubQuery
	Debug() IEmotionDo
	WithContext(ctx context.Context) IEmotionDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IEmotionDo
	WriteDB() IEmotionDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IEmotionDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IEmotionDo
	Not(conds ...gen.Condition) IEmotionDo
	Or(conds ...gen.Condition) IEmotionDo
	Select(conds ...field.Expr) IEmotionDo
	Where(conds ...gen.Condition) IEmotionDo
	Order(conds ...field.Expr) IEmotionDo
	Distinct(cols ...field.Expr) IEmotionDo
	Omit(cols ...field.Expr) IEmotionDo
	Join(table schema.Tabler, on ...field.Expr) IEmotionDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IEmotionDo
	RightJoin(table schema.Tabler, on ...field.Expr) IEmotionDo
	Group(cols ...field.Expr) IEmotionDo
	Having(conds ...gen.Condition) IEmotionDo
	Limit(limit int) IEmotionDo
	Offset(offset int) IEmotionDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IEmotionDo
	Unscoped() IEmotionDo
	Create(values ...*model.Emotion) error
	CreateInBatches(values []*model.Emotion, batchSize int) error
	Save(values ...*model.Emotion) error
	First() (*model.Emotion, error)
	Take() (*model.Emotion, error)
	Last() (*model.Emotion, error)
	Find() ([]*model.Emotion, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Emotion, err error)
	FindInBatches(result *[]*model.Emotion, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.Emotion) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IEmotionDo
	Assign(attrs ...field.AssignExpr) IEmotionDo
	Joins(fields ...field.RelationField) IEmotionDo
	Preload(fields ...field.RelationField) IEmotionDo
	FirstOrInit() (*model.Emotion, error)
	FirstOrCreate() (*model.Emotion, error)
	FindByPage(offset int, limit int) (result []*model.Emotion, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IEmotionDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (e emotionDo) Debug() IEmotionDo {
	return e.withDO(e.DO.Debug())
}

func (e emotionDo) WithContext(ctx context.Context) IEmotionDo {
	return e.withDO(e.DO.WithContext(ctx))
}

func (e emotionDo) ReadDB() IEmotionDo {
	return e.Clauses(dbresolver.Read)
}

func (e emotionDo) WriteDB() IEmotionDo {
	return e.Clauses(dbresolver.Write)
}

func (e emotionDo) Session(config *gorm.Session) IEmotionDo {
	return e.withDO(e.DO.Session(config))
}

func (e emotionDo) Clauses(conds ...clause.Expression) IEmotionDo {
	return e.withDO(e.DO.Clauses(conds...))
}

func (e emotionDo) Returning(value interface{}, columns ...string) IEmotionDo {
	return e.withDO(e.DO.Returning(value, columns...))
}

func (e emotionDo) Not(conds ...gen.Condition) IEmotionDo {
	return e.withDO(e.DO.Not(conds...))
}

func (e emotionDo) Or(conds ...gen.Condition) IEmotionDo {
	return e.withDO(e.DO.Or(conds...))
}

func (e emotionDo) Select(conds ...field.Expr) IEmotionDo {
	return e.withDO(e.DO.Select(conds...))
}

func (e emotionDo) Where(conds ...gen.Condition) IEmotionDo {
	return e.withDO(e.DO.Where(conds...))
}

func (e emotionDo) Order(conds ...field.Expr) IEmotionDo {
	return e.withDO(e.DO.Order(conds...))
}

func (e emotionDo) Distinct(cols ...field.Expr) IEmotionDo {
	return e.withDO(e.DO.Distinct(cols...))
}

func (e emotionDo) Omit(cols ...field.Expr) IEmotionDo {
	return e.withDO(e.DO.Omit(cols...))
}

func (e emotionDo) Join(table schema.Tabler, on ...field.Expr) IEmotionDo {
	return e.withDO(e.DO.Join(table, on...))
}

func (e emotionDo) LeftJoin(table schema.Tabler, on ...field.Expr) IEmotionDo {
	return e.withDO(e.DO.LeftJoin(table, on...))
}

func (e emotionDo) RightJoin(table schema.Tabler, on ...field.Expr) IEmotionDo {
	return e.withDO(e.DO.RightJoin(table, on...))
}

func (e emotionDo) Group(cols ...field.Expr) IEmotionDo {
	return e.withDO(e.DO.Group(cols...))
}

func (e emotionDo) Having(conds ...gen.Condition) IEmotionDo {
	return e.withDO(e.DO.Having(conds...))
}

func (e emotionDo) Limit(limit int) IEmotionDo {
	return e.withDO(e.DO.Limit(limit))
}

func (e emotionDo) Offset(offset int) IEmotionDo {
	return e.withDO(e.DO.Offset(offset))
}

func (e emotionDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IEmotionDo {
	return e.withDO(e.DO.Scopes(funcs...))
}

func (e emotionDo) Unscoped() IEmotionDo {
	return e.withDO(e.DO.Unscoped())
}

func (e emotionDo) Create(values ...*model.Emotion) error {
	if len(values) == 0 {
		return nil
	}
	return e.DO.Create(values)
}

func (e emotionDo) CreateInBatches(values []*model.Emotion, batchSize int) error {
	return e.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (e emotionDo) Save(values ...*model.Emotion) error {
	if len(values) == 0 {
		return nil
	}
	return e.DO.Save(values)
}

func (e emotionDo) First() (*model.Emotion, error) {
	if result, err := e.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.Emotion), nil
	}
}

func (e emotionDo) Take() (*model.Emotion, error) {
	if result, err := e.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.Emotion), nil
	}
}

func (e emotionDo) Last() (*model.Emotion, error) {
	if result, err := e.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.Emotion), nil
	}
}

func (e emotionDo) Find() ([]*model.Emotion, error) {
	result, err := e.DO.Find()
	return result.([]*model.Emotion), err
}

func (e emotionDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Emotion, err error) {
	buf := make([]*model.Emotion, 0, batchSize)
	err = e.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (e emotionDo) FindInBatches(result *[]*model.Emotion, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return e.DO.FindInBatches(result, batchSize, fc)
}

func (e emotionDo) Attrs(attrs ...field.AssignExpr) IEmotionDo {
	return e.withDO(e.DO.Attrs(attrs...))
}

func (e emotionDo) Assign(attrs ...field.AssignExpr) IEmotionDo {
	return e.withDO(e.DO.Assign(attrs...))
}

func (e emotionDo) Joins(fields ...field.RelationField) IEmotionDo {
	for _, _f := range fields {
		e = *e.withDO(e.DO.Joins(_f))
	}
	return &e
}

func (e emotionDo) Preload(fields ...field.RelationField) IEmotionDo {
	for _, _f := range fields {
		e = *e.withDO(e.DO.Preload(_f))
	}
	return &e
}

func (e emotionDo) FirstOrInit() (*model.Emotion, error) {
	if result, err := e.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.Emotion), nil
	}
}

func (e emotionDo) FirstOrCreate() (*model.Emotion, error) {
	if result, err := e.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.Emotion), nil
	}
}

func (e emotionDo) FindByPage(offset int, limit int) (result []*model.Emotion, count int64, err error) {
	result, err = e.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = e.Offset(-1).Limit(-1).Count()
	return
}

func (e emotionDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = e.Count()
	if err != nil {
		return
	}

	err = e.Offset(offset).Limit(limit).Scan(result)
	return
}

func (e emotionDo) Scan(result interface{}) (err error) {
	return e.DO.Scan(result)
}

func (e emotionDo) Delete(models ...*model.Emotion) (result gen.ResultInfo, err error) {
	return e.DO.Delete(models)
}

func (e *emotionDo) withDO(do gen.Dao) *emotionDo {
	e.DO = *do.(*gen.DO)
	return e
}
