// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"

	"gorm.io/gen"

	"gorm.io/plugin/dbresolver"
)

var (
	Q           = new(Query)
	Agent       *agent
	Device      *device
	DeviceInfo  *deviceInfo
	DeviceOta   *deviceOta
	DeviceSN    *deviceSN
	OtaResource *otaResource
	Reminder    *reminder
	User        *user
)

func SetDefault(db *gorm.DB, opts ...gen.DOOption) {
	*Q = *Use(db, opts...)
	Agent = &Q.Agent
	Device = &Q.Device
	DeviceInfo = &Q.DeviceInfo
	DeviceOta = &Q.DeviceOta
	DeviceSN = &Q.DeviceSN
	OtaResource = &Q.OtaResource
	Reminder = &Q.Reminder
	User = &Q.User
}

func Use(db *gorm.DB, opts ...gen.DOOption) *Query {
	return &Query{
		db:          db,
		Agent:       newAgent(db, opts...),
		Device:      newDevice(db, opts...),
		DeviceInfo:  newDeviceInfo(db, opts...),
		DeviceOta:   newDeviceOta(db, opts...),
		DeviceSN:    newDeviceSN(db, opts...),
		OtaResource: newOtaResource(db, opts...),
		Reminder:    newReminder(db, opts...),
		User:        newUser(db, opts...),
	}
}

type Query struct {
	db *gorm.DB

	Agent       agent
	Device      device
	DeviceInfo  deviceInfo
	DeviceOta   deviceOta
	DeviceSN    deviceSN
	OtaResource otaResource
	Reminder    reminder
	User        user
}

func (q *Query) Available() bool { return q.db != nil }

func (q *Query) clone(db *gorm.DB) *Query {
	return &Query{
		db:          db,
		Agent:       q.Agent.clone(db),
		Device:      q.Device.clone(db),
		DeviceInfo:  q.DeviceInfo.clone(db),
		DeviceOta:   q.DeviceOta.clone(db),
		DeviceSN:    q.DeviceSN.clone(db),
		OtaResource: q.OtaResource.clone(db),
		Reminder:    q.Reminder.clone(db),
		User:        q.User.clone(db),
	}
}

func (q *Query) ReadDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Read))
}

func (q *Query) WriteDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Write))
}

func (q *Query) ReplaceDB(db *gorm.DB) *Query {
	return &Query{
		db:          db,
		Agent:       q.Agent.replaceDB(db),
		Device:      q.Device.replaceDB(db),
		DeviceInfo:  q.DeviceInfo.replaceDB(db),
		DeviceOta:   q.DeviceOta.replaceDB(db),
		DeviceSN:    q.DeviceSN.replaceDB(db),
		OtaResource: q.OtaResource.replaceDB(db),
		Reminder:    q.Reminder.replaceDB(db),
		User:        q.User.replaceDB(db),
	}
}

type queryCtx struct {
	Agent       IAgentDo
	Device      IDeviceDo
	DeviceInfo  IDeviceInfoDo
	DeviceOta   IDeviceOtaDo
	DeviceSN    IDeviceSNDo
	OtaResource IOtaResourceDo
	Reminder    IReminderDo
	User        IUserDo
}

func (q *Query) WithContext(ctx context.Context) *queryCtx {
	return &queryCtx{
		Agent:       q.Agent.WithContext(ctx),
		Device:      q.Device.WithContext(ctx),
		DeviceInfo:  q.DeviceInfo.WithContext(ctx),
		DeviceOta:   q.DeviceOta.WithContext(ctx),
		DeviceSN:    q.DeviceSN.WithContext(ctx),
		OtaResource: q.OtaResource.WithContext(ctx),
		Reminder:    q.Reminder.WithContext(ctx),
		User:        q.User.WithContext(ctx),
	}
}

func (q *Query) Transaction(fc func(tx *Query) error, opts ...*sql.TxOptions) error {
	return q.db.Transaction(func(tx *gorm.DB) error { return fc(q.clone(tx)) }, opts...)
}

func (q *Query) Begin(opts ...*sql.TxOptions) *QueryTx {
	tx := q.db.Begin(opts...)
	return &QueryTx{Query: q.clone(tx), Error: tx.Error}
}

type QueryTx struct {
	*Query
	Error error
}

func (q *QueryTx) Commit() error {
	return q.db.Commit().Error
}

func (q *QueryTx) Rollback() error {
	return q.db.Rollback().Error
}

func (q *QueryTx) SavePoint(name string) error {
	return q.db.SavePoint(name).Error
}

func (q *QueryTx) RollbackTo(name string) error {
	return q.db.RollbackTo(name).Error
}
