app:
  name: "aibuddy_hub"
  host: "0.0.0.0"
  port: 9081
  log_level: "info"
  app_sercet: ""
  msg_send_count: 5
storage:
  database:
    host: "8.153.82.116"
    port: 5432
    name: "aibuddy"
    user: ""
    password: ""
  milvus:
    host: "127.0.0.1"
    port: 19530
    user: ""
    password: ""
  redis:
    host: "112.132.224.74"
    port: 6379
    password: ""
    db: 0
    username: ""
  flash:
    use: "redis"
wechat:
  app_id: ""
  app_secret: ""
agent:
  model:
    chat_model:
      model_name: ""
      api_key: ""
      api_url: ""
    work_model:
      model_name: ""
      api_key: ""
      api_url: ""
aliyun:
  ak: ""
  sk: ""
  sms:
    sign_name: "合肥绝对派智能科技"
    template_code: "SMS_487395253"
  mqtt:
    url: "tcp://post-cn-m414bwfgf03.mqtt.aliyuncs.com:1883"
    instance_id: "post-cn-m414bwfgf03"
    client_id_prefix: "GID_AIBuddy@@@"
    topic_prefix: "nlaibuddy"
    clean_session: false
    keep_alive: 60s
    reconnect:
      delay: 1000ms
tracer:
  service_name: "aibuddy_hub"
  endpoint: "112.132.224.74:4317"
