app:
  name: "aibuddy_hub"
  host: "0.0.0.0"
  port: 9081
  log_level: "error"
storage:
  database:
    host: "localhost"
    port: 5432
    name: "aibuddy"
    user: "dev"
    password: "dev"
  redis:
    host: "112.132.224.74"
    port: 6379
    password: "123456"
    db: 0
  flash:
    use: "redis"
agent:
  model:
    chat_model:
      model_name: ""
      api_key: ""
      api_url: ""
    work_model:
      model_name: ""
      api_key: ""
      api_url: ""
